"""
One definition of "the units WASM manages", read by every view.

On the owner's production fifteen application units and ``wasm-monitor`` all
carried the ``Generated by WASM`` marker, and the console's top bar still said
"Units 1": :meth:`ServiceManager.list_services` asked systemd for ``wasm-*``
plus the names in the services table, while application units have had no
prefix since 0.14.1 and the table had no row for them. The Services page read
another source, so the two disagreed; "show all units" failed as a whole on the
first name systemd had escaped; and the live log stream derived a unit from the
domain alone, so legacy, monorepo and Compose units were refused.

What is pinned here, all through the real manager on a fake runner:

- an application unit counts whether or not it has a prefix or a store row;
- the top bar's tally is exactly the Services page's list;
- a monorepo's workspace units and a legacy ``wasm-`` unit belong to their
  application;
- every unit on the machine is listed from one ``list-units``, escaped names
  included, without a probe per unit;
- the log stream finds an application's unit(s) the same way, says why a static
  site has nothing to stream, and forwards journalctl's own error;
- a deliberate start clears systemd's start limit first.
"""

from __future__ import annotations

import asyncio
from collections.abc import Iterator
from pathlib import Path
from typing import Any
from urllib.parse import quote

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient

from tests.test_web_auth import build_client
from tests.test_web_websockets import token_subprotocols
from wasm.core.runner import FakeRunner
from wasm.core.store import App, Service, WASMStore, get_store
from wasm.core.utils import domain_to_app_name
from wasm.managers.service_manager import (
    LIST_UNITS_ARGV,
    WASM_UNIT_MARKER,
    ServiceManager,
    readable_unit_name,
)
from wasm.web.api import services as services_api
from wasm.web.api.auth import get_current_session
from wasm.web.machine import AppTally, UnitTally, read_machine
from wasm.web.server import get_token_manager

LIST_UNITS = list(LIST_UNITS_ARGV)

#: A name exactly as systemd writes it for the fsck of a labelled disk.
ESCAPED = "systemd-fsck@dev-disk-by\\x2dlabel-BOOT"


# ------------------------------------------------------------------ fixtures


@pytest.fixture
def unit_dirs(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> dict[str, Path]:
    """
    Point the manager at a private managed directory and a distribution one.

    Returns:
        ``managed`` and ``distro``.
    """
    managed = tmp_path / "etc/systemd/system"
    distro = tmp_path / "usr/lib/systemd/system"
    for directory in (managed, distro):
        directory.mkdir(parents=True)
    monkeypatch.setattr(ServiceManager, "SYSTEMD_DIR", managed)
    monkeypatch.setattr(ServiceManager, "UNIT_SEARCH_DIRS", (managed, distro))
    return {"managed": managed, "distro": distro}


@pytest.fixture
def store() -> Iterator[WASMStore]:
    """
    The process-wide store, at the per-test location conftest redirects it to.

    Yields:
        The store every manager and endpoint in the test reads.
    """
    WASMStore.reset_instance()
    instance = get_store()
    try:
        yield instance
    finally:
        WASMStore.reset_instance()


def marked(unit_dirs: dict[str, Path], name: str) -> Path:
    """
    Write a unit file as WASM's templates do.

    Args:
        unit_dirs: The unit directories.
        name: Unit name without ``.service``.

    Returns:
        The file.
    """
    path = unit_dirs["managed"] / f"{name}.service"
    path.write_text(f"# Systemd service for {name}\n# {WASM_UNIT_MARKER}\n[Service]\n")
    return path


def deploy(store: WASMStore, domain: str, **fields: Any) -> App:
    """
    Record an application.

    Args:
        store: The store.
        domain: Its domain.
        **fields: Overrides.

    Returns:
        The stored application.
    """
    values: dict[str, Any] = {
        "domain": domain,
        "app_type": "nextjs",
        "port": 3000,
        "app_path": f"/var/www/apps/{domain_to_app_name(domain)}",
        "is_static": False,
    }
    values.update(fields)
    return store.create_app(App(**values))


def listing(*rows: str) -> str:
    """
    Build ``systemctl list-units --plain`` output.

    Args:
        *rows: ``"name load active sub"`` lines, without the suffix.

    Returns:
        The output, header included.
    """
    lines = ["UNIT LOAD ACTIVE SUB DESCRIPTION"]
    for row in rows:
        name, rest = row.split(" ", 1)
        lines.append(f"{name}.service {rest} Description")
    return "\n".join(lines) + "\n"


@pytest.fixture
def api() -> TestClient:
    """
    The services router with authentication stubbed out.

    Returns:
        A client whose requests are authenticated.
    """
    app = FastAPI()
    app.include_router(services_api.router, prefix="/api/services")
    app.dependency_overrides[get_current_session] = lambda: {"session_id": "t", "type": "master"}
    return TestClient(app, raise_server_exceptions=False)


# ----------------------------------------------- the production failure itself


def test_app_units_without_prefix_or_store_row_are_counted(
    runner: FakeRunner, unit_dirs: dict[str, Path], store: WASMStore
) -> None:
    """The top bar said "Units 1" on a machine running fifteen applications."""
    for domain in ("qrboda.com", "tienda.arennalabs.com", "broken.example.com"):
        deploy(store, domain)
        marked(unit_dirs, domain_to_app_name(domain))
    marked(unit_dirs, "wasm-monitor")
    runner.script(
        LIST_UNITS,
        stdout=listing(
            "qrboda-com loaded active running",
            "tienda-arennalabs-com loaded active running",
            "broken-example-com loaded failed failed",
            "wasm-monitor loaded active running",
        ),
    )

    names = [row["name"] for row in ServiceManager().list_services()]
    state = read_machine(apps_root="/tmp")

    assert names == [
        "broken-example-com",
        "qrboda-com",
        "tienda-arennalabs-com",
        "wasm-monitor",
    ]
    assert state.units == UnitTally(running=3, failed=1, stopped=0)
    assert state.apps == AppTally(running=2, failed=1, stopped=0, static=0)


def test_the_listing_asks_systemd_for_full_unit_names(
    runner: FakeRunner, unit_dirs: dict[str, Path], store: WASMStore
) -> None:
    """list-units matches globs against "name.service": a bare name matches nothing."""
    deploy(store, "qrboda.com")
    marked(unit_dirs, "qrboda-com")

    ServiceManager().list_services()

    argv = next(call for call in runner.calls if call[:2] == ("systemctl", "list-units"))
    assert "qrboda-com.service" in argv
    assert "wasm-*" in argv
    assert "*" not in argv
    assert not any(call[:2] == ("systemctl", "show") for call in runner.calls), (
        "the listing is one list-units, never a probe per unit"
    )


def test_a_stopped_disabled_unit_systemd_has_not_loaded_is_still_listed(
    runner: FakeRunner, unit_dirs: dict[str, Path], store: WASMStore
) -> None:
    """systemd forgets a unit nothing uses; its file says it is there."""
    marked(unit_dirs, "idle-example-com")

    rows = ServiceManager().list_services()

    assert rows == [
        {
            "name": "idle-example-com",
            "load": "not-loaded",
            "active": "inactive",
            "sub": "dead",
            "managed": True,
            "app": None,
        }
    ]


def test_a_file_without_any_signal_is_not_listed(
    runner: FakeRunner, unit_dirs: dict[str, Path], store: WASMStore
) -> None:
    """A unit an operator wrote by hand next to ours is not ours."""
    (unit_dirs["managed"] / "ollama.service").write_text("[Service]\nExecStart=/bin/ollama\n")
    runner.script(LIST_UNITS, stdout=listing("ollama loaded active running"))

    assert ServiceManager().list_services() == []


def test_a_marked_file_shadowing_a_distribution_unit_is_not_listed(
    runner: FakeRunner, unit_dirs: dict[str, Path], store: WASMStore
) -> None:
    """The same rule inspect_unit applies: eclipsing nginx is a takeover, not a unit of ours."""
    marked(unit_dirs, "nginx")
    (unit_dirs["distro"] / "nginx.service").write_text("[Service]\n")

    assert ServiceManager().list_services() == []


def test_the_top_bar_tally_equals_the_services_list(
    runner: FakeRunner, unit_dirs: dict[str, Path], store: WASMStore, api: TestClient
) -> None:
    """Two implementations disagreed; now both read managed_units."""
    deploy(store, "one.example.com")
    marked(unit_dirs, "one-example-com")
    deploy(store, "old.example.com")
    marked(unit_dirs, "wasm-old-example-com")
    marked(unit_dirs, "wasm-monitor")
    marked(unit_dirs, "idle-example-com")
    store.create_service(Service(name="hand-made", command="/usr/bin/true"))
    marked(unit_dirs, "hand-made")
    runner.script(
        LIST_UNITS,
        stdout=listing(
            "one-example-com loaded active running",
            "wasm-old-example-com loaded failed failed",
            "wasm-monitor loaded active running",
            "hand-made loaded inactive dead",
        ),
    )

    tally = read_machine(apps_root="/tmp").units
    response = api.get("/api/services")

    assert response.status_code == 200, response.text
    body = response.json()
    assert body["total"] == tally.running + tally.failed + tally.stopped == 5
    assert {row["name"] for row in body["services"]} == {
        "one-example-com",
        "wasm-old-example-com",
        "wasm-monitor",
        "idle-example-com",
        "hand-made",
    }
    hand_made = next(row for row in body["services"] if row["name"] == "hand-made")
    assert hand_made["description"] == "/usr/bin/true"


def test_the_services_page_describes_every_managed_unit_in_one_call(
    runner: FakeRunner, unit_dirs: dict[str, Path], store: WASMStore, api: TestClient
) -> None:
    """PID, memory and boot setting come from one systemctl show, not three calls per unit."""
    marked(unit_dirs, "one-example-com")
    marked(unit_dirs, "two-example-com")
    runner.script(
        LIST_UNITS,
        stdout=listing(
            "one-example-com loaded active running", "two-example-com loaded inactive dead"
        ),
    )
    runner.script(
        ["systemctl", "show", "--no-pager"],
        stdout=(
            "Id=one-example-com.service\nActiveState=active\nSubState=running\n"
            "MainPID=4242\nMemoryCurrent=1048576\nUnitFileState=enabled\nNRestarts=0\n\n"
            "Id=two-example-com.service\nActiveState=inactive\nSubState=dead\n"
            "MainPID=0\nUnitFileState=disabled\nNRestarts=0\n"
        ),
    )

    body = api.get("/api/services").json()

    rows = {row["name"]: row for row in body["services"]}
    assert rows["one-example-com"]["pid"] == 4242
    assert rows["one-example-com"]["enabled"] is True
    assert rows["one-example-com"]["status"] == "running"
    assert rows["two-example-com"]["enabled"] is False
    assert rows["two-example-com"]["pid"] is None
    shows = [call for call in runner.calls if call[:2] == ("systemctl", "show")]
    assert len(shows) == 1
    assert not any(call[:2] == ("systemctl", "is-active") for call in runner.calls)


# ------------------------------------------------ monorepo, legacy, Compose


def test_a_monorepo_runs_as_its_workspace_units(
    runner: FakeRunner, unit_dirs: dict[str, Path], store: WASMStore
) -> None:
    """The services table records a row per workspace, carrying the app's id."""
    app = deploy(store, "mono.example.com", app_type="monorepo")
    for workspace in ("api", "web"):
        name = f"mono-example-com-{workspace}"
        store.create_service(Service(name=name, app_id=app.id))
        marked(unit_dirs, name)
    runner.script(
        LIST_UNITS,
        stdout=listing(
            "mono-example-com-api loaded active running",
            "mono-example-com-web loaded failed failed",
        ),
    )
    manager = ServiceManager()

    assert manager.app_units(app) == ["mono-example-com-api", "mono-example-com-web"]
    assert {row["name"]: row["app"] for row in manager.list_services()} == {
        "mono-example-com-api": "mono.example.com",
        "mono-example-com-web": "mono.example.com",
    }
    # One workspace down is an application down.
    assert read_machine(apps_root="/tmp").apps == AppTally(running=0, failed=1, stopped=0, static=0)


def test_a_monorepo_without_rows_is_found_from_its_unit_files(
    runner: FakeRunner, unit_dirs: dict[str, Path], store: WASMStore
) -> None:
    """A store that was moved or rebuilt has no rows; the marked files remain."""
    app = deploy(store, "mono.example.com", app_type="monorepo")
    marked(unit_dirs, "mono-example-com-api")
    marked(unit_dirs, "mono-example-com-web")

    assert ServiceManager().app_units(app) == ["mono-example-com-api", "mono-example-com-web"]


def test_a_legacy_prefixed_unit_belongs_to_its_application(
    runner: FakeRunner, unit_dirs: dict[str, Path], store: WASMStore
) -> None:
    """Units from before 0.14.1 are named wasm-<app>."""
    app = deploy(store, "old.example.com")
    marked(unit_dirs, "wasm-old-example-com")

    manager = ServiceManager()

    assert manager.app_units(app) == ["wasm-old-example-com"]
    assert manager.list_services()[0]["app"] == "old.example.com"


def test_a_legacy_unit_systemd_lists_but_whose_file_is_unseen_still_matches(
    runner: FakeRunner, unit_dirs: dict[str, Path], store: WASMStore
) -> None:
    """What systemd is running is the authority when the file is not visible."""
    deploy(store, "old.example.com")
    runner.script(LIST_UNITS, stdout=listing("wasm-old-example-com loaded active running"))

    rows = ServiceManager().list_services()

    assert rows[0]["name"] == "wasm-old-example-com"
    assert rows[0]["app"] == "old.example.com"
    assert read_machine(apps_root="/tmp").apps.running == 1


def test_a_compose_application_is_named_after_it(
    runner: FakeRunner, unit_dirs: dict[str, Path], store: WASMStore
) -> None:
    """A Compose project's unit carries the application's name, like any other."""
    app = deploy(store, "stack.example.com", app_type="docker-compose")
    marked(unit_dirs, "stack-example-com")

    assert ServiceManager().app_units(app) == ["stack-example-com"]


def test_a_static_site_has_no_unit(store: WASMStore, unit_dirs: dict[str, Path]) -> None:
    """Even when a unit was left behind from the type it had before."""
    app = deploy(store, "static.example.com", app_type="static", is_static=False)
    marked(unit_dirs, "static-example-com")

    assert ServiceManager().app_units(app) == []


def test_an_app_unit_without_the_marker_is_managed_through_the_store(
    runner: FakeRunner, unit_dirs: dict[str, Path], store: WASMStore
) -> None:
    """inspect_unit and the listing apply one rule, the application signal included."""
    deploy(store, "plain.example.com")
    (unit_dirs["managed"] / "plain-example-com.service").write_text("[Service]\n")

    manager = ServiceManager()

    assert manager.inspect_unit("plain-example-com").managed
    assert [row["name"] for row in manager.list_services()] == ["plain-example-com"]


# ------------------------------------------------------------- all units


def test_all_units_lists_systemd_escaped_names_without_probing_them(
    runner: FakeRunner, unit_dirs: dict[str, Path], store: WASMStore, api: TestClient
) -> None:
    """Listing every unit used to fail as a whole on 'systemd-fsck@dev-disk-by\\x2dlabel-BOOT'."""
    marked(unit_dirs, "one-example-com")
    runner.script(
        [*LIST_UNITS, "*"],
        stdout=listing(
            f"{ESCAPED} loaded inactive dead",
            "getty@tty1 loaded active running",
            "ssh loaded active running",
            "one-example-com loaded active running",
        ),
    )

    response = api.get("/api/services", params={"wasm_only": "false"})

    assert response.status_code == 200, response.text
    rows = {row["name"]: row for row in response.json()["services"]}
    assert set(rows) == {ESCAPED, "getty@tty1", "ssh", "one-example-com"}
    assert rows[ESCAPED]["managed"] is False
    assert rows[ESCAPED]["status"] == "stopped"
    assert rows["ssh"]["active"] is True
    assert rows["ssh"]["managed"] is False
    assert rows["one-example-com"]["managed"] is True
    # One listing; foreign units are never asked about one by one.
    systemctl = runner.calls_to("systemctl")
    assert sum(call[1] == "list-units" for call in systemctl) == 1
    assert not any(ESCAPED + ".service" in call for call in systemctl if call[1] != "list-units")
    assert not any(call[1] in {"is-active", "is-enabled"} for call in systemctl)


def test_the_detail_of_an_escaped_foreign_unit_is_a_404_not_a_400(
    runner: FakeRunner, unit_dirs: dict[str, Path], store: WASMStore, api: TestClient
) -> None:
    """The console reads the 404 as "describe it from the all-units list"."""
    response = api.get(f"/api/services/{quote(ESCAPED, safe='')}")

    assert response.status_code == 404, response.text


def test_the_detail_of_an_app_unit_without_a_store_row_answers(
    runner: FakeRunner, unit_dirs: dict[str, Path], store: WASMStore, api: TestClient
) -> None:
    """It used to 404, and the console then showed WASM's own unit as a foreign one."""
    marked(unit_dirs, "qrboda-com")
    runner.script(["systemctl", "is-active", "qrboda-com.service"], stdout="active\n")

    response = api.get("/api/services/qrboda-com")

    assert response.status_code == 200, response.text
    assert response.json()["managed"] is True
    assert response.json()["active"] is True


def test_a_mutation_on_a_foreign_unit_is_still_refused(
    runner: FakeRunner, unit_dirs: dict[str, Path], store: WASMStore, api: TestClient
) -> None:
    """Accepting systemd's names for reading does not make them WASM's to act on."""
    response = api.post(f"/api/services/{quote(ESCAPED, safe='')}/restart")

    assert response.status_code in {400, 404}
    assert not any(call[1] == "restart" for call in runner.calls_to("systemctl"))


@pytest.mark.parametrize("name", [ESCAPED, "getty@tty1", "a:b", "x.service"])
def test_readable_unit_name_accepts_what_systemd_writes(name: str) -> None:
    """Escapes and instances are systemd's own spelling."""
    assert readable_unit_name(name) == name.removesuffix(".service")


@pytest.mark.parametrize("name", ["", "*", "a b", "../x", "-x", "a/b", "a\nb", "x" * 300])
def test_readable_unit_name_still_refuses_what_is_not_a_unit(name: str) -> None:
    """Nothing that could be a glob, a path or an option reaches argv."""
    from wasm.core.exceptions import ValidationError

    with pytest.raises(ValidationError):
        readable_unit_name(name)


# ------------------------------------------------------------ start limit


@pytest.mark.parametrize("verb", ["start", "restart"])
def test_a_deliberate_start_clears_the_start_limit_first(
    runner: FakeRunner, unit_dirs: dict[str, Path], store: WASMStore, verb: str
) -> None:
    """After a crash loop, the rollback's restart was refused as "repeated too quickly"."""
    marked(unit_dirs, "wasm-example")

    getattr(ServiceManager(), verb)("wasm-example")

    calls = runner.calls_to("systemctl")
    reset = calls.index(("systemctl", "reset-failed", "wasm-example.service"))
    started = calls.index(("systemctl", verb, "wasm-example.service"))
    assert reset < started


def test_reset_failed_is_never_sent_to_a_foreign_unit(
    runner: FakeRunner, unit_dirs: dict[str, Path], store: WASMStore
) -> None:
    """The guard runs first."""
    from wasm.core.exceptions import ServiceError

    (unit_dirs["distro"] / "ssh.service").write_text("[Service]\n")

    with pytest.raises(ServiceError):
        ServiceManager().restart("ssh")

    assert not any(call[1] == "reset-failed" for call in runner.calls_to("systemctl"))


# ---------------------------------------------------------------- log stream


class _Journal:
    """A journalctl that says what the test scripted, then ends."""

    def __init__(self, lines: list[bytes], error: bytes = b"", code: int = 0) -> None:
        self.returncode: int | None = None
        self._code = code
        self.stdout = asyncio.StreamReader()
        for line in lines:
            self.stdout.feed_data(line)
        if not lines:
            self.stdout.feed_eof()
        self.stderr = asyncio.StreamReader()
        if error:
            self.stderr.feed_data(error)
        self.stderr.feed_eof()

    def terminate(self) -> None:
        self.returncode = self._code

    def kill(self) -> None:
        self.returncode = -9

    async def wait(self) -> int:
        self.returncode = self._code
        return self._code


@pytest.fixture
def journal(monkeypatch: pytest.MonkeyPatch) -> dict[str, Any]:
    """
    Stand in for journalctl.

    Returns:
        ``calls`` (every argv spawned) and ``make`` (what the next spawn returns).
    """
    state: dict[str, Any] = {
        "calls": [],
        "make": lambda: _Journal([b"2026-09-26T10:00:00 host app[1]: hello\n"]),
    }

    async def fake_exec(*argv: str, **_kwargs: Any) -> _Journal:
        state["calls"].append(tuple(argv))
        return state["make"]()

    monkeypatch.setattr(asyncio, "create_subprocess_exec", fake_exec)
    monkeypatch.setattr("shutil.which", lambda name: f"/usr/bin/{name}")
    return state


def _open(sandbox: Path, path: str, frames: int) -> list[dict[str, Any]]:
    """
    Open a log socket and read some frames.

    Args:
        sandbox: The per-test sandbox.
        path: The socket path.
        frames: How many frames to read.

    Returns:
        The frames.
    """
    client = build_client(sandbox)
    token = get_token_manager().generate_master_token()
    with client.websocket_connect(path, subprotocols=token_subprotocols(token)) as ws:
        return [ws.receive_json() for _ in range(frames)]


def test_the_log_stream_follows_an_application_s_legacy_unit(
    sandbox: Path,
    runner: FakeRunner,
    unit_dirs: dict[str, Path],
    store: WASMStore,
    journal: dict[str, Any],
) -> None:
    """domain_to_app_name alone named a unit that does not exist and refused the stream."""
    deploy(store, "old.example.com")
    marked(unit_dirs, "wasm-old-example-com")

    connected, line = _open(sandbox, "/ws/logs/old.example.com", 2)

    assert connected["service"] == "wasm-old-example-com"
    assert line["type"] == "log"
    assert journal["calls"][0][:3] == ("journalctl", "-u", "wasm-old-example-com.service")


def test_the_log_stream_follows_every_workspace_of_a_monorepo(
    sandbox: Path,
    runner: FakeRunner,
    unit_dirs: dict[str, Path],
    store: WASMStore,
    journal: dict[str, Any],
) -> None:
    """All workspaces in one journalctl, interleaved by time."""
    app = deploy(store, "mono.example.com", app_type="monorepo")
    for workspace in ("api", "web"):
        store.create_service(Service(name=f"mono-example-com-{workspace}", app_id=app.id))
        marked(unit_dirs, f"mono-example-com-{workspace}")

    (connected,) = _open(sandbox, "/ws/logs/mono.example.com", 1)

    assert connected["services"] == ["mono-example-com-api", "mono-example-com-web"]
    argv = journal["calls"][0]
    assert argv[:5] == (
        "journalctl",
        "-u",
        "mono-example-com-api.service",
        "-u",
        "mono-example-com-web.service",
    )


def test_the_log_stream_of_a_workspace_unit_by_name(
    sandbox: Path,
    runner: FakeRunner,
    unit_dirs: dict[str, Path],
    store: WASMStore,
    journal: dict[str, Any],
) -> None:
    """The Services page streams one unit by its own name."""
    marked(unit_dirs, "mono-example-com-api")

    (connected,) = _open(sandbox, "/ws/logs/mono-example-com-api", 1)

    assert connected["service"] == "mono-example-com-api"


def test_a_static_site_has_no_process_to_stream(
    sandbox: Path,
    runner: FakeRunner,
    unit_dirs: dict[str, Path],
    store: WASMStore,
    journal: dict[str, Any],
) -> None:
    """Nothing is spawned, and the reason is said."""
    deploy(store, "static.example.com", app_type="static", is_static=True)

    (frame,) = _open(sandbox, "/ws/logs/static.example.com", 1)

    assert frame["type"] == "error"
    assert "static site" in frame["message"]
    assert journal["calls"] == []


def test_journalctl_s_own_error_reaches_the_client(
    sandbox: Path,
    runner: FakeRunner,
    unit_dirs: dict[str, Path],
    store: WASMStore,
    journal: dict[str, Any],
) -> None:
    """The console showed "The journal stream failed" with journalctl's reason thrown away."""
    marked(unit_dirs, "one-example-com")
    journal["make"] = lambda: _Journal(
        [], error=b"Failed to open journal: Permission denied\n", code=1
    )

    frames = _open(sandbox, "/ws/logs/one-example-com", 3)

    error = next(frame for frame in frames if frame["type"] == "error")
    assert "Permission denied" in error["message"]
    assert "status 1" in error["message"]
