# Copyright (c) 2024-2026 Yago Lopez Prado
# Licensed under WASM-NCSAL 1.0 (Commercial use prohibited)
# https://github.com/Perkybeet/wasm/blob/main/LICENSE

"""
Tests for migrating an in-place application onto the release layout.

Every test runs on a real temporary tree: the moves, links and counts are
real, and what ends up where is read back from disk. Git, systemd, the web
server and the HTTP probe are faked through the seams the code uses.

Review Focus pinned here: an application whose tree holds uploads git does not
track keeps every one of them, in ``shared/``, served through the release; no
file is lost (every file's bytes are found at its new place); a migration that
does not come up leaves the tree exactly as it was; ``--dry-run`` changes
nothing.
"""

from __future__ import annotations

import hashlib
import os
import stat
from collections.abc import Iterator
from pathlib import Path
from typing import Any

import pytest

from wasm.core.exceptions import DeploymentError, ServiceError, ValidationError, WASMError
from wasm.core.fs import DryRunFileSystem, RealFileSystem, set_fs
from wasm.core.runner import FakeRunner
from wasm.core.store import App, Service, Site, WASMStore
from wasm.core.utils import domain_to_app_name
from wasm.deployers import lifecycle
from wasm.deployers import migrate as migrate_module
from wasm.deployers.migrate import count_tree, migrate, plan_migration, relocate

DOMAIN = "shop.example.com"
PORT = 3100
COMMIT = "0123456789abcdef0123456789abcdef01234567"
GIT_URL = "https://github.com/example/shop.git"


class FakeUnits:
    """Stands in for ServiceManager: unit bodies in memory, restarts recorded."""

    def __init__(self, root: Path) -> None:
        self.root = root
        self.bodies: dict[str, str] = {}
        self.restarts: list[str] = []
        self.stops: list[bool] = []

    def stop(self, name: str) -> bool:
        # Whether the live tree was still in place when the unit stopped.
        self.stops.append((self.root / "server.js").is_file())
        return True

    def app_units(self, app: App) -> list[str]:
        return [] if app.is_static else [domain_to_app_name(app.domain)]

    def get_service_config(self, name: str) -> str | None:
        return self.bodies.get(name)

    def update_config(self, name: str, content: str) -> str:
        previous = self.bodies[name]
        self.bodies[name] = content
        return previous

    def restart(self, name: str) -> None:
        link = self.root / "current"
        self.restarts.append(os.readlink(link) if link.is_symlink() else "in place")

    def logs(self, name: str, lines: int = 50) -> str:
        return "Error: Cannot find module 'server.js'"


class FakeSites:
    """Stands in for the web server manager: site configurations in memory."""

    def __init__(self) -> None:
        self.configs: dict[str, str] = {}
        self.reloads = 0

    def get_site_config(self, domain: str) -> str | None:
        return self.configs.get(domain)

    def replace_site_config(self, domain: str, text: str) -> Path:
        self.configs[domain] = text
        return Path("/etc/nginx/sites-available") / domain

    def reload(self) -> bool:
        self.reloads += 1
        return True


def unit_body(root: Path) -> str:
    """A unit as WASM writes one for an in-place Node application."""
    return (
        "# Generated by WASM\n[Service]\n"
        f"WorkingDirectory={root}\n"
        "ExecStart=/usr/bin/npm run start\n"
        'Environment="PORT=3100"\n'
    )


@pytest.fixture
def root(tmp_path: Path) -> Path:
    """An in-place Node application with uploads git does not track."""
    root = tmp_path / "apps" / "shop-example-com"
    files = {
        "package.json": '{"name": "shop"}',
        "server.js": "require('http').createServer().listen(3100)",
        "public/logo.png": "png bytes",
        ".git/HEAD": "ref: refs/heads/main\n",
        "node_modules/dep/index.js": "module.exports = 1",
        "uploads/photo.jpg": "user photo",
        "uploads/2026/doc.pdf": "user document",
        ".env.local": "LOCAL=1\n",
        "notes.txt": "an untracked note",
        ".wasm/env-config.json": "{}",
    }
    for relative, content in files.items():
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
    (root / ".env").write_text("SECRET=1\n")
    (root / ".env").chmod(0o600)
    (root / "node_modules" / ".bin").mkdir()
    (root / "node_modules" / ".bin" / "dep").symlink_to(Path("../dep/index.js"))
    return root


@pytest.fixture
def store(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Iterator[WASMStore]:
    """A store in the test directory, where both modules look."""
    WASMStore.reset_instance()
    instance = WASMStore(tmp_path / "wasm.db")
    monkeypatch.setattr(migrate_module, "get_store", lambda: instance)
    monkeypatch.setattr(lifecycle, "get_store", lambda: instance)
    yield instance
    WASMStore.reset_instance()


@pytest.fixture
def machine(
    root: Path, store: WASMStore, runner: FakeRunner, monkeypatch: pytest.MonkeyPatch
) -> Any:
    """
    The application registered and running in place, with its machine faked.

    The probe answers when ``current`` has a server.js, which a correct
    migration gives it and a broken one does not.
    """
    app = store.create_app(
        App(
            domain=DOMAIN,
            app_type="nodejs",
            source=GIT_URL,
            branch="main",
            port=PORT,
            app_path=str(root),
        )
    )
    store.create_service(
        Service(
            app_id=app.id,
            name="shop-example-com",
            command="/usr/bin/npm run start",
            working_directory=str(root),
        )
    )
    store.create_site(Site(app_id=app.id, domain=DOMAIN, proxy_port=PORT))
    units = FakeUnits(root)
    units.bodies["shop-example-com"] = unit_body(root)
    sites = FakeSites()
    sites.configs[DOMAIN] = (
        f"server {{ server_name {DOMAIN}; proxy_pass http://127.0.0.1:{PORT}; }}"
    )
    probes: list[str] = []

    def probe(url: str, **kwargs: Any) -> bool:
        probes.append(url)
        answers = (root / "current" / "server.js").is_file()
        if not answers:
            kwargs["on_attempt"]("Health check attempt 1 failed: [Errno 111] Connection refused")
        return answers

    monkeypatch.setattr(migrate_module, "ServiceManager", lambda **kw: units)
    monkeypatch.setattr(lifecycle, "ServiceManager", lambda **kw: units)
    monkeypatch.setattr(migrate_module, "_webserver_for", lambda app: sites)
    monkeypatch.setattr(lifecycle, "wait_until_healthy", probe)

    prefix = ["git", "-c", f"safe.directory={root}", "--no-optional-locks"]
    runner.script([*prefix, "rev-parse"], stdout=f"{COMMIT}\n")
    runner.script(
        [*prefix, "status"],
        stdout="\0".join(
            [
                "?? uploads/",
                "!! node_modules/",
                "!! .env",
                "?? .env.local",
                "?? notes.txt",
                "?? .wasm/",
                "",
            ]
        ),
    )
    return type(
        "Machine",
        (),
        {"units": units, "sites": sites, "probes": probes, "runner": runner, "app": app},
    )


def snapshot(root: Path) -> dict[str, tuple[Any, ...]]:
    """
    Describe a tree exactly: every entry, its type, mode, link target and content hash.

    Returns:
        Relative path to description.
    """
    described: dict[str, tuple[Any, ...]] = {}
    for directory, subdirectories, names in os.walk(root):
        for name in [*subdirectories, *names]:
            path = Path(directory) / name
            info = os.lstat(path)
            relative = str(path.relative_to(root))
            if stat.S_ISLNK(info.st_mode):
                described[relative] = ("link", os.readlink(path))
            elif stat.S_ISDIR(info.st_mode):
                described[relative] = ("dir", stat.S_IMODE(info.st_mode))
            else:
                digest = hashlib.sha256(path.read_bytes()).hexdigest()
                described[relative] = ("file", stat.S_IMODE(info.st_mode), digest)
    return described


def files_by_content(root: Path) -> dict[str, str]:
    """Relative path to content hash, regular files only."""
    return {path: entry[2] for path, entry in snapshot(root).items() if entry[0] == "file"}


# ---------------------------------------------------------------------------
# Planning
# ---------------------------------------------------------------------------


def test_the_plan_keeps_what_git_does_not_track_and_changes_nothing(
    root: Path, machine: Any
) -> None:
    """Uploads are gitignored or untracked; both count. Build output never does."""
    before = snapshot(root)

    plan = plan_migration(DOMAIN)

    assert plan.persistent == (".env.local", "uploads")
    assert plan.persistent_source == "git"
    assert plan.env_files == (".env", ".wasm")
    assert plan.untracked_files == ("notes.txt",)
    assert any("notes.txt" in warning for warning in plan.warnings)
    assert plan.commit == COMMIT
    assert plan.release_id.endswith(f"-{COMMIT[:7]}")
    assert plan.unit == "shop-example-com"
    assert (plan.unit_rewrite, plan.site_rewrite) == (True, False)
    assert plan.count == count_tree(root)
    assert snapshot(root) == before


def test_named_paths_replace_what_git_would_have_chosen(root: Path, machine: Any) -> None:
    """--persist is the operator's word, validated but not second-guessed."""
    plan = plan_migration(DOMAIN, ["uploads/", "./public"])

    assert plan.persistent == ("uploads", "public")
    assert plan.persistent_source == "explicit"


@pytest.mark.parametrize(
    ("persist", "match"),
    [
        (["../elsewhere"], "not a path inside"),
        (["/etc"], "not a path inside"),
        (["public", "public/uploads"], "inside public"),
        ([".env"], "does not need --persist"),
    ],
)
def test_named_paths_that_could_escape_or_overlap_are_refused(
    machine: Any, persist: list[str], match: str
) -> None:
    """A path outside the application, or one inside another, is refused before anything."""
    with pytest.raises(ValidationError, match=match):
        plan_migration(DOMAIN, persist)


def test_a_tree_that_is_not_a_checkout_keeps_the_usual_upload_directories(
    root: Path, machine: Any
) -> None:
    """Without git nothing can be told apart; only what exists of the usual names, and a warning."""
    import shutil

    shutil.rmtree(root / ".git")
    (root / "storage").mkdir()

    plan = plan_migration(DOMAIN)

    assert plan.persistent == ("uploads", "storage")
    assert plan.persistent_source == "common"
    assert plan.commit is None
    assert plan.release_id.endswith("-nogit")
    assert any("--persist" in warning for warning in plan.warnings)


def test_only_in_place_applications_of_a_release_type_can_be_migrated(
    store: WASMStore, machine: Any
) -> None:
    """On releases already, or a type with no release pipeline, is refused."""
    app = store.get_app(DOMAIN)
    assert app is not None
    app.layout = "releases"
    store.update_app(app)
    with pytest.raises(DeploymentError, match="release layout already"):
        plan_migration(DOMAIN)

    app.layout, app.app_type = "inplace", "monorepo"
    store.update_app(app)
    with pytest.raises(DeploymentError, match="cannot use the release layout"):
        plan_migration(DOMAIN)

    with pytest.raises(WASMError, match="not found"):
        plan_migration("other.example.com")


# ---------------------------------------------------------------------------
# Migrating
# ---------------------------------------------------------------------------


def test_the_live_tree_becomes_the_first_release_and_uploads_move_to_shared(
    root: Path, store: WASMStore, machine: Any
) -> None:
    """Review Focus: every upload in shared/, served through the release; not a byte lost."""
    before_files = files_by_content(root)
    plan = plan_migration(DOMAIN)

    result = migrate(DOMAIN, plan, trigger="panel")

    release = root / "releases" / result.release_id
    assert os.readlink(root / "current") == f"releases/{result.release_id}"
    assert result.release_id.endswith(f"-{COMMIT[:7]}")
    assert sorted(os.listdir(root)) == ["current", "releases", "shared"]

    # Every file of the in-place tree is somewhere, byte for byte.
    after_files = files_by_content(root)
    for old, digest in before_files.items():
        top = old.split("/")[0]
        if top in plan.persistent or top in plan.env_files:
            new = f"shared/{old}"
        else:
            new = f"releases/{result.release_id}/{old}"
        assert after_files.get(new) == digest, f"{old} is not at {new}"
    assert len(after_files) == len(before_files)
    assert (result.before.files, result.before.bytes) == (result.after.files, result.after.bytes)

    # Served through the release, through relative links.
    assert os.readlink(release / "uploads") == "../../shared/uploads"
    assert os.readlink(release / ".env") == "../../shared/.env"
    assert os.readlink(release / ".env.local") == "../../shared/.env.local"
    assert (root / "current" / "uploads" / "2026" / "doc.pdf").read_text() == "user document"
    assert stat.S_IMODE((root / "shared" / ".env").stat().st_mode) == 0o600
    # A link the application had is still the same link.
    assert os.readlink(release / "node_modules" / ".bin" / "dep") == "../dep/index.js"

    # The unit runs from current; the proxied site did not need rewriting.
    assert f"WorkingDirectory={root}/current\n" in machine.units.bodies["shop-example-com"]
    assert machine.units.restarts == [f"releases/{result.release_id}"]
    assert (result.unit_rewritten, result.site_rewritten) == (True, False)
    service = store.get_service("shop-example-com")
    assert service is not None and service.working_directory == str(root / "current")

    app = store.get_app(DOMAIN)
    assert app is not None and app.layout == "releases"
    assert app.persistent_paths == [".env.local", "uploads"]
    assert [(r.id, r.status) for r in store.list_releases(app.id)] == [
        (result.release_id, "active")
    ]
    history = store.list_deployments(DOMAIN)[0]
    assert (history.status, history.triggered_by) == ("success", "panel")

    # New directories are the service's; the application directory is root's again.
    calls = machine.runner.calls
    assert ("chown", "www-data:www-data", str(release)) in calls
    assert ("chown", "www-data:www-data", str(root / "shared")) in calls
    assert ("chown", "root:root", str(root)) in calls


def test_a_migration_that_does_not_come_up_is_undone_exactly(
    root: Path, store: WASMStore, machine: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Every rename reversed, the unit put back byte for byte, restarted in place."""
    before = snapshot(root)
    unit_before = machine.units.bodies["shop-example-com"]
    plan = plan_migration(DOMAIN)
    monkeypatch.setattr(lifecycle, "wait_until_healthy", lambda url, **kw: False)

    with pytest.raises(DeploymentError, match="in-place layout was put back") as failure:
        migrate(DOMAIN, plan)

    assert snapshot(root) == before
    assert machine.units.bodies["shop-example-com"] == unit_before
    assert machine.units.restarts[-1] == "in place"
    assert "Error: Cannot find module" in failure.value.details
    assert "Not put back" not in failure.value.details
    app = store.get_app(DOMAIN)
    assert app is not None and app.layout == "inplace" and app.persistent_paths == []
    assert store.list_releases(app.id) == []
    service = store.get_service("shop-example-com")
    assert service is not None and service.working_directory == str(root)
    assert store.list_deployments(DOMAIN)[0].status == "failed"


def test_a_step_that_fails_halfway_is_undone_exactly(
    root: Path, store: WASMStore, machine: Any
) -> None:
    """The tenth rename fails; the nine before it are reversed."""
    before = snapshot(root)
    plan = plan_migration(DOMAIN)

    class FailingMoves(RealFileSystem):
        moves = 0

        def move(self, source: Path, destination: Path) -> None:
            FailingMoves.moves += 1
            if FailingMoves.moves == 10:
                raise OSError("No space left on device")
            super().move(source, destination)

    set_fs(FailingMoves())
    with pytest.raises(DeploymentError, match="No space left") as failure:
        migrate(DOMAIN, plan)
    set_fs(None)

    assert snapshot(root) == before
    assert machine.units.restarts == ["in place"]
    assert "Everything was put back" in failure.value.details
    assert isinstance(failure.value.__cause__, OSError)


def test_a_rehearsed_migration_changes_nothing(root: Path, store: WASMStore, machine: Any) -> None:
    """--dry-run: the tree, the unit, the site and the store are as they were."""
    before = snapshot(root)
    plan = plan_migration(DOMAIN)
    rehearsal = DryRunFileSystem()
    set_fs(rehearsal)

    result = migrate(DOMAIN, plan)
    set_fs(None)

    assert result.rehearsed
    assert snapshot(root) == before
    assert machine.units.bodies["shop-example-com"] == unit_body(root)
    assert machine.units.restarts == []
    assert any("uploads" in line for line in rehearsal.skipped)
    app = store.get_app(DOMAIN)
    assert app is not None and app.layout == "inplace"
    assert store.list_deployments(DOMAIN) == []


def test_names_the_layout_uses_do_not_collide_with_the_application_own(
    root: Path, store: WASMStore, machine: Any
) -> None:
    """An application may have its own shared/ or releases/ directory; it moves like the rest."""
    (root / "shared").mkdir()
    (root / "shared" / "lib.js").write_text("tracked shared code")
    (root / "releases").mkdir()
    (root / "releases" / "notes.md").write_text("tracked release notes")

    result = migrate(DOMAIN, plan_migration(DOMAIN))

    release = root / "releases" / result.release_id
    assert (release / "shared" / "lib.js").read_text() == "tracked shared code"
    assert (release / "releases" / "notes.md").read_text() == "tracked release notes"


def test_a_static_site_is_served_from_current(root: Path, store: WASMStore, machine: Any) -> None:
    """A site that names the directory is rewritten, reloaded and checked on disk."""
    (root / "dist").mkdir()
    (root / "dist" / "index.html").write_text("<h1>shop</h1>")
    app = store.get_app(DOMAIN)
    assert app is not None
    app.is_static = True
    store.update_app(app)
    site = store.get_site(DOMAIN)
    assert site is not None
    site.document_root = str(root / "dist")
    store.update_site(site)
    machine.sites.configs[DOMAIN] = f"server {{ root {root}/dist; }}"

    plan = plan_migration(DOMAIN)
    result = migrate(DOMAIN, plan)

    assert plan.unit is None and plan.site_rewrite
    assert result.site_rewritten
    assert machine.sites.configs[DOMAIN] == f"server {{ root {root}/current/dist; }}"
    assert machine.sites.reloads == 1
    stored = store.get_site(DOMAIN)
    assert stored is not None and stored.document_root == str(root / "current" / "dist")


def test_a_plan_for_another_directory_is_refused(root: Path, machine: Any) -> None:
    """A stale plan is not executed against a tree it did not describe."""
    from dataclasses import replace

    plan = replace(plan_migration(DOMAIN), app_path="/var/www/apps/elsewhere")

    with pytest.raises(DeploymentError, match="Plan again"):
        migrate(DOMAIN, plan)


# ---------------------------------------------------------------------------
# Rewriting units and sites
# ---------------------------------------------------------------------------


def test_relocation_points_at_current_and_starts_venv_scripts_through_python() -> None:
    """A venv script names its interpreter by the path that moved; python -m does not."""
    root = Path("/var/www/apps/shop")
    unit = (
        f"WorkingDirectory={root}\n"
        f"ExecStart={root}/venv/bin/gunicorn app:app -w 4\n"
        f'Environment="PYTHONPATH={root}"\n'
        'Environment="OTHER=/var/www/apps/shop-2/x"\n'
    )

    assert relocate(unit, root) == (
        f"WorkingDirectory={root}/current\n"
        f"ExecStart={root}/current/venv/bin/python -m gunicorn app:app -w 4\n"
        f'Environment="PYTHONPATH={root}/current"\n'
        'Environment="OTHER=/var/www/apps/shop-2/x"\n'
    )


def test_a_file_lost_on_the_way_fails_the_migration(
    root: Path, store: WASMStore, machine: Any
) -> None:
    """The count is the proof: one file fewer, anywhere, and the migration is undone."""
    plan = plan_migration(DOMAIN)

    class LosingMoves(RealFileSystem):
        def move(self, source: Path, destination: Path) -> None:
            super().move(source, destination)
            if destination.name == "uploads" and destination.parent.name == "shared":
                (destination / "photo.jpg").unlink()

    set_fs(LosingMoves())
    with pytest.raises(DeploymentError, match="before the migration") as failure:
        migrate(DOMAIN, plan)
    set_fs(None)

    assert "Not put back" in failure.value.details, "the loss is reported, not hidden"
    assert not os.path.lexists(root / "current")
    assert (root / "uploads" / "2026" / "doc.pdf").read_text() == "user document"
    assert machine.units.restarts == ["in place"]
    app = store.get_app(DOMAIN)
    assert app is not None and app.layout == "inplace"


# ---------------------------------------------------------------------------
# The unit is stopped while its tree moves
# ---------------------------------------------------------------------------


def test_the_unit_is_stopped_before_anything_moves(
    root: Path, store: WASMStore, machine: Any
) -> None:
    """A running Next.js recreates .next under a moving tree; the undo then cannot put it back."""
    plan = plan_migration(DOMAIN)

    migrate(DOMAIN, plan)

    assert machine.units.stops == [True], "stopped once, with the tree still in place"
    assert machine.units.restarts == [f"releases/{plan_release(root)}"]


def plan_release(root: Path) -> str:
    """The release current points at."""
    return Path(os.readlink(root / "current")).name


def test_the_plan_states_the_downtime(root: Path, machine: Any) -> None:
    plan = plan_migration(DOMAIN)

    assert any(
        "shop-example-com is stopped" in warning and "down" in warning for warning in plan.warnings
    )


def test_a_unit_that_would_not_stop_moves_nothing(
    root: Path, store: WASMStore, machine: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    before = snapshot(root)
    plan = plan_migration(DOMAIN)

    def refuse(name: str) -> bool:
        raise ServiceError(f"Failed to stop {name}", details="Job for it canceled")

    monkeypatch.setattr(machine.units, "stop", refuse)
    with pytest.raises(ServiceError, match="Failed to stop"):
        migrate(DOMAIN, plan)

    assert snapshot(root) == before
    assert machine.units.restarts == ["in place"]


def test_a_failure_after_the_build_moved_is_undone_and_says_what_stayed(
    root: Path, store: WASMStore, machine: Any
) -> None:
    """
    The build output moved, the next rename fails, and one reversal fails too.

    Every other change is still reversed, and the one error raised says what
    could not be put back and where it is now.
    """
    (root / ".next" / "server").mkdir(parents=True)
    (root / ".next" / "BUILD_ID").write_text("build-1")
    plan = plan_migration(DOMAIN)

    class Failing(RealFileSystem):
        def move(self, source: Path, destination: Path) -> None:
            if source == root / ".wasm":
                assert (destination.parent / ".next" / "BUILD_ID").is_file(), "after .next"
                raise OSError("No space left on device")
            if destination == root / ".git":
                raise OSError("Permission denied")
            super().move(source, destination)

    set_fs(Failing())
    with pytest.raises(DeploymentError, match="No space left") as failure:
        migrate(DOMAIN, plan)
    set_fs(None)

    staging = next(root.glob(".wasm-migrating-*"))
    details = failure.value.details
    assert "Not put back" in details
    assert f"{root / '.git'} is still at {staging / '.git'}" in details
    assert "Permission denied" in details
    # Everything else was reversed, the build output included.
    assert (root / ".next" / "BUILD_ID").read_text() == "build-1"
    assert (root / "node_modules" / "dep" / "index.js").is_file()
    assert (root / ".env").read_text() == "SECRET=1\n"
    assert (root / "server.js").is_file()
    assert (staging / ".git" / "HEAD").is_file()
    assert machine.units.restarts == ["in place"]
    app = store.get_app(DOMAIN)
    assert app is not None and app.layout == "inplace"


def test_every_reversal_runs_even_when_one_raises_something_unexpected(
    root: Path, store: WASMStore, machine: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A reversal that fails in a way nobody planned for does not stop the others."""
    before = snapshot(root)
    plan = plan_migration(DOMAIN)
    monkeypatch.setattr(lifecycle, "wait_until_healthy", lambda url, **kw: False)

    def broken_undo(name: str, content: str) -> str:
        if "current" not in content:
            raise RuntimeError("systemd went away")
        return FakeUnits.update_config(machine.units, name, content)

    monkeypatch.setattr(machine.units, "update_config", broken_undo)
    with pytest.raises(DeploymentError, match="did not pass its health check") as failure:
        migrate(DOMAIN, plan)

    assert "systemd went away" in failure.value.details
    assert snapshot(root) == before, "the tree was put back all the same"


# ---------------------------------------------------------------------------
# SQLite databases in the tree
# ---------------------------------------------------------------------------

SQLITE_HEADER = b"SQLite format 3\x00" + b"\x00" * 84


def with_database(root: Path, machine: Any, relative: str = "db.sqlite3") -> None:
    """Give the application a SQLite database in WAL mode, which git does not track."""
    database = root / relative
    database.parent.mkdir(parents=True, exist_ok=True)
    database.write_bytes(SQLITE_HEADER + b"rows")
    (root / f"{relative}-wal").write_bytes(b"committed but not checkpointed")
    (root / f"{relative}-shm").write_bytes(b"index")
    prefix = ["git", "-c", f"safe.directory={root}", "--no-optional-locks"]
    machine.runner.script(
        [*prefix, "status"],
        stdout="\0".join(
            [
                "?? uploads/",
                "!! node_modules/",
                "!! .env",
                "?? .env.local",
                "?? notes.txt",
                "?? .wasm/",
                f"!! {relative}",
                f"!! {relative}-wal",
                f"!! {relative}-shm",
                "",
            ]
        ),
    )


def test_a_sqlite_database_is_shared_and_its_wal_moves_with_it(
    root: Path, store: WASMStore, machine: Any
) -> None:
    """Left in the first release, the next deploy would start from an empty database."""
    with_database(root, machine)

    plan = plan_migration(DOMAIN)

    assert "db.sqlite3" in plan.persistent
    assert plan.companions == ("db.sqlite3-shm", "db.sqlite3-wal")
    assert not any("db.sqlite3" in f for f in plan.untracked_files)
    assert any("SQLite" in warning and "db.sqlite3" in warning for warning in plan.warnings)

    migrate(DOMAIN, plan)

    shared = root / "shared"
    assert (shared / "db.sqlite3").read_bytes().startswith(b"SQLite format 3")
    assert (shared / "db.sqlite3-wal").read_bytes() == b"committed but not checkpointed"
    assert (shared / "db.sqlite3-shm").is_file()
    release = root / "current"
    assert os.readlink(release / "db.sqlite3") == "../../shared/db.sqlite3"
    # SQLite resolves the link and keeps its -wal and -shm beside the real file.
    assert not os.path.lexists(release / "db.sqlite3-wal")
    assert "db.sqlite3" in store.get_app(DOMAIN).persistent_paths
    assert "db.sqlite3-wal" not in store.get_app(DOMAIN).persistent_paths


def test_a_database_inside_a_shared_directory_needs_nothing_more(
    root: Path, store: WASMStore, machine: Any
) -> None:
    with_database(root, machine, "uploads/cache.db")

    plan = plan_migration(DOMAIN)

    assert plan.persistent == (".env.local", "uploads")
    assert plan.companions == ()


def test_a_database_outside_the_named_paths_is_refused(root: Path, machine: Any) -> None:
    """--persist is the operator's list; one that forgets the database is not guessed at."""
    with_database(root, machine, "var/app.db")

    with pytest.raises(DeploymentError, match=r"var/app\.db") as refused:
        plan_migration(DOMAIN, ["uploads"])

    assert "--persist var" in refused.value.details


def test_a_database_git_tracks_is_warned_about(root: Path, machine: Any) -> None:
    """The next deploy's copy from the repository would win over the one in shared/."""
    (root / "seed.db").write_bytes(SQLITE_HEADER)

    plan = plan_migration(DOMAIN)

    assert "seed.db" in plan.persistent
    assert any("seed.db" in warning and "tracked" in warning for warning in plan.warnings)


def test_build_output_and_non_databases_are_not_mistaken_for_databases(
    root: Path, machine: Any
) -> None:
    (root / "node_modules" / "dep" / "fixtures.db").write_bytes(SQLITE_HEADER)
    (root / "public" / "fonts.db").write_text("not a database")

    plan = plan_migration(DOMAIN)

    assert plan.persistent == (".env.local", "uploads")
    assert plan.companions == ()


def test_a_migration_is_refused_while_another_operation_runs(
    root: Path, store: WASMStore, machine: Any
) -> None:
    """An update building in the tree, or a restore replacing it, must not see it move."""
    from tests.test_applock import Holder
    from wasm.core.applock import AppBusyError

    before = snapshot(root)
    plan = plan_migration(DOMAIN)

    with Holder(DOMAIN, "update"), pytest.raises(AppBusyError, match="update started at"):
        migrate(DOMAIN, plan)

    assert snapshot(root) == before
    assert machine.units.stops == []
    assert store.list_deployments(DOMAIN) == []
