# Copyright (c) 2024-2026 Yago Lopez Prado
# SPDX-License-Identifier: AGPL-3.0-or-later

"""
Tests for the ``wasm cron`` command group.

The commands are a thin shell around
:class:`~wasm.managers.cron_manager.CronManager`, which is exercised for real
here (through the escaped systemd templates, a sandboxed unit directory and
the :class:`~wasm.core.runner.FakeRunner`) rather than mocked out, so a
divergence between the CLI and the manager's own validation - the same
validation :mod:`wasm.web.api.cron` relies on - would show up as a failing
test rather than shipping.
"""

from __future__ import annotations

import json
from collections.abc import Iterator
from pathlib import Path

import click
import pytest
from click.testing import CliRunner

from wasm.cli.app import cli as root_cli
from wasm.cli.commands import cron as cron_cli
from wasm.core.config import Config
from wasm.core.runner import FakeRunner
from wasm.core.store import WASMStore
from wasm.managers.cron_manager import CronManager

#: What ``systemctl list-unit-files`` prints for one enabled WASM cron timer.
LIST_UNIT_FILES_LINE = "wasm-cron-cleanup.timer enabled enabled\n"

#: What ``systemctl show`` answers about that timer.
SHOW_TIMER_OUTPUT = (
    "TimersCalendar={ OnCalendar=*-*-* 02:00:00 ; next_elapse=Sat 2026-08-15 02:00:00 UTC }\n"
    "LastTriggerUSec=Fri 2026-08-14 02:00:00 UTC\n"
    "NextElapseUSecRealtime=Sat 2026-08-15 02:00:00 UTC\n"
)

#: Journal JSON for one successful run, in systemd's own shape.
JOURNAL_OUTPUT = "\n".join(
    [
        '{"__REALTIME_TIMESTAMP": "1700000000000000", "MESSAGE": "cleaning caches",'
        ' "_SYSTEMD_INVOCATION_ID": "aaa"}',
        '{"__REALTIME_TIMESTAMP": "1700000002000000", "UNIT": "wasm-cron-cleanup.service",'
        ' "INVOCATION_ID": "aaa", "JOB_RESULT": "done", "JOB_TYPE": "start"}',
    ]
)


@pytest.fixture
def systemd_dir(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """
    Point the manager's unit directory into the sandbox.

    Args:
        tmp_path: Per-test temporary directory.
        monkeypatch: Patching helper, scoped to the test.

    Returns:
        The directory unit files land in.
    """
    path = tmp_path / "systemd"
    path.mkdir()
    monkeypatch.setattr(CronManager, "SYSTEMD_DIR", path)
    return path


@pytest.fixture
def config_file(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Iterator[Path]:
    """
    Point the configuration singleton at the sandbox, never the real machine.

    Args:
        tmp_path: Per-test temporary directory.
        monkeypatch: Patching helper, scoped to the test.

    Yields:
        The path configuration is read from. It does not exist, so every key
        answers its default, including ``service_user``.
    """
    path = tmp_path / "etc" / "wasm" / "config.yaml"
    monkeypatch.setattr("wasm.core.config.DEFAULT_CONFIG_PATH", path)
    Config.reset_instance()
    try:
        yield path
    finally:
        Config.reset_instance()


@pytest.fixture
def cli_runner() -> CliRunner:
    """Return a Click test runner."""
    return CliRunner()


@pytest.fixture
def store(tmp_path: Path) -> Iterator[WASMStore]:
    """
    Give the manager a store of its own, sandboxed away from the real machine.

    ``USER_DB_PATH`` is computed once, at import time, from ``Path.home()``,
    so patching ``HOME`` after the fact does not redirect it: a test that
    associates a job with ``--app`` and does not sandbox the store reads and
    is answered by whatever this developer's own ``~/.local/share/wasm/wasm.db``
    happens to hold.

    Args:
        tmp_path: Per-test temporary directory.

    Yields:
        The store the manager reads.
    """
    WASMStore.reset_instance()
    instance = WASMStore(tmp_path / "wasm.db")
    try:
        yield instance
    finally:
        instance.close()
        WASMStore.reset_instance()


def write_owned_pair(systemd_dir: Path, name: str = "cleanup") -> tuple[Path, Path]:
    """
    Write a unit pair the way the manager would, marker included.

    Args:
        systemd_dir: The patched unit directory.
        name: Job name.

    Returns:
        The timer and service paths.
    """
    timer = systemd_dir / f"wasm-cron-{name}.timer"
    service = systemd_dir / f"wasm-cron-{name}.service"
    timer.write_text("# Generated by WASM\n[Timer]\nOnCalendar=*-*-* 02:00:00\n")
    service.write_text(
        "# Generated by WASM\n[Service]\nUser=www-data\n"
        "WorkingDirectory=/srv/caches\nExecStart=/usr/bin/find /tmp/caches -delete\n"
    )
    return timer, service


# ---------------------------------------------------------------------------
# Command tree
# ---------------------------------------------------------------------------


def test_every_command_answers_help(cli_runner: CliRunner) -> None:
    """Every subcommand documents itself."""
    for name in ("list", "create", "delete", "run", "enable", "disable", "runs"):
        result = cli_runner.invoke(cron_cli.cli, [name, "--help"])
        assert result.exit_code == 0, result.output
        assert "Usage:" in result.output


def test_cron_is_registered_on_the_root_group(cli_runner: CliRunner) -> None:
    """``wasm cron`` resolves through the lazy group, not just the submodule."""
    result = cli_runner.invoke(root_cli, ["cron", "--help"])

    assert result.exit_code == 0, result.output
    assert "create" in result.output


def test_no_command_binds_a_global_flag(cli_runner: CliRunner) -> None:
    """
    No subcommand redeclares --verbose/--dry-run/--json/--no-color as its own.

    ``list`` and ``runs`` offer ``--json`` (via ``json_option``, with
    ``expose_value=False``), which can only ever switch the shared Context on
    and never binds - and so cannot overwrite - a value on the command
    function. None of the others re-expose a global flag at all, so simply
    not declaring one is what keeps 'wasm --dry-run cron delete <name>
    --force' from being overridden by a subparser default - the argparse-era
    bug this whole migration exists to remove.
    """
    global_flags = {"--verbose", "-v", "--dry-run", "--json", "--no-color"}
    for name in cron_cli.cli.list_commands(click.Context(cron_cli.cli)):
        command = cron_cli.cli.get_command(click.Context(cron_cli.cli), name)
        assert command is not None
        present = {
            opt
            for param in command.params
            if getattr(param, "expose_value", True)
            for opt in getattr(param, "opts", [])
        }
        assert not present & global_flags, f"cron {name} redeclares a global flag"


# ---------------------------------------------------------------------------
# list
# ---------------------------------------------------------------------------


def test_list_reports_no_jobs(cli_runner: CliRunner, runner: FakeRunner) -> None:
    """An empty machine is reported plainly, with a hint how to create one."""
    result = cli_runner.invoke(cron_cli.cli, ["list"])

    assert result.exit_code == 0, result.output
    assert "No cron jobs" in result.output
    assert "wasm cron create" in result.output


def test_list_reports_an_owned_job(
    cli_runner: CliRunner, runner: FakeRunner, systemd_dir: Path
) -> None:
    """A job's schedule alias, state and last result are shown."""
    write_owned_pair(systemd_dir)
    runner.script(["systemctl", "list-unit-files"], stdout=LIST_UNIT_FILES_LINE)
    runner.script(["systemctl", "show", "wasm-cron-cleanup.timer"], stdout=SHOW_TIMER_OUTPUT)
    runner.script(["systemctl", "show", "wasm-cron-cleanup.service"], stdout="")

    result = cli_runner.invoke(cron_cli.cli, ["list"])

    assert result.exit_code == 0, result.output
    assert "cleanup" in result.output
    assert "daily" in result.output
    assert "enabled" in result.output


def test_list_json_reports_the_same_shape_the_api_uses(
    cli_runner: CliRunner, runner: FakeRunner, systemd_dir: Path
) -> None:
    """
    'wasm cron list --json' carries the fields GET /api/cron's CronJobInfo
    does, since both are built from CronManager.list_jobs.
    """
    write_owned_pair(systemd_dir)
    runner.script(["systemctl", "list-unit-files"], stdout=LIST_UNIT_FILES_LINE)
    runner.script(["systemctl", "show", "wasm-cron-cleanup.timer"], stdout=SHOW_TIMER_OUTPUT)
    runner.script(["systemctl", "show", "wasm-cron-cleanup.service"], stdout="")

    result = cli_runner.invoke(cron_cli.cli, ["list", "--json"])

    assert result.exit_code == 0, result.output
    payload = json.loads(result.output)
    assert payload["total"] == 1
    job = payload["jobs"][0]
    assert job["name"] == "cleanup"
    assert job["schedule"] == "daily"
    assert job["enabled"] is True


def test_list_json_reports_an_empty_machine(cli_runner: CliRunner, runner: FakeRunner) -> None:
    """No jobs is {"jobs": [], "total": 0}, not the human hint text."""
    result = cli_runner.invoke(cron_cli.cli, ["list", "--json"])

    assert result.exit_code == 0, result.output
    assert json.loads(result.output) == {"jobs": [], "total": 0}


def test_list_shows_the_effective_working_directory(
    cli_runner: CliRunner, runner: FakeRunner, systemd_dir: Path
) -> None:
    """
    The directory column is read back from the unit's own WorkingDirectory=,
    so it shows current/ for a releases application rather than the app root
    a stale listing would otherwise imply.
    """
    write_owned_pair(systemd_dir)
    runner.script(["systemctl", "list-unit-files"], stdout=LIST_UNIT_FILES_LINE)
    runner.script(["systemctl", "show", "wasm-cron-cleanup.timer"], stdout=SHOW_TIMER_OUTPUT)
    runner.script(["systemctl", "show", "wasm-cron-cleanup.service"], stdout="")

    result = cli_runner.invoke(cron_cli.cli, ["list"])

    assert result.exit_code == 0, result.output
    assert "/srv/caches" in result.output


# ---------------------------------------------------------------------------
# create
# ---------------------------------------------------------------------------


def test_create_writes_the_unit_pair_and_enables_it(
    cli_runner: CliRunner, runner: FakeRunner, systemd_dir: Path, config_file: Path
) -> None:
    """A valid job is written through the manager and its timer enabled."""
    result = cli_runner.invoke(
        cron_cli.cli,
        ["create", "cleanup", "/usr/bin/find /tmp/caches -delete", "--schedule", "daily"],
    )

    assert result.exit_code == 0, result.output
    assert "Created cron job: cleanup" in result.output
    assert (systemd_dir / "wasm-cron-cleanup.timer").exists()
    assert (systemd_dir / "wasm-cron-cleanup.service").exists()
    assert ("systemctl", "enable", "--now", "wasm-cron-cleanup.timer") in runner.calls


def test_create_refuses_an_invalid_schedule(
    cli_runner: CliRunner, runner: FakeRunner, systemd_dir: Path, config_file: Path
) -> None:
    """
    The same calendar rule the panel enforces is enforced here.

    wasm.managers.backup_scheduler.validate_calendar is the single definition
    both wasm.web.api.cron and this command go through, so a value the panel
    would answer 422 for is refused here in the same words instead of being
    written into a root-owned unit file. A newline is what an operator could
    use to append a directive to the unit, which is exactly what the
    character allowlist exists to catch.
    """
    result = cli_runner.invoke(
        cron_cli.cli,
        ["create", "cleanup", "/usr/bin/true", "--schedule", "daily\nOnBootSec=1s"],
    )

    assert result.exit_code == 1
    assert "Invalid cron schedule" in result.output
    assert list(systemd_dir.iterdir()) == []


def test_create_refuses_an_unparseable_command(
    cli_runner: CliRunner, runner: FakeRunner, systemd_dir: Path, config_file: Path
) -> None:
    """A dangling quote is refused before anything is written."""
    result = cli_runner.invoke(cron_cli.cli, ["create", "cleanup", "/usr/bin/echo 'unterminated"])

    assert result.exit_code == 1
    assert "Cannot parse" in result.output
    assert list(systemd_dir.iterdir()) == []


def test_create_associates_an_unknown_application_is_refused(
    cli_runner: CliRunner,
    runner: FakeRunner,
    systemd_dir: Path,
    config_file: Path,
    store: WASMStore,
) -> None:
    """--app names a domain the store has never heard of."""
    result = cli_runner.invoke(
        cron_cli.cli,
        ["create", "cleanup", "/usr/bin/true", "--app", "example.com"],
    )

    assert result.exit_code == 1
    assert "example.com" in result.output


# ---------------------------------------------------------------------------
# delete
# ---------------------------------------------------------------------------


def test_delete_with_force_removes_the_unit_pair(
    cli_runner: CliRunner, runner: FakeRunner, systemd_dir: Path
) -> None:
    """--force skips the confirmation and removes both unit files."""
    timer, service = write_owned_pair(systemd_dir)

    result = cli_runner.invoke(cron_cli.cli, ["delete", "cleanup", "--force"])

    assert result.exit_code == 0, result.output
    assert "Deleted cron job: cleanup" in result.output
    assert not timer.exists()
    assert not service.exists()


def test_delete_without_force_asks_first(
    cli_runner: CliRunner, runner: FakeRunner, systemd_dir: Path
) -> None:
    """Declining the confirmation leaves the unit pair untouched."""
    timer, service = write_owned_pair(systemd_dir)

    result = cli_runner.invoke(cron_cli.cli, ["delete", "cleanup"], input="n\n")

    assert result.exit_code == 0, result.output
    assert "Cancelled" in result.output
    assert timer.exists()
    assert service.exists()


def test_delete_of_an_unknown_job_fails(cli_runner: CliRunner, runner: FakeRunner) -> None:
    """Deleting a job that was never created is an error, not a silent no-op."""
    result = cli_runner.invoke(cron_cli.cli, ["delete", "nosuch", "--force"])

    assert result.exit_code == 1
    assert "Unknown cron job" in result.output


# ---------------------------------------------------------------------------
# run, enable, disable
# ---------------------------------------------------------------------------


def test_run_starts_the_service_unit(
    cli_runner: CliRunner, runner: FakeRunner, systemd_dir: Path
) -> None:
    """``wasm cron run`` starts the service outside its schedule."""
    write_owned_pair(systemd_dir)

    result = cli_runner.invoke(cron_cli.cli, ["run", "cleanup"])

    assert result.exit_code == 0, result.output
    assert "Started wasm-cron-cleanup.service" in result.output
    assert ("systemctl", "start", "--no-block", "wasm-cron-cleanup.service") in runner.calls


def test_enable_and_disable_drive_the_timer(
    cli_runner: CliRunner, runner: FakeRunner, systemd_dir: Path
) -> None:
    """Enable and disable act on the timer unit and report which one."""
    write_owned_pair(systemd_dir)

    enabled = cli_runner.invoke(cron_cli.cli, ["enable", "cleanup"])
    disabled = cli_runner.invoke(cron_cli.cli, ["disable", "cleanup"])

    assert enabled.exit_code == 0, enabled.output
    assert "Enabled wasm-cron-cleanup.timer" in enabled.output
    assert ("systemctl", "enable", "--now", "wasm-cron-cleanup.timer") in runner.calls

    assert disabled.exit_code == 0, disabled.output
    assert "Disabled wasm-cron-cleanup.timer" in disabled.output
    assert ("systemctl", "disable", "--now", "wasm-cron-cleanup.timer") in runner.calls


def test_run_of_an_unowned_unit_is_refused(
    cli_runner: CliRunner, runner: FakeRunner, systemd_dir: Path
) -> None:
    """A unit without the WASM marker is never started, enabled or disabled."""
    (systemd_dir / "wasm-cron-cleanup.timer").write_text("[Timer]\nOnCalendar=daily\n")
    (systemd_dir / "wasm-cron-cleanup.service").write_text("[Service]\nExecStart=/bin/true\n")

    result = cli_runner.invoke(cron_cli.cli, ["run", "cleanup"])

    assert result.exit_code == 1
    assert "Refusing" in result.output
    assert not any(call[:2] == ("systemctl", "start") for call in runner.calls_to("systemctl"))


# ---------------------------------------------------------------------------
# runs
# ---------------------------------------------------------------------------


def test_runs_reconstructs_history_from_the_journal(
    cli_runner: CliRunner, runner: FakeRunner, systemd_dir: Path
) -> None:
    """Recent executions come from journalctl, with the job's own output."""
    write_owned_pair(systemd_dir)
    runner.script(["journalctl", "-u", "wasm-cron-cleanup.service"], stdout=JOURNAL_OUTPUT)

    result = cli_runner.invoke(cron_cli.cli, ["runs", "cleanup"])

    assert result.exit_code == 0, result.output
    assert "cleaning caches" in result.output


def test_runs_json_carries_the_same_fields_as_the_api(
    cli_runner: CliRunner, runner: FakeRunner, systemd_dir: Path
) -> None:
    """'wasm cron runs --json' matches GET /api/cron/{name}/runs's CronRunInfo."""
    write_owned_pair(systemd_dir)
    runner.script(["journalctl", "-u", "wasm-cron-cleanup.service"], stdout=JOURNAL_OUTPUT)

    result = cli_runner.invoke(cron_cli.cli, ["runs", "cleanup", "--json"])

    assert result.exit_code == 0, result.output
    payload = json.loads(result.output)
    assert payload["name"] == "cleanup"
    assert payload["total"] == 1
    run = payload["runs"][0]
    assert "cleaning caches" in run["output"]
    assert run["success"] is True


def test_runs_reports_no_history(
    cli_runner: CliRunner, runner: FakeRunner, systemd_dir: Path
) -> None:
    """A job that has never run says so instead of printing nothing."""
    write_owned_pair(systemd_dir)

    result = cli_runner.invoke(cron_cli.cli, ["runs", "cleanup"])

    assert result.exit_code == 0, result.output
    assert "No recorded runs" in result.output


def test_runs_of_an_unknown_job_fails(cli_runner: CliRunner, runner: FakeRunner) -> None:
    """Asking for the history of a job that does not exist is an error."""
    result = cli_runner.invoke(cron_cli.cli, ["runs", "nosuch"])

    assert result.exit_code == 1
    assert "Unknown cron job" in result.output
