# Copyright (c) 2024-2026 Yago Lopez Prado
# SPDX-License-Identifier: AGPL-3.0-or-later

"""
Tests for per-application memory, CPU and task limits.

- The unit a deploy writes carries ``MemoryMax=``, ``CPUQuota=`` and
  ``TasksMax=`` only for the limits that are set (a snapshot of the whole
  unit pins where and how).
- Setting limits on an existing unit edits it rather than rendering it again,
  and the edit produces exactly what rendering would: one spelling.
- The ranges are enforced in the service manager, whoever asks.
- :func:`wasm.deployers.lifecycle.set_resource_limits` rewrites every unit of
  the application, records the limits on its row and restarts only when asked;
  a redeploy keeps them.
"""

# The service manager fixtures are imported rather than replicated.
# ruff: noqa: F811

from __future__ import annotations

from pathlib import Path
from typing import Any

import pytest
from jinja2 import Environment, PackageLoader

from tests.test_service_manager import (  # noqa: F401  (pytest resolves fixtures by name)
    manager,
    store,
    unit_dirs,
)
from wasm.core.exceptions import DeploymentError, ServiceError, ValidationError
from wasm.core.store import App, Service, WASMStore
from wasm.deployers import lifecycle
from wasm.managers.service_manager import (
    ResourceLimits,
    ServiceManager,
    with_resource_limits,
)

LIMITS = ResourceLimits(memory_max_mb=512, cpu_quota_percent=50, tasks_max=256)

#: The unit a Node application on releases gets with LIMITS, in full.
SNAPSHOT = """\
# Systemd service for shop-example-com
# Generated by WASM

[Unit]
Description=WASM: shop.example.com (nodejs)
Documentation=https://github.com/Perkybeet/wasm
After=network.target
# A transient failure is retried; a hopeless one (a missing script, a missing
# binary) ends in `failed` after five starts in five minutes instead of looping
# every RestartSec forever. Deliberate starts clear the counter first.
StartLimitIntervalSec=300
StartLimitBurst=5

[Service]
Type=simple
User=www-data
Group=www-data
WorkingDirectory=/var/www/apps/shop-example-com/current

# Environment
Environment="PORT=3100"
Environment="NODE_ENV=production"

# Command
ExecStart=/usr/bin/npm run start

# Restart policy
Restart=always
RestartSec=10

# Security
NoNewPrivileges=true
PrivateTmp=true

# Logging
StandardOutput=journal
StandardError=journal
SyslogIdentifier=shop-example-com

# Resource limits
LimitNOFILE=65535
MemoryMax=512M
CPUQuota=50%
TasksMax=256

[Install]
WantedBy=multi-user.target"""


def render(limits: ResourceLimits | None) -> str:
    """Render the application unit template the way the service manager does."""
    return (
        Environment(  # noqa: S701 - unit files, escaped by their own macros
            loader=PackageLoader("wasm", "templates/systemd"), trim_blocks=True, lstrip_blocks=True
        )
        .get_template("app.service.j2")
        .render(
            name="shop-example-com",
            description="WASM: shop.example.com (nodejs)",
            command="/usr/bin/npm run start",
            working_directory="/var/www/apps/shop-example-com/current",
            user="www-data",
            group="www-data",
            environment={"PORT": "3100", "NODE_ENV": "production"},
            resource_limits=(limits or ResourceLimits()).directives(),
        )
    )


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def test_the_unit_with_limits_is_exactly_the_snapshot() -> None:
    """Where and how the three directives appear, pinned whole."""
    assert render(LIMITS) == SNAPSHOT


def test_a_limit_that_is_not_set_writes_no_directive() -> None:
    """No limit means no line, not an empty or zero value systemd would reject."""
    unit = render(ResourceLimits(tasks_max=64))

    assert "TasksMax=64\n" in unit
    assert "MemoryMax" not in unit and "CPUQuota" not in unit
    assert not any(d in render(None) for d in ("MemoryMax", "CPUQuota", "TasksMax"))


def test_editing_a_unit_gives_what_rendering_it_would() -> None:
    """One spelling: the edit and the template cannot disagree, in either direction."""
    assert with_resource_limits(render(None), LIMITS) == render(LIMITS)
    assert with_resource_limits(render(LIMITS), ResourceLimits()) == render(None)
    changed = ResourceLimits(memory_max_mb=1024)
    assert with_resource_limits(render(LIMITS), changed) == render(changed)


def test_an_edited_unit_keeps_the_operator_own_lines() -> None:
    """A hand edit is no reason to lose it; only the limit directives are replaced."""
    unit = "# Generated by WASM\n[Service]\nExecStart=/bin/app\nNice=5\nMemoryMax=1G\n\n[Install]\n"

    edited = with_resource_limits(unit, ResourceLimits(memory_max_mb=256))

    assert edited == (
        "# Generated by WASM\n[Service]\nExecStart=/bin/app\nNice=5\nMemoryMax=256M\n\n[Install]\n"
    )


def test_a_unit_without_a_service_section_is_refused() -> None:
    """There is nowhere a limit would take effect."""
    with pytest.raises(ServiceError, match=r"\[Service\]"):
        with_resource_limits("[Unit]\nDescription=x\n", LIMITS)


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "limits",
    [
        ResourceLimits(memory_max_mb=64),
        ResourceLimits(cpu_quota_percent=1),
        ResourceLimits(cpu_quota_percent=400),
        ResourceLimits(tasks_max=16),
        ResourceLimits(),
    ],
)
def test_limits_a_unit_can_run_under_are_accepted(limits: ResourceLimits) -> None:
    """The boundaries themselves are allowed; four CPUs allow 400%."""
    assert limits.validated(cpus=4) == limits


@pytest.mark.parametrize(
    ("limits", "match"),
    [
        (ResourceLimits(memory_max_mb=63), "at least 64M"),
        (ResourceLimits(cpu_quota_percent=0), "1% to 400%"),
        (ResourceLimits(cpu_quota_percent=401), "1% to 400%"),
        (ResourceLimits(tasks_max=15), "at least 16"),
    ],
)
def test_limits_out_of_range_say_what_is_allowed(limits: ResourceLimits, match: str) -> None:
    """The refusal names the range, so the fix is in the message."""
    with pytest.raises(ValidationError) as failure:
        limits.validated(cpus=4)

    assert match in failure.value.details


def test_the_service_manager_is_the_chokepoint(
    manager: ServiceManager, unit_dirs: dict[str, Path]
) -> None:
    """Created or rewritten, a unit gets limits only through the same validation."""
    with pytest.raises(ValidationError):
        manager.create_service(
            name="shop",
            command="/usr/bin/true",
            working_directory="/srv",
            limits=ResourceLimits(memory_max_mb=8),
        )
    with pytest.raises(ValidationError):
        manager.set_resource_limits("shop", ResourceLimits(tasks_max=1))
    assert list(unit_dirs["managed"].iterdir()) == []


def test_limits_are_written_into_a_unit_and_reloaded(
    manager: ServiceManager, unit_dirs: dict[str, Path], runner: Any
) -> None:
    """Created with limits, then changed: the file holds the new ones, systemd reloaded."""
    manager.create_service(
        name="shop", command="/usr/bin/true", working_directory="/srv", limits=LIMITS
    )
    unit = unit_dirs["managed"] / "shop.service"
    assert "MemoryMax=512M\nCPUQuota=50%\nTasksMax=256\n" in unit.read_text()

    previous = manager.set_resource_limits("shop", ResourceLimits(memory_max_mb=128))

    assert "MemoryMax=512M" in previous
    body = unit.read_text()
    assert "MemoryMax=128M\n" in body and "CPUQuota" not in body and "TasksMax" not in body
    assert runner.calls.count(("systemctl", "daemon-reload")) == 2


# ---------------------------------------------------------------------------
# The application operation
# ---------------------------------------------------------------------------


class FakeUnits:
    """Stands in for ServiceManager: records rewrites and restarts."""

    def __init__(self, fail_on: str | None = None) -> None:
        self.bodies: dict[str, str] = {}
        self.restarts: list[str] = []
        self.fail_on = fail_on

    def set_resource_limits(self, name: str, limits: ResourceLimits) -> str:
        limits.validated()
        if name == self.fail_on:
            raise ServiceError(f"Could not write {name}")
        previous = self.bodies.get(name, "old")
        self.bodies[name] = "\n".join(limits.directives())
        return previous

    def update_config(self, name: str, content: str) -> str:
        previous = self.bodies[name]
        self.bodies[name] = content
        return previous

    def restart(self, name: str) -> None:
        self.restarts.append(name)

    def logs(self, name: str, lines: int = 50) -> str:
        return "Out of memory: Killed process 4242 (node)"


@pytest.fixture
def sqlite_store(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Any:
    """A store where the lifecycle looks for it."""
    WASMStore.reset_instance()
    instance = WASMStore(tmp_path / "wasm.db")
    monkeypatch.setattr(lifecycle, "get_store", lambda: instance)
    yield instance
    WASMStore.reset_instance()


def deploy(store: WASMStore, *, app_type: str = "nodejs", units: tuple[str, ...] = ()) -> App:
    """Register an application and the units it runs as."""
    app = store.create_app(
        App(domain="shop.example.com", app_type=app_type, port=3100, app_path="/srv/shop")
    )
    for name in units:
        store.create_service(Service(app_id=app.id, name=name, command="x", working_directory="/"))
    return app


def test_every_unit_of_the_application_gets_the_limits_and_the_row_keeps_them(
    sqlite_store: WASMStore, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A monorepo's workspaces are limited alike; no restart unless asked."""
    deploy(sqlite_store, app_type="monorepo", units=("shop-web", "shop-api"))
    units = FakeUnits()
    monkeypatch.setattr(lifecycle, "ServiceManager", lambda **kw: units)

    change = lifecycle.set_resource_limits("shop.example.com", LIMITS)

    assert sorted(change.units) == ["shop-api", "shop-web"]
    assert units.bodies == dict.fromkeys(change.units, "MemoryMax=512M\nCPUQuota=50%\nTasksMax=256")
    assert units.restarts == [] and not change.restarted
    app = sqlite_store.get_app("shop.example.com")
    assert app is not None
    assert (app.memory_max_mb, app.cpu_quota_percent, app.tasks_max) == (512, 50, 256)

    probes: list[str] = []
    monkeypatch.setattr(
        lifecycle, "wait_until_healthy", lambda url, **kw: probes.append(url) or True
    )
    lifecycle.set_resource_limits("shop.example.com", LIMITS, restart=True)
    assert sorted(units.restarts) == ["shop-api", "shop-web"]
    assert probes == ["http://127.0.0.1:3100/"], "restarted means proven to answer"


def test_limits_it_cannot_run_under_are_put_back(
    sqlite_store: WASMStore, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Restarted under a limit it dies of, the application gets its old units back."""
    deploy(sqlite_store, units=("shop",))
    units = FakeUnits()
    units.bodies["shop"] = "MemoryMax=2048M"
    monkeypatch.setattr(lifecycle, "ServiceManager", lambda **kw: units)
    answers = iter([False, True])
    monkeypatch.setattr(lifecycle, "wait_until_healthy", lambda url, **kw: next(answers))

    with pytest.raises(DeploymentError, match="previous ones are running again") as failure:
        lifecycle.set_resource_limits(
            "shop.example.com", ResourceLimits(memory_max_mb=64), restart=True
        )

    assert "Out of memory" in failure.value.details
    assert units.bodies == {"shop": "MemoryMax=2048M"}
    assert units.restarts == ["shop", "shop"]
    app = sqlite_store.get_app("shop.example.com")
    assert app is not None and app.memory_max_mb is None


def test_a_unit_that_cannot_be_written_puts_the_others_back(
    sqlite_store: WASMStore, monkeypatch: pytest.MonkeyPatch
) -> None:
    """All or none; the row is not changed either."""
    deploy(sqlite_store, units=("shop-api", "shop-web"))
    order = [s.name for s in sqlite_store.list_services()]
    units = FakeUnits(fail_on=order[-1])
    monkeypatch.setattr(lifecycle, "ServiceManager", lambda **kw: units)

    with pytest.raises(ServiceError):
        lifecycle.set_resource_limits("shop.example.com", LIMITS)

    assert units.bodies == {order[0]: "old"}
    app = sqlite_store.get_app("shop.example.com")
    assert app is not None and app.memory_max_mb is None


@pytest.mark.parametrize(
    ("app_type", "is_static", "match"),
    [("docker-compose", False, "compose file"), ("static", True, "static site")],
)
def test_applications_with_no_unit_of_their_own_are_refused(
    sqlite_store: WASMStore,
    monkeypatch: pytest.MonkeyPatch,
    app_type: str,
    is_static: bool,
    match: str,
) -> None:
    """The limit would not reach what runs, so it is refused with where it belongs."""
    app = deploy(sqlite_store, app_type=app_type)
    app.is_static = is_static
    sqlite_store.update_app(app)
    monkeypatch.setattr(lifecycle, "ServiceManager", lambda **kw: FakeUnits())

    with pytest.raises(DeploymentError) as failure:
        lifecycle.set_resource_limits("shop.example.com", LIMITS)

    assert match in f"{failure.value.message} {failure.value.details}"


def test_a_redeploy_writes_the_recorded_limits_into_the_new_unit(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The limits are the application's, not the deployment's."""
    from tests.test_release_pipeline import FakeServices
    from wasm.deployers.nodejs import NodeJSDeployer

    WASMStore.reset_instance()
    instance = WASMStore(tmp_path / "wasm.db")
    try:
        existing = instance.create_app(
            App(domain="shop.example.com", app_type="nodejs", app_path=str(tmp_path))
        )
        existing.memory_max_mb, existing.tasks_max = 768, 128
        instance.update_app(existing)
        deployer = NodeJSDeployer()
        deployer.store = instance
        services = FakeServices(tmp_path)
        deployer.service_manager = services
        deployer._resolve_absolute_path = lambda command: command
        deployer.configure("shop.example.com", str(tmp_path), port=3100, app_path=tmp_path)
        deployer._app_record = deployer._register_app_in_store("deploying")

        deployer.create_service()
    finally:
        WASMStore.reset_instance()

    assert services.units["shop-example-com"]["limits"] == ResourceLimits(
        memory_max_mb=768, tasks_max=128
    )
