# Copyright (c) 2024-2026 Yago Lopez Prado
# Licensed under WASM-NCSAL 1.0 (Commercial use prohibited)
# https://github.com/Perkybeet/wasm/blob/main/LICENSE

"""
Tests for the cron jobs page and its API.

The page is a thin client of the cron API; the API is a thin client of the
manager; these tests hold both to that. What is asserted is the exact argv
systemctl receives and the exact unit files written into a sandboxed systemd
directory - never a real process.

The refusals matter most: a calendar the manager would not write answers with
the manager's own words and nothing half-written, and deleting demands the
job's exact name typed back, compared server-side, because a ``required``
attribute on an input is a courtesy, not a guard.
"""

# The web fixtures are imported from test_web_views rather than replicated, so
# there stays one definition of "a signed-in panel client". Ruff reads a test
# parameter named after an imported fixture as a redefinition; here it is the
# mechanism.
# ruff: noqa: F811

from __future__ import annotations

from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from tests.test_web_views import (  # noqa: F401  (pytest resolves fixtures by name)
    MISSING_MARKER,
    anonymous,
    app,
    body_of,
    client,
    config_file,
    deploy,
    store,
)
from wasm.core.runner import FakeRunner
from wasm.core.store import WASMStore
from wasm.managers.cron_manager import CronManager

#: What ``systemctl list-unit-files`` prints for one enabled WASM cron timer.
LIST_UNIT_FILES_LINE = "wasm-cron-cleanup.timer enabled enabled\n"

#: What ``systemctl show`` answers about that timer.
SHOW_TIMER_OUTPUT = (
    "TimersCalendar={ OnCalendar=*-*-* 02:00:00 ; next_elapse=Sat 2026-08-15 02:00:00 UTC }\n"
    "LastTriggerUSec=Fri 2026-08-14 02:00:00 UTC\n"
    "NextElapseUSecRealtime=Sat 2026-08-15 02:00:00 UTC\n"
)

#: What ``systemctl show`` answers about the service after a failing run.
SHOW_SERVICE_FAILED = (
    "ExecMainStatus=2\nExecMainExitTimestamp=Fri 2026-08-14 02:00:05 UTC\nResult=exit-code\n"
)

#: A schedule that would append a directive to a root-owned unit file.
INJECTED_CALENDAR = "daily\nOnBootSec=1s"

#: Journal JSON for one run whose output carries markup. It must reach the
#: page verbatim in content and escaped in form: this panel runs as root, and
#: a cron job's output is attacker-influenced text.
JOURNAL_OUTPUT = "\n".join(
    [
        '{"__REALTIME_TIMESTAMP": "1700000000000000",'
        ' "MESSAGE": "ERROR: disk full <b>boom-11</b>", "_SYSTEMD_INVOCATION_ID": "aaa"}',
        '{"__REALTIME_TIMESTAMP": "1700000001000000", "UNIT": "wasm-cron-cleanup.service",'
        ' "INVOCATION_ID": "aaa", "EXIT_CODE": "exited", "EXIT_STATUS": "2"}',
    ]
)


@pytest.fixture
def systemd_dir(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """
    Point the manager's unit directory into the sandbox.

    The API instantiates its own manager per request, so the class attribute
    is patched rather than an instance.

    Args:
        tmp_path: Per-test temporary directory.
        monkeypatch: Patching helper, scoped to the test.

    Returns:
        The directory unit files land in.
    """
    path = tmp_path / "systemd"
    path.mkdir()
    monkeypatch.setattr(CronManager, "SYSTEMD_DIR", path)
    return path


def write_owned_pair(systemd_dir: Path) -> tuple[Path, Path]:
    """
    Write a unit pair the way the manager would, marker included.

    Args:
        systemd_dir: The patched unit directory.

    Returns:
        The timer and service paths.
    """
    timer = systemd_dir / "wasm-cron-cleanup.timer"
    service = systemd_dir / "wasm-cron-cleanup.service"
    timer.write_text("# Generated by WASM\n[Timer]\nOnCalendar=*-*-* 02:00:00\n")
    service.write_text(
        "# Generated by WASM\n# Application: example.com\n[Service]\nUser=www-data\n"
        "ExecStart=/usr/bin/find /tmp/caches -delete\n"
    )
    return timer, service


def scripted_job(runner: FakeRunner) -> None:
    """
    Make systemctl report one cron job named cleanup.

    Args:
        runner: The fake command runner.
    """
    runner.script(("systemctl", "list-unit-files"), stdout=LIST_UNIT_FILES_LINE)
    runner.script(("systemctl", "show", "wasm-cron-cleanup.timer"), stdout=SHOW_TIMER_OUTPUT)
    runner.script(("systemctl", "show", "wasm-cron-cleanup.service"), stdout=SHOW_SERVICE_FAILED)


# ---------------------------------------------------------------- the page


def test_the_page_demands_a_session(anonymous: TestClient) -> None:
    """The cron screen redirects to the sign-in form, like every page."""
    response = anonymous.get("/cron")
    assert response.status_code == 303
    assert response.headers["location"] == "/login"

    section = anonymous.get("/cron/jobs")
    assert section.status_code == 303


def test_the_api_demands_a_session(anonymous: TestClient) -> None:
    """The cron endpoints are not a hole in the fence."""
    assert anonymous.get("/api/cron").status_code in (401, 403)
    assert anonymous.post("/api/cron", json={"name": "x", "command": "/bin/true"}).status_code in (
        401,
        403,
    )
    assert anonymous.delete("/api/cron/x").status_code in (401, 403)
    assert anonymous.post("/api/cron/x/run").status_code in (401, 403)
    assert anonymous.get("/api/cron/x/runs").status_code in (401, 403)


def test_the_page_loads_the_section(client: TestClient) -> None:
    """The page hands the browser the section's address."""
    body = body_of(client, "/cron")

    assert MISSING_MARKER not in body
    assert 'hx-get="/cron/jobs"' in body
    assert "Cron jobs" in body


def test_the_empty_section_renders_and_documents_the_no_shell_rule(
    client: TestClient, runner: FakeRunner, systemd_dir: Path
) -> None:
    """An empty machine still shows the form, and the form tells the truth."""
    body = body_of(client, "/cron/jobs")

    assert MISSING_MARKER not in body
    assert "No cron jobs" in body
    # The shlex decision is documented where the command is typed.
    assert "without a shell" in body
    assert "/bin/sh -c" in body


def test_the_section_renders_each_job(
    client: TestClient, runner: FakeRunner, systemd_dir: Path
) -> None:
    """The row names the job, the command in mono, the schedule and the exit."""
    write_owned_pair(systemd_dir)
    scripted_job(runner)

    body = body_of(client, "/cron/jobs")

    assert MISSING_MARKER not in body
    assert "cleanup" in body
    assert "/usr/bin/find /tmp/caches -delete" in body
    assert "*-*-* 02:00:00" in body
    assert "Sat 2026-08-15 02:00:00 UTC" in body
    # The last run failed with 2: the rail and the badge both say failed.
    assert "row--failed" in body
    assert "exit 2" in body
    assert "example.com" in body


def test_creating_from_the_form_writes_the_units_and_enables_the_timer(
    client: TestClient, runner: FakeRunner, systemd_dir: Path
) -> None:
    """The htmx form drives the same create the JSON API drives."""
    response = client.post(
        "/cron/jobs",
        data={
            "name": "cleanup",
            "command": "/usr/bin/find /tmp/caches -delete",
            "schedule": "daily",
            "user": "www-data",
            "working_directory": "/srv/caches",
        },
    )

    assert response.status_code == 200, response.text
    assert "Cron job cleanup created" in response.text
    timer = systemd_dir / "wasm-cron-cleanup.timer"
    service = systemd_dir / "wasm-cron-cleanup.service"
    assert "OnCalendar=*-*-* 02:00:00" in timer.read_text()
    assert "ExecStart=/usr/bin/find /tmp/caches -delete" in service.read_text()
    assert ("systemctl", "enable", "--now", "wasm-cron-cleanup.timer") in runner.calls


def test_a_refused_calendar_renders_inline_and_writes_nothing(
    client: TestClient, runner: FakeRunner, systemd_dir: Path
) -> None:
    """
    htmx does not swap an error status, so the refusal answers 200 with the
    manager's words on the fragment - and no unit half-written behind it.
    """
    response = client.post(
        "/cron/jobs",
        data={
            "name": "cleanup",
            "command": "/usr/bin/true",
            "schedule": "custom",
            "on_calendar": INJECTED_CALENDAR,
        },
    )

    assert response.status_code == 200
    assert "Invalid cron schedule" in response.text
    assert list(systemd_dir.iterdir()) == []
    # The operator's input survives the refusal.
    assert "/usr/bin/true" in response.text


def test_the_form_offers_the_deployed_applications(
    client: TestClient, runner: FakeRunner, systemd_dir: Path, store: WASMStore
) -> None:
    """The association select is built from what is deployed, not typed."""
    deploy(store)
    deploy(store, domain="other.example.com")

    body = body_of(client, "/cron/jobs")

    assert '<option value="example.com"' in body
    assert '<option value="other.example.com"' in body


# ----------------------------------------------------------------- actions


def test_run_now_starts_the_service(
    client: TestClient, runner: FakeRunner, systemd_dir: Path
) -> None:
    """The Run now button drives one systemctl start of the service unit."""
    write_owned_pair(systemd_dir)
    scripted_job(runner)

    response = client.post("/cron/jobs/cleanup/run")

    assert response.status_code == 200, response.text
    assert ("systemctl", "start", "--no-block", "wasm-cron-cleanup.service") in runner.calls
    assert "Started wasm-cron-cleanup.service" in response.text


def test_enable_and_disable_drive_the_timer(
    client: TestClient, runner: FakeRunner, systemd_dir: Path
) -> None:
    """The toggle posts to the right verb and reports what it did."""
    write_owned_pair(systemd_dir)
    scripted_job(runner)

    disabled = client.post("/cron/jobs/cleanup/disable")
    enabled = client.post("/cron/jobs/cleanup/enable")

    assert ("systemctl", "disable", "--now", "wasm-cron-cleanup.timer") in runner.calls
    assert ("systemctl", "enable", "--now", "wasm-cron-cleanup.timer") in runner.calls
    assert "Disabled wasm-cron-cleanup.timer" in disabled.text
    assert "Enabled wasm-cron-cleanup.timer" in enabled.text


def test_deleting_demands_the_exact_name_typed_back(
    client: TestClient, runner: FakeRunner, systemd_dir: Path
) -> None:
    """A mismatch deletes nothing and says so; the match tears the pair down."""
    timer, service = write_owned_pair(systemd_dir)
    scripted_job(runner)

    refused = client.post("/cron/jobs/cleanup/delete", data={"confirm": "clean"})

    assert refused.status_code == 200
    assert "Nothing was deleted" in refused.text
    assert timer.exists() and service.exists()
    assert ("systemctl", "stop", "wasm-cron-cleanup.timer") not in runner.calls

    accepted = client.post("/cron/jobs/cleanup/delete", data={"confirm": "cleanup"})

    assert accepted.status_code == 200
    assert "Cron job cleanup deleted" in accepted.text
    assert not timer.exists() and not service.exists()
    assert ("systemctl", "stop", "wasm-cron-cleanup.timer") in runner.calls


def test_deleting_a_job_that_does_not_exist_answers_the_refusal_inline(
    client: TestClient, runner: FakeRunner, systemd_dir: Path
) -> None:
    """A delete that removed nothing must not report success."""
    response = client.post("/cron/jobs/ghost/delete", data={"confirm": "ghost"})

    assert response.status_code == 200
    assert "No cron job named ghost" in response.text


def test_a_foreign_unit_is_refused_from_the_panel_too(
    client: TestClient, runner: FakeRunner, systemd_dir: Path
) -> None:
    """The ownership guard's words reach the operator, not a blank screen."""
    (systemd_dir / "wasm-cron-cleanup.timer").write_text("[Timer]\nOnCalendar=hourly\n")

    response = client.post("/cron/jobs/cleanup/run")

    assert response.status_code == 200
    assert "does not manage" in response.text
    assert not any(call[:2] == ("systemctl", "start") for call in runner.calls)


# ----------------------------------------------------------------- history


def test_the_history_renders_the_runs_output_verbatim_and_escaped(
    client: TestClient, runner: FakeRunner, systemd_dir: Path
) -> None:
    """The journal's text reaches the page whole, with its markup inert."""
    write_owned_pair(systemd_dir)
    runner.script(("journalctl",), stdout=JOURNAL_OUTPUT)

    body = body_of(client, "/cron/jobs/cleanup/runs")

    assert MISSING_MARKER not in body
    assert "ERROR: disk full" in body
    # Escaped, not stripped: the operator reads exactly what the job printed.
    assert "&lt;b&gt;boom-11&lt;/b&gt;" in body
    assert "<b>boom-11</b>" not in body
    assert "exit 2" in body
    assert "2023-11-14 22:13:20 UTC" in body


def test_a_job_with_no_recorded_runs_says_so(
    client: TestClient, runner: FakeRunner, systemd_dir: Path
) -> None:
    """An empty history is an explanation, not a blank fragment."""
    write_owned_pair(systemd_dir)
    runner.script(("journalctl",), stdout="")

    body = body_of(client, "/cron/jobs/cleanup/runs")

    assert MISSING_MARKER not in body
    assert "No recorded runs" in body


def test_the_history_row_addresses_resolve(
    client: TestClient, runner: FakeRunner, systemd_dir: Path
) -> None:
    """Every address the section emits answers with the method it is used with."""
    write_owned_pair(systemd_dir)
    scripted_job(runner)

    body = body_of(client, "/cron/jobs")

    assert 'hx-get="/cron/jobs/cleanup/runs"' in body
    assert 'hx-post="/cron/jobs/cleanup/run"' in body
    assert 'hx-post="/cron/jobs/cleanup/delete"' in body


# ----------------------------------------------------------------- the API


def test_the_json_api_lists_jobs_with_their_last_result(
    client: TestClient, runner: FakeRunner, systemd_dir: Path
) -> None:
    """A Bearer client and the section read the same listing."""
    write_owned_pair(systemd_dir)
    scripted_job(runner)

    payload = client.get("/api/cron").json()

    assert payload["total"] == 1
    entry = payload["jobs"][0]
    assert entry["name"] == "cleanup"
    assert entry["schedule"] == "daily"
    assert entry["on_calendar"] == "*-*-* 02:00:00"
    assert entry["last_exit_code"] == 2
    assert entry["enabled"] is True


def test_the_json_api_reports_history(
    client: TestClient, runner: FakeRunner, systemd_dir: Path
) -> None:
    """GET /api/cron/{name}/runs carries the exit code and the output."""
    write_owned_pair(systemd_dir)
    runner.script(("journalctl",), stdout=JOURNAL_OUTPUT)

    payload = client.get("/api/cron/cleanup/runs").json()

    assert payload["total"] == 1
    run = payload["runs"][0]
    assert run["exit_code"] == 2
    assert run["success"] is False
    assert "ERROR: disk full" in run["output"]


def test_an_injected_calendar_answers_422_with_the_managers_refusal(
    client: TestClient, runner: FakeRunner, systemd_dir: Path
) -> None:
    """The request model refuses what the manager would refuse, at 422."""
    response = client.post(
        "/api/cron",
        json={"name": "cleanup", "command": "/usr/bin/true", "schedule": INJECTED_CALENDAR},
    )

    assert response.status_code == 422
    assert "Invalid cron schedule" in response.text
    assert list(systemd_dir.iterdir()) == []
