#!/usr/bin/env python3
"""
Generate the man page from the command tree.

There were two of them, ``man/wasm.1`` and ``obs/wasm.1``, they had diverged,
both were about fifteen releases behind the code, and the one actually shipped
in the .deb and .rpm declared "Licensed under the MIT License" for a project
released under WASM-NCSAL. That is not a documentation slip, it is the wrong
licence on the artifact users install.

One source of truth: the Click tree, which is also what generates the shell
completions, so the manual, the completions and the CLI cannot disagree.

Usage:
    scripts/generate_man.py            Write man/wasm.1 and obs/wasm.1.
    scripts/generate_man.py --check    Fail if either is out of date. CI runs this.
"""

from __future__ import annotations

import argparse
import sys
from datetime import date
from pathlib import Path

import click

ROOT = Path(__file__).resolve().parent.parent
TARGETS = (ROOT / "man/wasm.1", ROOT / "obs/wasm.1")


def escape(text: str) -> str:
    """
    Escape text for roff.

    Args:
        text: Plain text.

    Returns:
        Text safe to place in a man page.
    """
    return text.replace("\\", "\\\\").replace("-", "\\-")


def render_command(command: click.Command, path: tuple[str, ...]) -> list[str]:
    """
    Render one command and its children.

    Args:
        command: The command to document.
        path: Command names leading here, including this one.

    Returns:
        roff lines.
    """
    name = " ".join(path)
    summary = (command.help or command.short_help or "").strip().split("\n\n")[0]
    summary = " ".join(summary.split())

    lines = [f".SS {escape(name)}", escape(summary) or "No description."]

    options = [p for p in command.params if isinstance(p, click.Option)]
    arguments = [p for p in command.params if isinstance(p, click.Argument)]

    if arguments:
        lines.append(".TP")
        lines.append(".B Arguments")
        for arg in arguments:
            lines.append(f".br")
            lines.append(f"\\fI{escape(arg.name or '')}\\fR")

    for option in options:
        if option.name == "help":
            continue
        flags = ", ".join(escape(o) for o in option.opts + option.secondary_opts)
        lines.append(".TP")
        lines.append(f".B {flags}")
        text = " ".join((option.help or "").split()) or "No description."
        if option.default not in (None, False) and not option.is_flag:
            text += f" Default: {option.default}."
        lines.append(escape(text))

    lines.append("")

    if isinstance(command, click.Group):
        ctx = click.Context(command)
        for child_name in command.list_commands(ctx):
            child = command.get_command(ctx, child_name)
            if child is not None:
                lines += render_command(child, path + (child_name,))

    return lines


def build() -> str:
    """
    Render the whole manual.

    Returns:
        The man page source.
    """
    from wasm import __version__
    from wasm.cli.app import cli

    stamp = date.today().isoformat()
    header = [
        f'.TH WASM 1 "{stamp}" "WASM {__version__}" "Web App System Management"',
        '.\\" Generated by scripts/generate_man.py. Do not edit by hand.',
        ".SH NAME",
        "wasm \\- deploy and manage web applications on a Linux server",
        ".SH SYNOPSIS",
        ".B wasm",
        "[\\fIGLOBAL OPTIONS\\fR] \\fICOMMAND\\fR [\\fIARGS\\fR]",
        ".SH DESCRIPTION",
        "WASM deploys and manages web applications on the server it runs on. It",
        "configures the web server, obtains and renews TLS certificates, writes and",
        "supervises systemd units, manages databases and takes backups.",
        ".PP",
        "WASM requires root, because everything it does writes to /etc, /var and",
        "systemd.",
        ".SH COMMANDS",
    ]

    body = render_command(cli, ("wasm",))[2:]

    footer = [
        ".SH FILES",
        ".TP",
        ".I /etc/wasm/config.yaml",
        "Configuration. Contains credentials, so it is created mode 0600 in a 0700",
        "directory.",
        ".TP",
        ".I /var/lib/wasm/wasm.db",
        "What WASM knows about this machine. Mode 0600.",
        ".TP",
        ".I /var/www/apps/",
        "Deployed applications.",
        ".TP",
        ".I /var/backups/wasm/",
        "Backup archives. Each one is self\\-contained.",
        ".SH EXIT STATUS",
        ".TP",
        ".B 0",
        "The command did what it said.",
        ".TP",
        ".B 1",
        "The command failed. The message says what happened and how to fix it.",
        ".TP",
        ".B 2",
        "The command line was wrong.",
        ".TP",
        ".B 130",
        "Interrupted.",
        ".SH SEE ALSO",
        ".BR systemctl (1),",
        ".BR nginx (8),",
        ".BR certbot (1)",
        ".SH LICENSE",
        "WASM\\-NCSAL 1.0. Source\\-available, non\\-commercial use only.",
        ".PP",
        "https://github.com/Perkybeet/wasm/blob/main/LICENSE",
        ".SH AUTHOR",
        "Yago Lopez Prado",
    ]

    return "\n".join(header + body + footer) + "\n"


def main(argv: list[str] | None = None) -> int:
    """
    Command line entry point.

    Args:
        argv: Arguments, defaulting to sys.argv.

    Returns:
        Process exit code.
    """
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    parser.add_argument("--check", action="store_true", help="fail if out of date")
    args = parser.parse_args(argv)

    content = build()

    if args.check:
        # The date line changes daily and says nothing about the content.
        def body_of(text: str) -> str:
            return "\n".join(line for line in text.splitlines() if not line.startswith(".TH "))

        stale = [t for t in TARGETS if not t.exists() or body_of(t.read_text()) != body_of(content)]
        if stale:
            print("These man pages are out of date. Run scripts/generate_man.py:")
            for target in stale:
                print(f"  {target.relative_to(ROOT)}")
            return 1
        print("Man pages match the command tree")
        return 0

    for target in TARGETS:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        print(f"  wrote {target.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
