# Copyright (c) 2024-2026 Yago Lopez Prado
# Licensed under WASM-NCSAL 1.0 (Commercial use prohibited)
# https://github.com/Perkybeet/wasm/blob/main/LICENSE

"""
User cron jobs as first-class systemd timers.

Follows the shape of :mod:`wasm.managers.backup_scheduler`: a timer/service
unit pair named ``wasm-cron-{name}``, rendered through the escaped systemd
templates, written through :mod:`wasm.core.fs` and driven through the shared
:class:`~wasm.core.runner.CommandRunner`, so ``--dry-run`` reaches the unit
files and no test can touch a real systemctl.

Two decisions define this module:

- **The command is an argv, never a shell.** The operator types one command
  line; it is split with :func:`shlex.split` and written to ``ExecStart``
  token by token. systemd itself runs no shell, so pipes, ``&&`` and globs in
  that line are inert text handed to the program as arguments - which is the
  honest behaviour to expose. An operator who wants shell features writes
  ``/bin/sh -c '...'`` explicitly, and the quoted script travels as the single
  argument shlex parsed it as.
- **Only units carrying the WASM marker are touched.** Every unit this module
  writes carries ``Generated by WASM`` (the same marker
  :class:`~wasm.managers.service_manager.ServiceManager` recognises); every
  mutation first reads the unit file back and refuses when the marker is
  missing, so a hand-written ``wasm-cron-*`` unit is never overwritten,
  started or deleted by the panel.

The calendar expression is validated by
:func:`wasm.managers.backup_scheduler.validate_calendar` - the single
definition of what WASM writes after ``OnCalendar=`` - and only re-worded here
so the refusal talks about cron jobs instead of backups.
"""

from __future__ import annotations

import datetime as dt
import json
import re
import shlex
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from jinja2 import Environment, PackageLoader, TemplateError

from wasm.core.config import SYSTEMD_DIR as _SYSTEMD_DIR
from wasm.core.config import Config
from wasm.core.exceptions import BackupError, ServiceError, WASMError
from wasm.core.fs import FileSystem, get_fs
from wasm.core.logger import Logger
from wasm.core.runner import CommandRunner, get_runner
from wasm.core.store import get_store
from wasm.managers.backup_scheduler import SCHEDULE_ALIASES, validate_calendar
from wasm.validators.environment import escape_systemd_value, validate_unit_value
from wasm.validators.names import resolve_within, validate_app_name, validate_service_name

#: Deadline for a systemctl verb. Nothing here talks to the network.
_SYSTEMCTL_TIMEOUT = 60

#: Deadline for reading the journal. It is a local read, but a large journal
#: takes real time to filter.
_JOURNAL_TIMEOUT = 60

#: Unit files are world readable and root writable, like every other unit.
_UNIT_MODE = 0o644

#: Prefix of every unit this manager owns. The name after it is a validated
#: identifier, so the pair can never collide with an application unit.
UNIT_PREFIX = "wasm-cron-"

#: The marker every generated unit carries, shared with the service manager's
#: definition of "a unit WASM created".
WASM_UNIT_MARKER = "Generated by WASM"

#: The ``OnCalendar`` expression inside systemd's ``TimersCalendar`` property,
#: which prints as ``{ OnCalendar=*-*-* 02:00:00 ; next_elapse=... }``.
_ON_CALENDAR = re.compile(r"OnCalendar=([^;}]+)")

#: How the service unit records the application a job belongs to. The comment
#: is rendered by this module's own template, so reading it back is reading
#: this module's own writing.
_APP_COMMENT = "# Application: "

#: An ExecStart token that needs no quoting. ``%`` is deliberately excluded:
#: systemd expands it as a specifier, so any token carrying one goes through
#: the quoted-and-escaped path.
_BARE_TOKEN = re.compile(r"^[A-Za-z0-9_@:,./=+-]+$")

#: How many journal entries to read when reconstructing runs. Bounded so a
#: chatty job cannot make the history endpoint read the whole journal.
_JOURNAL_ENTRIES = 500


@dataclass
class CronJob:
    """
    Configuration for one user cron job.

    Attributes:
        name: Job name, used to build the ``wasm-cron-{name}`` unit names.
        command: One command line. Split with :func:`shlex.split` and executed
            without a shell.
        schedule: Alias from :data:`SCHEDULE_ALIASES` or a systemd calendar
            expression.
        user: Unix user the command runs as. None means the configured
            ``service_user``.
        working_directory: Absolute directory the command runs in. None means
            the associated application's directory when there is one,
            otherwise systemd's default.
        app_domain: Domain of the application this job belongs to, when any.
    """

    name: str
    command: str
    schedule: str
    user: str | None = None
    working_directory: str | None = None
    app_domain: str | None = None

    @property
    def on_calendar(self) -> str:
        """
        Return the schedule as a systemd ``OnCalendar`` expression.

        Returns:
            The expansion of the alias, or the expression itself.
        """
        return SCHEDULE_ALIASES.get(self.schedule, self.schedule)

    @property
    def unit_name(self) -> str:
        """
        Return the base unit name shared by the timer and the service.

        Returns:
            The unit name without a ``.timer`` or ``.service`` suffix.
        """
        return f"{UNIT_PREFIX}{self.name}"


def validate_cron_calendar(schedule: str) -> str:
    """
    Validate a schedule with the scheduler's single calendar definition.

    Args:
        schedule: Alias from :data:`SCHEDULE_ALIASES` or a systemd calendar
            expression.

    Returns:
        The expansion of the alias, or the expression itself.

    Raises:
        ServiceError: When the expression is one
            :func:`~wasm.managers.backup_scheduler.validate_calendar` refuses,
            re-worded for cron jobs but carrying the same rules.
    """
    try:
        return validate_calendar(schedule)
    except BackupError as exc:
        raise ServiceError(
            f"Invalid cron schedule: {schedule!r}",
            details=exc.details
            or f"Use an alias ({', '.join(SCHEDULE_ALIASES)}) or a calendar expression.",
        ) from exc


class CronManager:
    """
    Manager for user cron jobs backed by systemd timers.

    Creates ``wasm-cron-{name}`` timer/service pairs, lists them with their
    next and last run, runs them on demand, and reconstructs their execution
    history from the journal. WASM requires root, so unit files are written
    directly and systemctl is invoked without sudo.
    """

    SYSTEMD_DIR = _SYSTEMD_DIR

    def __init__(
        self,
        verbose: bool = False,
        runner: CommandRunner | None = None,
        fs: FileSystem | None = None,
    ) -> None:
        """
        Initialize the manager.

        Args:
            verbose: Enable verbose logging.
            runner: Command runner used for systemctl and journalctl. Defaults
                to the process-wide runner.
            fs: Filesystem used to write and remove unit files. Defaults to
                the process-wide one, so ``--dry-run`` reaches the unit files
                too.
        """
        self.verbose = verbose
        self.logger = Logger(verbose=verbose)
        self._runner = runner
        self._fs = fs
        self.jinja_env = Environment(
            loader=PackageLoader("wasm", "templates/systemd"),
            trim_blocks=True,
            lstrip_blocks=True,
            # Systemd units are not markup: HTML escaping would corrupt them.
            # The templates escape what matters through the _escape.j2 macros.
            autoescape=False,  # noqa: S701 - systemd unit files, not markup
        )

    @property
    def runner(self) -> CommandRunner:
        """
        Return the command runner used for every external command.

        Returns:
            The injected runner, or the process-wide one.
        """
        return self._runner or get_runner()

    @property
    def fs(self) -> FileSystem:
        """
        Return the filesystem used for every unit file this manager owns.

        Returns:
            The injected filesystem, or the process-wide one.
        """
        return self._fs or get_fs()

    def _systemctl(self, *args: str) -> Any:
        """
        Run a systemctl verb through the shared runner.

        Args:
            args: Arguments after the ``systemctl`` program name.

        Returns:
            The command outcome.
        """
        return self.runner.run(["systemctl", *args], timeout=_SYSTEMCTL_TIMEOUT)

    # Validation -----------------------------------------------------------

    def _validate_name(self, name: str) -> str:
        """
        Validate a job name that is about to become part of two unit names.

        Args:
            name: Candidate job name.

        Returns:
            The validated name.

        Raises:
            ServiceError: When the name cannot safely become a unit name.
        """
        try:
            checked = validate_app_name(name)
            validate_service_name(f"{UNIT_PREFIX}{checked}")
        except WASMError as exc:
            raise ServiceError(
                f"Invalid cron job name: {name!r}",
                details=f"{exc}. The name becomes part of two systemd unit names, so it "
                "is restricted to letters, digits, '.', '_' and '-'.",
            ) from exc
        return checked

    def parse_command(self, command: str) -> list[str]:
        """
        Split a command line into the argv systemd will execute.

        There is no shell anywhere in this path: the line is parsed with
        :func:`shlex.split` and each token becomes one ``ExecStart`` argument,
        so shell metacharacters are inert text. A relative program name is
        resolved to an absolute path once, here, because a unit file must not
        depend on whatever ``$PATH`` systemd happens to have.

        Args:
            command: The command line as the operator typed it.

        Returns:
            The argv, with an absolute path in the first position.

        Raises:
            ServiceError: When the line is empty, cannot be parsed, uses a
                relative path, or names a program that is not installed.
        """
        validate_unit_value(command, field="ExecStart")
        try:
            argv = shlex.split(command)
        except ValueError as exc:
            raise ServiceError(
                f"Cannot parse the command line: {exc}",
                details="Check the quoting. The line is split like a POSIX shell would "
                "split it, but no shell runs it.",
            ) from exc
        if not argv:
            raise ServiceError(
                "The cron job has no command",
                details="Give the command to run, for example: /usr/bin/php artisan schedule:run",
            )

        program = argv[0]
        if "/" in program:
            if not program.startswith("/"):
                raise ServiceError(
                    f"The command path is not absolute: {program}",
                    details="Systemd units use absolute paths. Write the full path, "
                    "for example /usr/bin/node.",
                )
        else:
            resolved = shutil.which(program)
            if resolved is None:
                raise ServiceError(
                    f"Command not found: {program}",
                    details="Nothing by that name is on PATH on this machine. Install it, "
                    "or write the absolute path to the program.",
                )
            argv = [resolved, *argv[1:]]
        return argv

    @staticmethod
    def build_exec_start(argv: list[str]) -> str:
        """
        Render an argv as one systemd ``ExecStart`` value.

        Tokens that need nothing are written bare, so the unit stays readable;
        everything else is double-quoted with systemd's own escaping. ``%`` is
        always doubled, in either form, so systemd does not expand it as a
        specifier.

        Args:
            argv: The parsed argument vector.

        Returns:
            The value to write after ``ExecStart=``.
        """
        rendered = []
        for token in argv:
            if _BARE_TOKEN.match(token):
                rendered.append(token)
            else:
                rendered.append(f'"{escape_systemd_value(token)}"')
        return " ".join(rendered)

    def _validate(self, job: CronJob) -> CronJob:
        """
        Check every value that is about to be written into a unit file.

        Args:
            job: The job to validate.

        Returns:
            A new job with the name checked, the calendar expanded, the user
            defaulted to the configured ``service_user`` and the working
            directory defaulted to the associated application's directory.

        Raises:
            ServiceError: When any value is not something WASM is willing to
                write into a root-owned unit file.
        """
        name = self._validate_name(job.name)
        calendar = validate_cron_calendar(job.schedule)
        # Parsing is validation here: an unparseable or unresolvable command
        # must be refused before anything is written.
        self.parse_command(job.command)

        user = (job.user or "").strip() or Config().service_user
        validate_unit_value(user, field="User")

        app_domain = (job.app_domain or "").strip() or None
        working_directory = (job.working_directory or "").strip() or None
        if app_domain is not None:
            validate_unit_value(app_domain, field="Description")
            app = get_store().get_app(app_domain)
            if app is None:
                raise ServiceError(
                    f"No application is deployed at {app_domain}",
                    details="Associate the job with a deployed domain, or leave the "
                    "application empty.",
                )
            if working_directory is None:
                working_directory = app.app_path
        if working_directory is not None:
            validate_unit_value(working_directory, field="WorkingDirectory")
            if not working_directory.startswith("/"):
                raise ServiceError(
                    f"The working directory is not absolute: {working_directory}",
                    details="Systemd units use absolute paths.",
                )

        return CronJob(
            name=name,
            command=job.command,
            schedule=calendar,
            user=user,
            working_directory=working_directory,
            app_domain=app_domain,
        )

    # Ownership ------------------------------------------------------------

    def _unit_path(self, unit_file: str) -> Path:
        """
        Resolve a unit file name inside the systemd directory.

        Args:
            unit_file: File name including its suffix.

        Returns:
            The path, guaranteed to stay under :attr:`SYSTEMD_DIR`.

        Raises:
            SecurityError: If the name escapes the systemd directory.
        """
        return resolve_within(self.SYSTEMD_DIR, unit_file)

    def _refuse_foreign(self, path: Path) -> None:
        """
        Refuse to touch a unit file that does not carry the WASM marker.

        Args:
            path: Unit file inside the managed directory.

        Raises:
            ServiceError: When the file exists and was not generated by WASM.
        """
        try:
            content = path.read_text()
        except FileNotFoundError:
            return
        except OSError as exc:
            raise ServiceError(
                f"Cannot read unit file: {path}",
                details=f"{exc}. WASM must run as root to manage systemd units.",
            ) from exc
        if WASM_UNIT_MARKER not in content:
            raise ServiceError(
                f"Refusing to touch a unit WASM does not manage: {path.name}",
                details=f"{path} exists but was not generated by WASM. Use systemctl "
                "directly if that is really what you want to do.",
            )

    def _require_owned(self, name: str, *, operation: str) -> tuple[str, Path, Path]:
        """
        Resolve a job's unit pair and refuse to act unless WASM owns it.

        Args:
            name: Job name.
            operation: Verb used in the error message.

        Returns:
            The validated name and the timer and service unit paths.

        Raises:
            ServiceError: When no such job exists, or a unit file with the
                job's name exists without the WASM marker.
        """
        checked = self._validate_name(name)
        timer_path = self._unit_path(f"{UNIT_PREFIX}{checked}.timer")
        service_path = self._unit_path(f"{UNIT_PREFIX}{checked}.service")

        self._refuse_foreign(timer_path)
        self._refuse_foreign(service_path)

        if not timer_path.exists() and not service_path.exists():
            raise ServiceError(
                f"Unknown cron job: {checked}",
                details=f"Cannot {operation} it: there is no {UNIT_PREFIX}{checked} unit "
                f"pair under {self.SYSTEMD_DIR}.",
            )
        return checked, timer_path, service_path

    # Rendering ------------------------------------------------------------

    def _render(self, template_name: str, **values: str) -> str:
        """
        Render one of the escaped systemd templates.

        Args:
            template_name: File name of the template.
            values: Values passed to the template.

        Returns:
            The rendered unit file.

        Raises:
            ServiceError: If the template is missing or fails to render.
        """
        try:
            template = self.jinja_env.get_template(template_name)
            return template.render(**values)
        except TemplateError as exc:
            raise ServiceError(
                f"Failed to render systemd template: {template_name}",
                details=f"{exc}. The WASM installation may be incomplete.",
            ) from exc

    def render_timer(self, job: CronJob) -> str:
        """
        Render the systemd timer unit for a validated job.

        Args:
            job: The job, as :meth:`_validate` returned it.

        Returns:
            The unit file content, with every interpolated value escaped.
        """
        return self._render("cron-timer.j2", name=job.name, schedule=job.on_calendar)

    def render_service(self, job: CronJob) -> str:
        """
        Render the systemd service unit for a validated job.

        Args:
            job: The job, as :meth:`_validate` returned it.

        Returns:
            The unit file content, with every interpolated value escaped.
        """
        return self._render(
            "cron-service.j2",
            name=job.name,
            unit_name=job.unit_name,
            user=job.user or "",
            working_directory=job.working_directory or "",
            app_domain=job.app_domain or "",
            exec_start=self.build_exec_start(self.parse_command(job.command)),
        )

    # Operations -----------------------------------------------------------

    def create_job(self, job: CronJob) -> CronJob:
        """
        Create a cron job as a systemd timer and service pair.

        Creating a job whose units already carry the WASM marker rewrites
        them, so this is also how a job is changed. A unit pair somebody else
        wrote is refused, never overwritten.

        Args:
            job: The job configuration.

        Returns:
            The job as validated and written.

        Raises:
            ServiceError: If a value is unusable, a unit belongs to someone
                else, a unit cannot be written or the timer cannot be enabled.
        """
        checked = self._validate(job)

        timer_path = self._unit_path(f"{checked.unit_name}.timer")
        service_path = self._unit_path(f"{checked.unit_name}.service")
        self._refuse_foreign(timer_path)
        self._refuse_foreign(service_path)

        for path, content in (
            (timer_path, self.render_timer(checked)),
            (service_path, self.render_service(checked)),
        ):
            try:
                self.fs.write_text(path, content, mode=_UNIT_MODE)
            except OSError as exc:
                raise ServiceError(
                    f"Failed to write unit file: {path}",
                    details=f"{exc}. WASM must run as root to manage systemd units.",
                ) from exc

        self._systemctl("daemon-reload")

        result = self._systemctl("enable", "--now", f"{checked.unit_name}.timer")
        if not result.success:
            raise ServiceError(
                f"Failed to enable timer: {checked.unit_name}.timer",
                details=result.stderr.strip() or "Check 'systemctl status' for details.",
            )

        self.logger.info(f"Created cron job: {checked.unit_name}")
        self.logger.info(f"  Schedule: {checked.on_calendar}")
        return checked

    def delete_job(self, name: str) -> bool:
        """
        Remove a cron job's timer and service units.

        Args:
            name: Job name.

        Returns:
            True when the job was removed.

        Raises:
            ServiceError: When no such job exists or the units are not WASM's.
        """
        checked, timer_path, service_path = self._require_owned(name, operation="delete")

        self._systemctl("stop", f"{UNIT_PREFIX}{checked}.timer")
        self._systemctl("disable", f"{UNIT_PREFIX}{checked}.timer")

        for path in (timer_path, service_path):
            try:
                self.fs.remove(path)
            except OSError as exc:
                self.logger.warning(f"Could not remove {path}: {exc}")

        self._systemctl("daemon-reload")

        self.logger.info(f"Removed cron job: {UNIT_PREFIX}{checked}")
        return True

    def run_now(self, name: str) -> str:
        """
        Start a job's service unit immediately, outside its schedule.

        The start is asynchronous: systemd queues the run and the outcome
        lands in the job's history, exactly as a scheduled run would.

        Args:
            name: Job name.

        Returns:
            The unit that was started.

        Raises:
            ServiceError: When no such job exists, the units are not WASM's,
                or systemd refuses the start.
        """
        checked, _, _ = self._require_owned(name, operation="run")
        unit = f"{UNIT_PREFIX}{checked}.service"

        result = self._systemctl("start", "--no-block", unit)
        if not result.success:
            raise ServiceError(
                f"Failed to start {unit}",
                details=result.stderr.strip() or "Check 'systemctl status' for details.",
            )
        return unit

    def enable_job(self, name: str) -> str:
        """
        Enable a job's timer and start it now.

        Args:
            name: Job name.

        Returns:
            The timer unit that was enabled.

        Raises:
            ServiceError: When no such job exists, the units are not WASM's,
                or systemd refuses.
        """
        return self._timer_verb(name, "enable", "--now")

    def disable_job(self, name: str) -> str:
        """
        Disable a job's timer and stop it, keeping the unit files.

        Args:
            name: Job name.

        Returns:
            The timer unit that was disabled.

        Raises:
            ServiceError: When no such job exists, the units are not WASM's,
                or systemd refuses.
        """
        return self._timer_verb(name, "disable", "--now")

    def _timer_verb(self, name: str, *verb: str) -> str:
        """
        Apply an enable or disable verb to an owned job's timer.

        Args:
            name: Job name.
            verb: The systemctl verb and its flags.

        Returns:
            The timer unit acted on.

        Raises:
            ServiceError: When the job is unknown, foreign, or systemd
                refuses.
        """
        checked, _, _ = self._require_owned(name, operation=verb[0])
        unit = f"{UNIT_PREFIX}{checked}.timer"

        result = self._systemctl(*verb, unit)
        if not result.success:
            raise ServiceError(
                f"Failed to {verb[0]} {unit}",
                details=result.stderr.strip() or "Check 'systemctl status' for details.",
            )
        return unit

    # Listing --------------------------------------------------------------

    @staticmethod
    def _show_properties(output: str) -> dict[str, str]:
        """
        Parse ``systemctl show`` output into its property mapping.

        Args:
            output: The ``Property=value`` lines systemctl printed.

        Returns:
            One entry per property.
        """
        properties: dict[str, str] = {}
        for line in output.splitlines():
            key, separator, value = line.partition("=")
            if separator:
                properties[key] = value.strip()
        return properties

    def _read_service_fields(self, name: str) -> dict[str, str]:
        """
        Read command, user, directory and application back from a unit file.

        The file is this module's own writing, rendered from validated values,
        so parsing it is reading our own records - the same way the backup
        scheduler reads the domain back out of its own Description line.

        Args:
            name: Validated job name.

        Returns:
            ``command`` (the raw ``ExecStart`` value), ``user``,
            ``working_directory`` and ``app_domain``, each empty when the file
            cannot be read.
        """
        fields = {"command": "", "user": "", "working_directory": "", "app_domain": ""}
        path = self.SYSTEMD_DIR / f"{UNIT_PREFIX}{name}.service"
        try:
            content = path.read_text()
        except OSError:
            return fields
        for line in content.splitlines():
            if line.startswith("ExecStart="):
                fields["command"] = line[len("ExecStart=") :].strip()
            elif line.startswith("User="):
                fields["user"] = line[len("User=") :].strip()
            elif line.startswith("WorkingDirectory="):
                fields["working_directory"] = line[len("WorkingDirectory=") :].strip()
            elif line.startswith(_APP_COMMENT):
                fields["app_domain"] = line[len(_APP_COMMENT) :].strip()
        return fields

    def _job_info(self, name: str, enabled: bool) -> dict[str, Any]:
        """
        Build the listing entry for one owned job.

        Args:
            name: Validated job name.
            enabled: Whether the timer's unit file is enabled.

        Returns:
            The entry: name, command, schedule, run times and last result.
        """
        info: dict[str, Any] = {
            "name": name,
            "enabled": enabled,
            "on_calendar": "",
            "next_run": "pending",
            "last_run": "never",
            "last_exit_code": None,
            "last_result": "never ran",
        }
        info.update(self._read_service_fields(name))

        timer = self._systemctl(
            "show",
            f"{UNIT_PREFIX}{name}.timer",
            "--property=TimersCalendar,LastTriggerUSec,NextElapseUSecRealtime",
        )
        if timer.success:
            properties = self._show_properties(timer.stdout)
            match = _ON_CALENDAR.search(properties.get("TimersCalendar", ""))
            if match:
                info["on_calendar"] = match.group(1).strip()
            next_run = properties.get("NextElapseUSecRealtime", "")
            if next_run and next_run != "n/a":
                info["next_run"] = next_run
            last_run = properties.get("LastTriggerUSec", "")
            if last_run and last_run != "n/a":
                info["last_run"] = last_run

        service = self._systemctl(
            "show",
            f"{UNIT_PREFIX}{name}.service",
            "--property=ExecMainStatus,ExecMainExitTimestamp,Result",
        )
        if service.success:
            properties = self._show_properties(service.stdout)
            exited = properties.get("ExecMainExitTimestamp", "")
            if exited and exited != "n/a":
                try:
                    info["last_exit_code"] = int(properties.get("ExecMainStatus", "0"))
                except ValueError:
                    info["last_exit_code"] = None
                info["last_result"] = properties.get("Result", "") or "unknown"
        return info

    def _is_owned_unit(self, name: str) -> bool:
        """
        Report whether a job's timer file is one this module wrote.

        Args:
            name: Validated job name.

        Returns:
            True when the file lives in the managed directory and carries the
            marker. A ``wasm-cron-*`` unit somebody wrote by hand is skipped
            from listings rather than presented as something the panel can
            manage.
        """
        try:
            return WASM_UNIT_MARKER in (self.SYSTEMD_DIR / f"{UNIT_PREFIX}{name}.timer").read_text()
        except OSError:
            return False

    def list_jobs(self) -> list[dict[str, Any]]:
        """
        List every WASM cron job with its schedule, next run and last result.

        ``list-unit-files`` is the source rather than ``list-timers`` because
        a disabled timer - a state this manager deliberately supports - does
        not appear in ``list-timers`` at all. Every value then comes from
        ``systemctl show``, whose ``Property=value`` lines are a stable
        contract, and from the unit files this module itself wrote.

        Returns:
            One entry per job: ``name``, ``command`` (the raw ``ExecStart``
            value), ``user``, ``working_directory``, ``app_domain``,
            ``enabled``, ``on_calendar``, ``next_run`` and ``last_run`` as
            systemd prints them, ``last_exit_code`` (None when the job never
            ran) and ``last_result``.
        """
        result = self._systemctl(
            "list-unit-files", "--no-legend", "--no-pager", f"{UNIT_PREFIX}*.timer"
        )
        if not result.success:
            return []

        jobs: list[dict[str, Any]] = []
        for line in result.stdout.strip().splitlines():
            parts = line.split()
            unit = next((part for part in parts if part.endswith(".timer")), None)
            if unit is None:
                continue
            name = unit[len(UNIT_PREFIX) : -len(".timer")]
            try:
                self._validate_name(name)
            except ServiceError:
                continue
            if not self._is_owned_unit(name):
                self.logger.debug(f"Skipping {unit}: not generated by WASM")
                continue
            state = parts[1] if len(parts) > 1 else ""
            jobs.append(self._job_info(name, enabled=state == "enabled"))
        return sorted(jobs, key=lambda job: job["name"])

    def get_job(self, name: str) -> dict[str, Any] | None:
        """
        Get one job's listing entry.

        Args:
            name: Job name.

        Returns:
            The entry, or None when no owned unit pair exists for the name.

        Raises:
            ServiceError: When the name is not a usable job name.
        """
        checked = self._validate_name(name)
        if not self._is_owned_unit(checked):
            return None
        state = self._systemctl("is-enabled", f"{UNIT_PREFIX}{checked}.timer")
        return self._job_info(checked, enabled=state.stdout.strip() == "enabled")

    # History --------------------------------------------------------------

    @staticmethod
    def _timestamp(entry: dict[str, Any]) -> str:
        """
        Format a journal entry's realtime timestamp for humans.

        Args:
            entry: The parsed journal entry.

        Returns:
            The timestamp in UTC, or an empty string when the entry has none.
        """
        raw = entry.get("__REALTIME_TIMESTAMP", "")
        try:
            microseconds = int(raw)
        except (TypeError, ValueError):
            return ""
        moment = dt.datetime.fromtimestamp(microseconds / 1_000_000, tz=dt.timezone.utc)
        return moment.strftime("%Y-%m-%d %H:%M:%S UTC")

    def runs(self, name: str, *, limit: int = 10, lines: int = 20) -> list[dict[str, Any]]:
        """
        Reconstruct a job's recent executions from the journal.

        The journal is read as JSON and grouped by systemd's own invocation
        id, which is the one fact that separates two runs of the same unit.
        The exit code comes from the fields systemd attaches, never from
        parsing message text: a failing main process carries ``EXIT_STATUS``,
        and a start job reported ``done`` is a run that finished with 0.

        Args:
            name: Job name.
            limit: Most runs to return.
            lines: Most output lines to keep per run; the last ones win,
                because the end of a cron job's output is where it says what
                went wrong.

        Returns:
            The runs, newest first. Each carries ``started``, ``exit_code``
            (None while it is still unknown), ``success`` (None while
            unknown) and ``lines``, the unit's own output verbatim.

        Raises:
            ServiceError: When no such job exists or the units are not WASM's.
        """
        checked, _, _ = self._require_owned(name, operation="read the history of")
        unit_file = f"{UNIT_PREFIX}{checked}.service"

        result = self.runner.run(
            [
                "journalctl",
                "-u",
                unit_file,
                "-o",
                "json",
                "-n",
                str(_JOURNAL_ENTRIES),
                "--no-pager",
            ],
            timeout=_JOURNAL_TIMEOUT,
        )
        if not result.success:
            return []

        runs: dict[str, dict[str, Any]] = {}
        for line in result.stdout.splitlines():
            try:
                entry = json.loads(line)
            except ValueError:
                continue
            if not isinstance(entry, dict):
                continue

            if entry.get("UNIT") == unit_file and "INVOCATION_ID" in entry:
                # A message from systemd itself about this unit, carrying the
                # invocation it talks about and, on failure, the exit status.
                run = runs.setdefault(
                    str(entry["INVOCATION_ID"]),
                    {"started": self._timestamp(entry), "exit_code": None, "lines": []},
                )
                status = entry.get("EXIT_STATUS")
                if status is not None:
                    try:
                        run["exit_code"] = int(status)
                    except (TypeError, ValueError):
                        pass
                elif entry.get("JOB_RESULT") == "done" and run["exit_code"] is None:
                    run["exit_code"] = 0
            elif "_SYSTEMD_INVOCATION_ID" in entry:
                # A line the job itself printed.
                run = runs.setdefault(
                    str(entry["_SYSTEMD_INVOCATION_ID"]),
                    {"started": self._timestamp(entry), "exit_code": None, "lines": []},
                )
                if not run["started"]:
                    run["started"] = self._timestamp(entry)
                message = entry.get("MESSAGE")
                if isinstance(message, str):
                    run["lines"].append(message)

        shaped = []
        for run in runs.values():
            exit_code = run["exit_code"]
            shaped.append(
                {
                    "started": run["started"],
                    "exit_code": exit_code,
                    "success": (exit_code == 0) if exit_code is not None else None,
                    "lines": run["lines"][-lines:],
                }
            )
        # The journal prints oldest first; the operator wants newest first.
        return list(reversed(shaped))[:limit]
