"""
Systemd service manager for WASM.

This module is the only door to systemd, and WASM runs as root, so the question
it has to answer before every single operation is *who owns this unit*. Getting
that wrong is not a cosmetic bug: ``wasm service delete ssh`` used to stop and
disable sshd, because the ownership guard only ran when a file existed under
``/etc/systemd/system`` and distribution units live in ``/usr/lib/systemd/system``.

Definition of a WASM-managed unit
---------------------------------
A unit belongs to WASM when **all three** hold:

1. **systemd loads it from the directory WASM manages.** The authority is
   ``systemctl show -p FragmentPath``, not a guess based on paths: it is one
   call and it reports where the unit actually comes from, including when a
   name in ``/etc`` is an alias for a file shipped by the distribution.
2. **It does not shadow a unit shipped with the system.** A file in our
   directory that eclipses ``/usr/lib/systemd/system/nginx.service`` is a
   takeover of the distribution's unit, not one of ours, and is refused even
   though it sits in the right directory.
3. **It carries a WASM signal**: the ``wasm-`` prefix (the historical naming
   scheme), a record in the store's services table, the ``Generated by WASM``
   marker written by the templates, or being the unit an application in the
   store runs as (:meth:`ServiceManager.app_units`). Several signals because
   any one of them can be missing on a server that has been upgraded or
   repaired by hand: since 0.14.1 app units carry no prefix, and a store that
   was moved or rebuilt has an empty services table.

Every operation that reads or changes unit state goes through
:meth:`ServiceManager.inspect_unit`, so the guard cannot be forgotten in one
code path the way it was before.

The units WASM manages, as a set
--------------------------------
:meth:`ServiceManager.managed_units` is the one answer to "which units are
WASM's": every unit file in the managed directory carrying a signal, plus the
unit(s) of every application in the store, judged by the same rule as
:meth:`~ServiceManager.inspect_unit`. The console's top bar, the Services page,
``wasm service list``, the live log stream and the monitor all read it. It
costs one ``systemctl list-units`` and a scan of one directory, because the
top bar asks for it every five seconds.

Secrets go in ``EnvironmentFile=``, not ``Environment=``
------------------------------------------------------
A unit file is 0644, and ``systemctl show <unit>`` prints its ``Environment=``
to any local user, not only to root: an unprivileged account on the machine
could read every DATABASE_URL and API key an application was deployed with.
So an application's unit carries inline only what is not secret and is WASM's
to decide (PORT, NODE_ENV), and loads the rest with ``EnvironmentFile=-`` from
the application's env file - the one
:func:`~wasm.deployers.helpers.layout.env_file_for` names, 0600 and owned by
the service account, which backups, restores and deletes already know about
because ``wasm env`` and the panel edit the same file.

Two consequences the callers own. systemd lets ``EnvironmentFile=`` override
``Environment=``, so the deployers keep PORT and NODE_ENV out of the file.
And the file is parsed by systemd as well as by the application, so it is
written in the one grammar both read the same way (see
:class:`~wasm.deployers.helpers.env_manager.EnvManager`). A unit written by
an earlier version, with the variables inline, keeps working as it is; the
next deploy moves them into the file.

Everything still interpolated into a unit is validated in
:meth:`ServiceManager.create_service` - mandatory, since this manager is the
single step every caller must pass through - and escaped at render time.
"""

from __future__ import annotations

import os
import re
import sqlite3
import tempfile
from collections.abc import Callable, Collection, Mapping
from dataclasses import dataclass
from functools import partial
from pathlib import Path
from typing import Any, ClassVar

from jinja2 import Environment, PackageLoader, TemplateNotFound
from jinja2 import TemplateError as JinjaTemplateError

from wasm.core.config import SYSTEMD_DIR
from wasm.core.exceptions import ServiceError, TemplateError, ValidationError, WASMError
from wasm.core.fs import SECRET_DIR_MODE, SECRET_MODE, FileSystem
from wasm.core.runner import DEFAULT_TIMEOUT, CommandResult, CommandRunner
from wasm.core.store import App, Service, get_store
from wasm.core.utils import domain_to_app_name
from wasm.managers.base_manager import BaseManager
from wasm.validators.environment import validate_environment, validate_unit_value
from wasm.validators.names import validate_service_name

#: Marker every generated unit file carries, used to recognise our own units
#: when the store has lost track of them.
WASM_UNIT_MARKER = "Generated by WASM"

#: Starting or restarting an app can take a while: systemd waits for the unit
#: to settle before it answers.
_LIFECYCLE_TIMEOUT = 120

#: ``journalctl -f`` runs until the caller stops reading. The deadline exists
#: because the runner requires one, not because an hour of logs is a limit
#: anybody should hit; callers that need longer pass their own.
_FOLLOW_TIMEOUT = 3600

#: Unit files are not secret - systemd reads them as root and users need to be
#: able to inspect them - but nothing outside root may rewrite one.
UNIT_FILE_MODE = 0o644

#: systemd-analyze verify parses the unit and, for a .service, resolves its
#: ExecStart binary; both are fast, but a deadline is still mandatory.
VERIFY_TIMEOUT = 15


#: The smallest memory limit accepted. Below it a Node or Python process is
#: killed by the OOM killer while it is still loading, which looks like a
#: crash loop rather than a limit.
MIN_MEMORY_MB = 64

#: The smallest task limit accepted. A runtime starts a handful of threads
#: before it runs any application code, and a limit it cannot start under is
#: a unit that never comes up.
MIN_TASKS = 16

#: The directives this manager owns in a unit's ``[Service]`` section.
LIMIT_DIRECTIVES = ("MemoryMax", "CPUQuota", "TasksMax")

#: The leading arguments of every ``systemctl list-units`` this manager runs;
#: the unit patterns follow them.
LIST_UNITS_ARGV = (
    "systemctl",
    "list-units",
    "--type=service",
    "--all",
    "--no-pager",
    "--plain",
)

#: What a unit is described with when the Services page lists it: the fields
#: :meth:`ServiceManager.get_status` reports, read for every unit in one
#: ``systemctl show``.
DESCRIBE_PROPERTIES = (
    "Id",
    "LoadState",
    "ActiveState",
    "SubState",
    "Result",
    "ExecMainStatus",
    "NRestarts",
    "MainPID",
    "MemoryCurrent",
    "ActiveEnterTimestamp",
    "UnitFileState",
)

#: A unit name as systemd itself writes it: ASCII letters, digits and
#: ``:-_.\\@``, where ``\\xNN`` escapes everything else
#: (``systemd-fsck@dev-disk-by\\x2dlabel-BOOT``). Wider than the names WASM
#: creates, which :func:`~wasm.validators.names.validate_service_name` still
#: enforces for every write; this is only for naming a unit that is read.
SYSTEMD_UNIT_NAME = re.compile(r"^[A-Za-z0-9:_\\@][A-Za-z0-9:_.\\@-]*$")

#: systemd refuses longer unit names.
MAX_UNIT_NAME_LENGTH = 255


def readable_unit_name(name: str) -> str:
    """
    Check a unit name that is only going to be read about.

    systemd names its own units with escapes (``\\x2d`` for a dash inside a
    path component) and instances (``getty@tty1``), and the unit-name validator
    WASM writes with refuses both: listing every unit on the machine used to
    fail as a whole on the first ``systemd-fsck@...`` it met. Read-only paths
    use this instead. It is still argv-safe: no ``/``, no whitespace, no glob
    character, nothing that could start an option.

    Args:
        name: A unit name, with or without the ``.service`` suffix.

    Returns:
        The name without the suffix.

    Raises:
        ValidationError: When it is not a name systemd could have given a unit.
    """
    unit = str(name).removesuffix(".service")
    if not unit or len(unit) > MAX_UNIT_NAME_LENGTH or not SYSTEMD_UNIT_NAME.match(unit):
        raise ValidationError(
            f"Not a systemd unit name: {unit!r}",
            details=(
                "A unit name is made of letters, digits and ':-_.\\@'; "
                "systemd escapes anything else as \\xNN."
            ),
        )
    return unit


def _is_plain(name: str) -> bool:
    """
    Report whether a unit name is inert as a ``list-units`` pattern.

    Args:
        name: Unit name.

    Returns:
        True when it has no glob or escape character.
    """
    return not any(char in name for char in "*?[]\\")


@dataclass(frozen=True)
class ManagedUnit:
    """
    One unit WASM manages, as :meth:`ServiceManager.managed_units` found it.

    Attributes:
        name: Unit name without the ``.service`` suffix.
        load: systemd's LOAD column (``loaded``, ``not-found``, ...), or
            ``not-loaded`` for a unit file systemd has not loaded because
            nothing is using it.
        active: systemd's ACTIVE column (``active``, ``failed``, ...).
        sub: systemd's SUB column (``running``, ``dead``, ``auto-restart``...).
        app: Domain of the application this unit runs, or None for a unit
            that is not an application's (the monitor, a cron job, a service
            created by hand).
    """

    name: str
    load: str
    active: str
    sub: str
    app: str | None = None

    @property
    def unit_file(self) -> str:
        """The full unit name, as systemctl expects it."""
        return f"{self.name}.service"

    def as_dict(self) -> dict[str, Any]:
        """
        The row shape :meth:`ServiceManager.list_services` has always returned.

        Returns:
            ``name``, ``load``, ``active`` and ``sub`` as systemd wrote them,
            ``managed`` (always True here) and ``app``.
        """
        return {
            "name": self.name,
            "load": self.load,
            "active": self.active,
            "sub": self.sub,
            "managed": True,
            "app": self.app,
        }


@dataclass(frozen=True)
class ResourceLimits:
    """
    What a unit may use. None means unlimited, and writes no directive.

    Attributes:
        memory_max_mb: ``MemoryMax=``, in megabytes.
        cpu_quota_percent: ``CPUQuota=``, in percent of one CPU; 200 is two.
        tasks_max: ``TasksMax=``, processes and threads together.
    """

    memory_max_mb: int | None = None
    cpu_quota_percent: int | None = None
    tasks_max: int | None = None

    @classmethod
    def of(cls, app: App | None) -> ResourceLimits:
        """
        Read the limits an application's row records.

        Args:
            app: The application, or None for no limits.

        Returns:
            Its limits.
        """
        if app is None:
            return cls()
        return cls(
            memory_max_mb=app.memory_max_mb,
            cpu_quota_percent=app.cpu_quota_percent,
            tasks_max=app.tasks_max,
        )

    def validated(self, cpus: int | None = None) -> ResourceLimits:
        """
        Check that the limits are ones a unit can run under.

        Args:
            cpus: CPUs on this machine; read from the machine when None.

        Returns:
            The same limits.

        Raises:
            ValidationError: A limit is below what a runtime needs to start,
                or asks for more CPU than the machine has.
        """
        available = cpus if cpus is not None else (os.cpu_count() or 1)
        if self.memory_max_mb is not None and self.memory_max_mb < MIN_MEMORY_MB:
            raise ValidationError(
                f"A memory limit of {self.memory_max_mb}M is too small",
                details=f"Allow at least {MIN_MEMORY_MB}M, or no limit.",
            )
        if self.cpu_quota_percent is not None and not (
            1 <= self.cpu_quota_percent <= 100 * available
        ):
            raise ValidationError(
                f"A CPU quota of {self.cpu_quota_percent}% is not possible here",
                details=f"This machine has {available} CPU(s): use 1% to {100 * available}%.",
            )
        if self.tasks_max is not None and self.tasks_max < MIN_TASKS:
            raise ValidationError(
                f"A limit of {self.tasks_max} tasks is too small",
                details=f"Allow at least {MIN_TASKS}, or no limit.",
            )
        return self

    def directives(self) -> list[str]:
        """
        Write the limits as unit directives.

        The one spelling of them: the template renders these lines when a unit
        is created and :func:`with_resource_limits` puts them into one that
        exists, so the two cannot disagree.

        Returns:
            One line per limit that is set, in a fixed order.
        """
        lines = []
        if self.memory_max_mb is not None:
            lines.append(f"MemoryMax={self.memory_max_mb}M")
        if self.cpu_quota_percent is not None:
            lines.append(f"CPUQuota={self.cpu_quota_percent}%")
        if self.tasks_max is not None:
            lines.append(f"TasksMax={self.tasks_max}")
        return lines


def with_resource_limits(unit: str, limits: ResourceLimits) -> str:
    """
    Put limits into an existing unit, leaving everything else as it is.

    The unit is edited rather than rendered again, because an operator may
    have edited it by hand (the panel's unit editor exists for that) and a
    limit is no reason to throw that away. Any previous limit directive in
    ``[Service]`` is removed; the new ones go after ``LimitNOFILE=`` when the
    unit has it, which is where the template puts them, or at the end of the
    section.

    Args:
        unit: The unit file.
        limits: The limits it must have.

    Returns:
        The unit with exactly these limits.

    Raises:
        ServiceError: The unit has no ``[Service]`` section.
    """
    lines = unit.split("\n")
    section = ""
    start = end = anchor = None
    kept: list[str] = []
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("[") and stripped.endswith("]"):
            if section == "[Service]" and end is None:
                end = len(kept)
            section = stripped
            if section == "[Service]":
                start = len(kept)
        elif section == "[Service]" and stripped.split("=", 1)[0] in LIMIT_DIRECTIVES:
            continue
        elif section == "[Service]" and stripped.startswith("LimitNOFILE="):
            anchor = len(kept) + 1
        kept.append(line)
    if start is None:
        raise ServiceError(
            "The unit has no [Service] section to put limits in",
            details="Check the unit with 'systemctl cat <name>'; WASM writes one in every unit.",
        )
    if end is None:
        end = len(kept)
    # Blank lines closing the section stay after the directives, not before.
    while end > start + 1 and not kept[end - 1].strip():
        end -= 1
    position = anchor if anchor is not None else end
    return "\n".join(kept[:position] + limits.directives() + kept[position:])


@dataclass(frozen=True)
class UnitOwnership:
    """
    What WASM knows about one systemd unit.

    Attributes:
        unit: Validated unit name without the ``.service`` suffix.
        path: Where WASM would write this unit inside its own directory.
        fragment_path: The file systemd reports loading the unit from, when
            systemd could be asked.
        exists: True when a unit file for this name exists anywhere systemd
            looks, or systemd already knows the unit.
        managed: True when the unit satisfies every ownership rule.
        reason: Why the unit is not managed. Empty when it is.
    """

    unit: str
    path: Path
    fragment_path: Path | None
    exists: bool
    managed: bool
    reason: str = ""

    @property
    def unit_file(self) -> str:
        """The full unit name, as systemctl expects it."""
        return f"{self.unit}.service"


class ServiceManager(BaseManager):
    """
    Manager for systemd services.

    Handles creating, starting, stopping, and managing systemd services. Every
    public method refuses to act on a unit WASM does not own; see the module
    docstring for what ownership means.
    """

    SYSTEMD_DIR = SYSTEMD_DIR

    #: Every directory systemd loads units from, most specific first. Ownership
    #: is decided against all of them: looking only at ``/etc/systemd/system``
    #: is what let ``delete ssh`` through, because sshd lives in ``/usr/lib``.
    UNIT_SEARCH_DIRS: tuple[Path, ...] = (
        SYSTEMD_DIR,
        Path("/run/systemd/system"),
        Path("/run/systemd/transient"),
        Path("/etc/systemd/system.control"),
        Path("/usr/local/lib/systemd/system"),
        Path("/usr/lib/systemd/system"),
        Path("/lib/systemd/system"),
    )

    #: Prefix carried by every unit this project created before the name was
    #: shortened. New units drop it and are recognised through the store or the
    #: unit-file marker instead.
    SERVICE_PREFIX = "wasm-"
    LEGACY_PREFIX = SERVICE_PREFIX

    def __init__(
        self,
        verbose: bool = False,
        runner: CommandRunner | None = None,
        fs: FileSystem | None = None,
    ):
        """
        Initialize service manager.

        Args:
            verbose: Enable verbose logging.
            runner: Command runner to execute systemd with. Defaults to the
                process-wide runner.
            fs: Filesystem to write unit files through. Defaults to the
                process-wide one, which is what makes ``--dry-run`` refuse to
                install or delete a unit.
        """
        super().__init__(verbose=verbose, runner=runner, fs=fs)
        self.store = get_store()

        try:
            # Unit files are not markup: autoescaping would corrupt ExecStart.
            self.jinja_env: Environment | None = Environment(
                loader=PackageLoader("wasm", "templates/systemd"),
                trim_blocks=True,
                lstrip_blocks=True,
                autoescape=False,  # noqa: S701
            )
        except (ImportError, ValueError, OSError) as exc:
            # A missing template package is not fatal: everything except
            # create_service keeps working.
            self.logger.debug(f"Systemd template environment unavailable: {exc}")
            self.jinja_env = None

    def _exec(self, argv: list[str], *, timeout: int = DEFAULT_TIMEOUT) -> CommandResult:
        """
        Run a command through the shared runner.

        WASM requires root, so nothing here is prefixed with sudo: a manager
        that shells out to sudo hides which identity the change was made under
        and breaks on hosts where sudo is not installed.

        Args:
            argv: Program and arguments.
            timeout: Deadline in seconds.

        Returns:
            The command outcome.
        """
        return self.runner.run(argv, timeout=timeout)

    def is_installed(self) -> bool:
        """
        Check if systemd is available.

        Returns:
            True when systemctl can be executed.
        """
        return self.runner.exists("systemctl")

    def get_version(self) -> str | None:
        """
        Get systemd version.

        Returns:
            The major version as a string, or None when it cannot be read.
        """
        result = self._exec(["systemctl", "--version"])
        if result.success:
            match = re.search(r"systemd (\d+)", result.stdout)
            if match:
                return match.group(1)
        return None

    # Naming ---------------------------------------------------------------

    def _get_service_name(self, name: str) -> str:
        """
        Get the validated service name for new services (no prefix).

        Args:
            name: Base service name, with or without the ``.service`` suffix.

        Returns:
            Service name without prefix or suffix.

        Raises:
            ValidationError: When the name is not a safe unit name.
        """
        candidate = validate_service_name(str(name).removesuffix(".service"))
        return candidate.removeprefix(self.LEGACY_PREFIX) or candidate

    #: Units WASM runs for itself, not for an application.
    OWN_UNITS: ClassVar[frozenset[str]] = frozenset({"wasm-web", "wasm-monitor"})
    #: Prefixes of the units WASM writes for scheduled work.
    OWN_UNIT_PREFIXES: ClassVar[tuple[str, ...]] = ("wasm-cron-", "wasm-backup-")

    @classmethod
    def _is_own_unit_name(cls, name: str) -> bool:
        """
        Report whether a unit name is one of WASM's own, never an application's.

        Args:
            name: Unit name without the ``.service`` suffix.

        Returns:
            True for the console, the monitor and the scheduled-work units.
        """
        return name in cls.OWN_UNITS or name.startswith(cls.OWN_UNIT_PREFIXES)

    def _resolve_service_name(self, name: str) -> str:
        """
        Resolve actual service name, checking both new and legacy formats.

        For backwards compatibility, checks if a legacy (``wasm-*``) unit exists
        and returns that if found. Otherwise returns the new format.

        Args:
            name: Base service name.

        Returns:
            Actual service name (may have legacy prefix if it exists).

        Raises:
            ValidationError: When the name is not a safe unit name.
        """
        given = validate_service_name(str(name).removesuffix(".service"))

        if given.startswith(self.LEGACY_PREFIX):
            # A caller that spells the prefix means that unit. Only fall back to
            # the unprefixed form when it is the one actually installed,
            # otherwise the prefix - a WASM ownership signal - is thrown away.
            # WASM's own units are never an application's: "wasm-web" falling
            # back to an app named "web" would stop that app instead of the console.
            if self._is_own_unit_name(given):
                return given
            stripped = given.removeprefix(self.LEGACY_PREFIX) or given
            if (self.SYSTEMD_DIR / f"{given}.service").exists():
                return given
            if (self.SYSTEMD_DIR / f"{stripped}.service").exists():
                return stripped
            return given

        legacy_name = f"{self.LEGACY_PREFIX}{given}"
        if (self.SYSTEMD_DIR / f"{legacy_name}.service").exists():
            return legacy_name

        return given

    def _get_service_file(self, name: str) -> Path:
        """
        Get the unit file path a new service would be written to.

        Args:
            name: Service name.

        Returns:
            Path to the unit file inside the managed directory.

        Raises:
            ValidationError: When the name is not a safe unit name.
        """
        return self.SYSTEMD_DIR / f"{self._get_service_name(name)}.service"

    def _resolve_service_file(self, name: str) -> Path:
        """
        Resolve unit file path, checking both new and legacy formats.

        Args:
            name: Service name.

        Returns:
            Path to the existing unit file, or the new-format path when none
            exists.

        Raises:
            ValidationError: When the name is not a safe unit name.
        """
        return self.SYSTEMD_DIR / f"{self._resolve_service_name(name)}.service"

    # Ownership ------------------------------------------------------------

    def _stored_services(self) -> list[Service]:
        """
        The rows of the store's services table.

        Returns:
            Every recorded service. Empty when the store cannot be read, which
            only makes the ownership filter stricter.
        """
        try:
            return list(self.store.list_services())
        except (WASMError, sqlite3.Error) as exc:
            self.logger.debug(f"Could not read services from store: {exc}")
            return []

    def _stored_service_names(self) -> set[str]:
        """
        Names of the units the store knows this project created.

        Returns:
            Unit names without the ``.service`` suffix. Empty when the store
            cannot be read, which only makes the filter stricter.
        """
        return {service.name.removesuffix(".service") for service in self._stored_services()}

    def _stored_apps(self) -> list[App]:
        """
        The applications the store records.

        Returns:
            Every application. Empty when the store cannot be read.
        """
        try:
            return list(self.store.list_apps())
        except (WASMError, sqlite3.Error) as exc:
            self.logger.debug(f"Could not read applications from store: {exc}")
            return []

    def _marked_unit_files(self) -> dict[str, bool]:
        """
        Scan the managed directory for unit files that could be WASM's.

        Only regular files are read: a symlink in ``/etc/systemd/system`` is an
        alias or a mask pointing at somebody else's file. A name WASM could not
        have written (an escape, a template ending in ``@``) is skipped, since
        WASM validates every name it creates.

        Returns:
            Unit name (without ``.service``) to whether its file carries
            :data:`WASM_UNIT_MARKER`, for every ``.service`` file with a
            name WASM could have given it.
        """
        found: dict[str, bool] = {}
        try:
            entries = sorted(Path(self.SYSTEMD_DIR).iterdir())
        except OSError as exc:
            self.logger.debug(f"Could not scan {self.SYSTEMD_DIR}: {exc}")
            return found

        for entry in entries:
            if entry.suffix != ".service" or entry.is_symlink() or not entry.is_file():
                continue
            unit = entry.name.removesuffix(".service")
            try:
                validate_service_name(unit)
            except ValidationError:
                continue
            if unit.endswith("@"):
                continue
            found[unit] = self._file_has_marker(entry)
        return found

    @staticmethod
    def _file_has_marker(path: Path) -> bool:
        """
        Report whether a unit file carries the WASM marker.

        Args:
            path: The unit file.

        Returns:
            True when the file can be read and carries the marker.
        """
        try:
            return WASM_UNIT_MARKER in path.read_text(errors="replace")
        except OSError:
            return False

    def app_units(
        self,
        app: App,
        *,
        services: list[Service] | None = None,
        marked: Mapping[str, bool] | None = None,
        listed: Collection[str] = (),
    ) -> list[str]:
        """
        Name the unit(s) an application runs as.

        The one mapping from an application to its units; the log stream, the
        machine tally, ``wasm list`` and the migration all ask here. In order:

        1. The rows of the services table that carry the application's id: a
           monorepo has one per workspace.
        2. For a monorepo without rows, the marked unit files named
           ``<app-name>-<workspace>`` in the managed directory.
        3. The unit named after the application, or the legacy ``wasm-``
           prefixed one when that is the one installed (units from before
           0.14.1): its file is in the managed directory, or systemd lists it
           and knows nothing of the unprefixed name. Docker Compose
           applications are named the same way.

        Args:
            app: The application.
            services: The services table, when the caller has already read it.
            marked: What :meth:`_marked_unit_files` returned, when the caller
                has already scanned the directory.
            listed: Unit names systemd listed, when the caller has asked.

        Returns:
            Unit names without the ``.service`` suffix, primary first. Empty
            for a static application, which has no process.
        """
        # A site of the static type has no process, even when a unit was left
        # behind from a type it had before.
        if app.is_static or app.app_type == "static":
            return []

        rows = services if services is not None else self._stored_services()
        if app.id is not None:
            owned = sorted(
                {row.name.removesuffix(".service") for row in rows if row.app_id == app.id}
            )
            if owned:
                return owned

        base = domain_to_app_name(app.domain)
        if app.app_type == "monorepo":
            files = marked if marked is not None else self._marked_unit_files()
            workspaces = sorted(
                name
                for name, has_marker in files.items()
                if has_marker and name.startswith(f"{base}-")
            )
            if workspaces:
                return workspaces

        legacy = f"{self.LEGACY_PREFIX}{base}"
        directory = Path(self.SYSTEMD_DIR)
        if (directory / f"{legacy}.service").exists():
            return [legacy]
        if legacy in listed and base not in listed and not (directory / f"{base}.service").exists():
            return [legacy]
        return [base]

    def _app_unit_owners(
        self,
        apps: list[App],
        services: list[Service],
        marked: Mapping[str, bool] | None = None,
        listed: Collection[str] = (),
    ) -> dict[str, str]:
        """
        Map every application unit to the domain it serves.

        Args:
            apps: The applications.
            services: The services table.
            marked: The directory scan, when already done.
            listed: Unit names systemd listed, when already asked.

        Returns:
            Unit name to application domain.
        """
        owners: dict[str, str] = {}
        for app in apps:
            for unit in self.app_units(app, services=services, marked=marked, listed=listed):
                owners.setdefault(unit, app.domain)
        return owners

    def _is_managed_dir(self, directory: Path) -> bool:
        """
        Report whether a directory is the one WASM writes units into.

        Args:
            directory: Candidate unit directory.

        Returns:
            True when it is the managed directory, comparing resolved paths so
            a symlinked ``/lib`` does not read as a second location.
        """
        if directory == self.SYSTEMD_DIR:
            return True
        try:
            return directory.resolve() == Path(self.SYSTEMD_DIR).resolve()
        except OSError:
            return False

    def _foreign_unit_dirs(self) -> list[Path]:
        """
        The unit directories that belong to the system, not to WASM.

        Returns:
            Every configured search directory except the managed one.
        """
        return [d for d in self.UNIT_SEARCH_DIRS if not self._is_managed_dir(d)]

    def _fragment_path(self, unit_file: str) -> Path | None:
        """
        Ask systemd where it loads a unit from.

        Args:
            unit_file: Full unit name, including the ``.service`` suffix.

        Returns:
            The path systemd reports, or None when systemd does not know the
            unit or cannot be reached.
        """
        result = self._exec(["systemctl", "show", "-p", "FragmentPath", unit_file])
        if not result.success:
            return None

        for line in result.stdout.splitlines():
            key, separator, value = line.partition("=")
            if separator and key.strip() == "FragmentPath":
                fragment = value.strip()
                return Path(fragment) if fragment else None
        return None

    def _carries_wasm_signal(
        self,
        unit: str,
        path: Path,
        *,
        stored: set[str] | None = None,
        app_owned: Mapping[str, str] | None = None,
        has_marker: bool | None = None,
    ) -> bool:
        """
        Report whether a unit shows any sign of having been created by WASM.

        The cheap signals are checked first, so a single lookup reads the store
        only when the name and the file said nothing.

        Args:
            unit: Unit name without the ``.service`` suffix.
            path: The unit file inside the managed directory.
            stored: The services table's names, when already read.
            app_owned: :meth:`_app_unit_owners`, when already computed.
            has_marker: Whether the file carries the marker, when already read.

        Returns:
            True when the prefix, the store, the file marker or an application
            in the store identifies it.
        """
        if unit.startswith(self.SERVICE_PREFIX):
            return True
        if unit in (stored if stored is not None else self._stored_service_names()):
            return True
        if has_marker if has_marker is not None else self._file_has_marker(path):
            return True
        if app_owned is None:
            app_owned = self._app_unit_owners(self._stored_apps(), self._stored_services())
        return unit in app_owned

    def _shadowing_file(self, unit: str) -> Path | None:
        """
        Find a same-named unit file in a directory the system owns.

        Args:
            unit: Unit name without the ``.service`` suffix.

        Returns:
            The first such file, or None.
        """
        return next(
            (
                d / f"{unit}.service"
                for d in self._foreign_unit_dirs()
                if (d / f"{unit}.service").exists()
            ),
            None,
        )

    def _refusal(
        self,
        unit: str,
        path: Path,
        *,
        fragment: Path | None,
        shadowed: Path | None,
        signal: Callable[[], bool],
    ) -> str:
        """
        Apply the ownership rule, and say why a unit is not WASM's.

        The rule itself, shared by :meth:`inspect_unit` (one unit, with
        systemd's FragmentPath) and :meth:`managed_units` (every unit, from the
        directory scan), so the listing and the guard cannot disagree.

        Args:
            unit: Unit name without the ``.service`` suffix.
            path: Its file inside the managed directory.
            fragment: Where systemd loads it from, when that was asked.
            shadowed: A same-named file in a system directory, if any.
            signal: Evaluates the WASM signals; only called when needed.

        Returns:
            Why the unit is not managed, or an empty string when it is.
        """
        if fragment is not None and not self._is_managed_dir(fragment.parent):
            return f"systemd loads it from {fragment}, outside {self.SYSTEMD_DIR}"

        if shadowed is not None:
            return (
                f"a unit with the same name is shipped by the system at {shadowed}; "
                "a file in the managed directory would eclipse it"
            )

        # Ownership is deliberately independent of existence: a unit systemd has
        # loaded but whose file this process cannot see is still ours when
        # nothing points at another owner. Callers ask about existence through
        # ``exists``, which is what decides whether an operation has a target.
        if not signal():
            return (
                f"{path} was not generated by WASM"
                if path.exists()
                else f"nothing identifies {unit} as a unit WASM created"
            )
        return ""

    def inspect_unit(self, name: str) -> UnitOwnership:
        """
        Decide whether a unit belongs to WASM, and why.

        Args:
            name: Unit name, with or without the ``.service`` suffix.

        Returns:
            The ownership verdict, including the reason when it is negative.

        Raises:
            ValidationError: When the name is not a safe unit name.
        """
        unit = self._resolve_service_name(name)
        path = self.SYSTEMD_DIR / f"{unit}.service"
        fragment = self._fragment_path(f"{unit}.service")
        shadowed = self._shadowing_file(unit)
        exists = path.exists() or shadowed is not None or fragment is not None

        reason = self._refusal(
            unit,
            path,
            fragment=fragment,
            shadowed=shadowed,
            signal=lambda: self._carries_wasm_signal(unit, path),
        )
        return UnitOwnership(
            unit=unit,
            path=path,
            fragment_path=fragment,
            exists=exists,
            managed=not reason,
            reason=reason,
        )

    def is_managed(self, name: str) -> bool:
        """
        Report whether a unit belongs to WASM.

        Args:
            name: Unit name, with or without the ``.service`` suffix.

        Returns:
            True when the unit was created by this project and still lives
            where this project puts its units. An unusable name is not managed
            rather than an error, so listings can call this on anything.
        """
        try:
            return self.inspect_unit(name).managed
        except WASMError as exc:
            self.logger.debug(f"Not a WASM unit name: {name!r}: {exc}")
            return False

    def _require_managed(
        self, name: str, *, operation: str, missing_ok: bool = False
    ) -> UnitOwnership:
        """
        Resolve a unit and refuse to operate on it unless WASM owns it.

        Args:
            name: Unit name, with or without the ``.service`` suffix.
            operation: Verb used in the error message.
            missing_ok: Return the verdict instead of raising when the unit does
                not exist anywhere. Used by the idempotent operations (stop,
                disable, delete, status), so teardown does not depend on knowing
                whether a unit was ever created.

        Returns:
            The ownership verdict. It is only returned with ``exists`` False
            when ``missing_ok`` is set.

        Raises:
            ServiceError: When the unit is not WASM's, or does not exist and
                ``missing_ok`` is False.
            ValidationError: When the name is not a safe unit name.
        """
        info = self.inspect_unit(name)

        # Existence is checked first: a name nobody has installed cannot belong
        # to anyone, and the caller decides whether that is an error.
        if not info.exists:
            if missing_ok:
                return info
            raise ServiceError(
                f"Unknown service: {info.unit}",
                details=(
                    f"There is no unit file at {info.path}. "
                    "Run 'wasm service list' to see the units WASM manages."
                ),
            )

        if info.managed:
            return info

        raise ServiceError(
            f"Refusing to {operation} a unit WASM does not manage: {info.unit}",
            details=(
                f"{info.reason}. Use systemctl directly if that is really what you want to do."
            ),
        )

    # State ----------------------------------------------------------------

    def daemon_reload(self) -> bool:
        """
        Reload systemd daemon.

        Returns:
            True if successful.
        """
        result = self._exec(["systemctl", "daemon-reload"])
        if not result.success:
            self.logger.debug(f"daemon-reload failed: {result.stderr}")
        return result.success

    def service_exists(self, name: str) -> bool:
        """
        Check if a unit file exists in the managed directory.

        Args:
            name: Service name.

        Returns:
            True if the unit file exists, in either the new or legacy format.

        Raises:
            ValidationError: When the name is not a safe unit name.
        """
        return self._resolve_service_file(name).exists()

    @staticmethod
    def state_is_running(raw_state: str) -> bool:
        """
        Decide whether a systemd active-state string means "running".

        ``systemctl is-active`` and the ACTIVE column ``systemctl
        list-units`` prints share one vocabulary (``active``, ``inactive``,
        ``failed``, ``activating``, ``deactivating``, ``reloading``), and
        exactly one value of it means the unit is up. This is the one place
        that decides that, so :meth:`get_status` (which the web API reads)
        and a caller of :meth:`list_services` (``wasm service list``) cannot
        end up answering "is it running" two different ways.

        Args:
            raw_state: The raw string systemd reported.

        Returns:
            True when the state means the unit is running.
        """
        return raw_state.strip() == "active"

    @staticmethod
    def _parse_list_units(stdout: str) -> dict[str, dict[str, str]]:
        """
        Read the rows of ``systemctl list-units --plain``.

        Names are taken exactly as systemd writes them, escapes included: this
        is systemd's own output, not user input, and nothing here builds a
        path from it.

        Args:
            stdout: What systemctl printed.

        Returns:
            Unit name (without ``.service``) to its ``load``, ``active`` and
            ``sub`` columns, in the order systemd printed them.
        """
        rows: dict[str, dict[str, str]] = {}
        for line in stdout.splitlines():
            parts = line.split()
            if len(parts) < 4 or not parts[0].endswith(".service"):
                continue
            name = parts[0].removesuffix(".service")
            rows[name] = {"name": name, "load": parts[1], "active": parts[2], "sub": parts[3]}
        return rows

    def _list_units(self, patterns: list[str]) -> dict[str, dict[str, str]] | None:
        """
        Run one ``systemctl list-units`` and parse it.

        Args:
            patterns: Unit names or globs to ask about.

        Returns:
            The parsed rows, or None when systemctl failed.
        """
        result = self._exec([*LIST_UNITS_ARGV, *patterns])
        if not result.success:
            self.logger.debug(f"systemctl list-units failed: {result.stderr.strip()}")
            return None
        return self._parse_list_units(result.stdout)

    def managed_units(
        self, *, listing: Mapping[str, Mapping[str, str]] | None = None
    ) -> list[ManagedUnit]:
        """
        List the units WASM manages: the one definition every view reads.

        Candidates are the ``.service`` files in the managed directory that
        carry a WASM signal, the services table, the unit(s) of every
        application in the store (:meth:`app_units`) and the ``wasm-*`` units
        systemd has loaded. Each is judged by the rule :meth:`inspect_unit`
        applies, from the directory scan instead of a ``systemctl show`` per
        unit: the console's top bar calls this every five seconds.

        Args:
            listing: Rows of a ``systemctl list-units`` already run, such as the
                whole-machine one :meth:`list_services` makes; None runs one
                scoped to the candidates.

        Returns:
            One entry per unit, sorted by name. A unit whose file exists but
            that systemd has not loaded (stopped and disabled) is included as
            ``not-loaded``/``inactive``/``dead``; an application unit that
            exists nowhere is not.

        Raises:
            ServiceError: When systemctl cannot list units at all, so that a
                caller can tell "none" from "could not ask".
        """
        services = self._stored_services()
        stored = {service.name.removesuffix(".service") for service in services}
        marked = self._marked_unit_files()
        apps = self._stored_apps()

        candidates = {name for name, has_marker in marked.items() if has_marker} | {
            name for name in marked if name.startswith(self.SERVICE_PREFIX)
        }
        candidates |= stored | set(self._app_unit_owners(apps, services, marked))

        rows: Mapping[str, Mapping[str, str]] | None = listing
        if rows is None:
            # Full unit names, not bare ones: list-units matches its arguments
            # as globs against "name.service", so "shop-example-com" alone
            # matches nothing. Names that are not safe globs never get here:
            # every candidate passed validate_service_name or came from the
            # store, which only records validated names.
            patterns = [f"{self.SERVICE_PREFIX}*"]
            patterns += [f"{name}.service" for name in sorted(candidates) if _is_plain(name)]
            rows = self._list_units(patterns)
            if rows is None:
                raise ServiceError(
                    "Could not list systemd units",
                    details="Check that systemd is running: 'systemctl list-units' failed.",
                )

        # Asked again with what systemd listed: a legacy unit whose file this
        # process cannot see is still recognised as its application's.
        owners = self._app_unit_owners(apps, services, marked, listed=set(rows))
        candidates |= set(owners)
        candidates |= {name for name in rows if name.startswith(self.SERVICE_PREFIX)}

        units: list[ManagedUnit] = []
        for name in sorted(candidates):
            path = Path(self.SYSTEMD_DIR) / f"{name}.service"
            row = rows.get(name)
            on_disk = name in marked
            loaded = row is not None and row.get("load") != "not-found"
            if not on_disk and not loaded:
                continue
            reason = self._refusal(
                name,
                path,
                fragment=None,
                shadowed=self._shadowing_file(name),
                signal=partial(
                    self._carries_wasm_signal,
                    name,
                    path,
                    stored=stored,
                    app_owned=owners,
                    has_marker=marked.get(name, False),
                ),
            )
            if reason:
                continue
            units.append(
                ManagedUnit(
                    name=name,
                    load=row["load"] if row is not None else "not-loaded",
                    active=row["active"] if row is not None else "inactive",
                    sub=row["sub"] if row is not None else "dead",
                    app=owners.get(name),
                )
            )
        return units

    def list_services(self, all_services: bool = False) -> list[dict[str, Any]]:
        """
        List WASM-managed services, or every service on the machine.

        The managed listing is :meth:`managed_units`. Asking systemd for ``*``
        and filtering afterwards used to return ssh, cron and dbus, which then
        showed up as deletable in ``wasm service list``.

        Args:
            all_services: List every unit on the system as well, each flagged
                ``managed``. Opt-in, for diagnostics only. Foreign units are
                described from the one listing, never validated or probed one
                by one: a name systemd escaped (``\\x2d``) is still a unit.

        Returns:
            One dictionary per unit with ``name``, ``load``, ``active``,
            ``sub``, ``managed`` and ``app`` (the domain it serves, or None).
            Empty when systemd cannot be reached.
        """
        if not all_services:
            try:
                return [unit.as_dict() for unit in self.managed_units()]
            except ServiceError as exc:
                self.logger.debug(str(exc))
                return []

        listing = self._list_units(["*"])
        if listing is None:
            return []
        managed = {unit.name: unit for unit in self.managed_units(listing=listing)}
        rows: list[dict[str, Any]] = [unit.as_dict() for unit in managed.values()]
        rows += [
            {**row, "managed": False, "app": None}
            for name, row in listing.items()
            if name not in managed
        ]
        return sorted(rows, key=lambda row: str(row["name"]))

    def describe_units(self, names: list[str]) -> dict[str, dict[str, str]]:
        """
        Read systemd's properties for several units in one call.

        The Services page shows the PID, memory, uptime and boot setting of
        every unit WASM manages. Asking with three ``systemctl`` calls per unit,
        the way :meth:`get_status` does for one, is dozens of processes per page
        load; ``systemctl show`` answers for all of them at once.

        Args:
            names: Unit names without the ``.service`` suffix, as systemd or
                :meth:`managed_units` wrote them.

        Returns:
            Unit name to its :data:`DESCRIBE_PROPERTIES`. A unit systemd did
            not answer for is missing.
        """
        if not names:
            return {}
        result = self._exec(
            [
                "systemctl",
                "show",
                "--no-pager",
                "-p",
                ",".join(DESCRIBE_PROPERTIES),
                "--",
                *(f"{name}.service" for name in names),
            ]
        )
        if not result.success:
            self.logger.debug(f"systemctl show failed: {result.stderr.strip()}")
            return {}

        described: dict[str, dict[str, str]] = {}
        for block in result.stdout.split("\n\n"):
            properties: dict[str, str] = {}
            for line in block.splitlines():
                key, separator, value = line.partition("=")
                if separator:
                    properties[key.strip()] = value
            unit_id = properties.get("Id", "")
            if unit_id:
                described[unit_id.removesuffix(".service")] = properties
        return described

    @staticmethod
    def status_from_properties(
        name: str, properties: Mapping[str, str], *, managed: bool, exists: bool = True
    ) -> dict[str, Any]:
        """
        Shape systemd's properties the way :meth:`get_status` answers.

        Args:
            name: Unit name without the ``.service`` suffix.
            properties: From :meth:`describe_units`, or the ``active``/``sub``
                columns of a listing under ``ActiveState``/``SubState``.
            managed: Whether WASM manages the unit.
            exists: Whether a unit file for it exists.

        Returns:
            The same keys :meth:`get_status` returns.
        """
        return {
            "name": name,
            "exists": exists,
            "active": ServiceManager.state_is_running(properties.get("ActiveState", "")),
            "enabled": properties.get("UnitFileState", "").strip() == "enabled",
            "pid": properties.get("MainPID", ""),
            "memory": properties.get("MemoryCurrent", ""),
            "uptime": properties.get("ActiveEnterTimestamp", ""),
            "active_state": properties.get("ActiveState", ""),
            "sub_state": properties.get("SubState", ""),
            "restarts": properties.get("NRestarts", "0"),
            "result": properties.get("Result", ""),
            "managed": managed,
        }

    def list_statuses(self, all_services: bool = False) -> list[dict[str, Any]]:
        """
        Describe the units the Services page lists, each like :meth:`get_status`.

        Managed units are described with one ``systemctl show`` for all of
        them. With ``all_services``, a foreign unit is described from the
        listing alone (its state columns; no PID, memory or boot setting): it is
        shown, never acted on, and one odd unit can no longer fail the list.

        Args:
            all_services: Include every unit on the machine.

        Returns:
            One status mapping per unit, plus ``app``, sorted by name.
        """
        rows = self.list_services(all_services=all_services)
        described = self.describe_units([str(row["name"]) for row in rows if row["managed"]])

        statuses: list[dict[str, Any]] = []
        for row in rows:
            name = str(row["name"])
            properties = described.get(name) if row["managed"] else None
            if properties is None:
                properties = {"ActiveState": str(row["active"]), "SubState": str(row["sub"])}
            status = self.status_from_properties(name, properties, managed=bool(row["managed"]))
            status["app"] = row.get("app")
            statuses.append(status)
        return statuses

    def get_status(self, name: str, *, require_managed: bool = True) -> dict:
        """
        Get service status.

        Args:
            name: Service name.
            require_managed: Refuse a unit WASM does not own, exactly like
                every other operation here. False is for read-only listings
                across every unit on the host (``all_services=True``), where
                the point is precisely to describe a foreign unit rather than
                refuse it.

        Returns:
            Dictionary with status information. A unit that does not exist is
            reported as absent rather than refused, because callers use this to
            decide whether they still have to create it.

        Raises:
            ServiceError: When ``require_managed`` is true and the unit
                exists but WASM does not manage it.
            ValidationError: When the name is not a safe unit name.
        """
        info = (
            self._require_managed(name, operation="inspect", missing_ok=True)
            if require_managed
            else self.inspect_unit(name)
        )

        # A unit this process cannot see a file for is still queried: the three
        # probes below only read, systemd is the authority on what is running,
        # and a status call that lies about a live service is how a broken
        # deployment gets reported as healthy. ``exists`` reports our own view.
        is_active = self.state_is_running(
            self._exec(["systemctl", "is-active", info.unit_file]).stdout
        )
        is_enabled = (
            self._exec(["systemctl", "is-enabled", info.unit_file]).stdout.strip() == "enabled"
        )

        result = self._exec(["systemctl", "show", info.unit_file, "--no-pager"])
        details: dict[str, str] = {}
        if result.success:
            for line in result.stdout.split("\n"):
                key, separator, value = line.partition("=")
                if separator:
                    details[key] = value

        # "active" alone cannot tell a healthy service from one systemd is
        # restarting every few seconds: a crash loop spends most of its time in
        # activating/auto-restart and reports active in between. active_state,
        # sub_state, restarts and result are what distinguishes the two.
        # "managed" is reported independently of require_managed: a caller that
        # skipped the guard to describe a foreign unit still needs to say so.
        status = self.status_from_properties(
            info.unit, details, managed=info.managed, exists=info.exists
        )
        status["active"] = is_active
        status["enabled"] = is_enabled
        return status

    # Creation -------------------------------------------------------------

    def _write_unit_atomically(self, path: Path, content: str) -> None:
        """
        Write a unit file so that no reader ever sees a partial one.

        This used to open its own ``mkstemp``, fsync it and ``os.replace`` it
        into position. :meth:`~wasm.core.fs.FileSystem.write_text` already does
        exactly that - sibling temporary, fsync, atomic rename, mode applied at
        creation - so the copy is gone: two implementations of an atomic write
        means one of them eventually stops being atomic, and only one of them
        can be turned off by ``--dry-run``.

        Args:
            path: Final unit file path.
            content: Complete unit file body.

        Raises:
            ServiceError: When the file cannot be written or renamed.
        """
        try:
            self.fs.write_text(path, content, mode=UNIT_FILE_MODE)
        except OSError as exc:
            raise ServiceError(
                f"Failed to write unit file: {path}",
                details=(
                    f"{exc}. The previous unit file, if any, is untouched. "
                    f"Check that {path.parent} exists and is writable by root."
                ),
            ) from exc

    def _render_unit(self, template: str, context: Mapping[str, Any]) -> str:
        """
        Render a unit file from a packaged template.

        Args:
            template: Template name without the ``.service.j2`` suffix.
            context: Variables handed to the template.

        Returns:
            The rendered unit file.

        Raises:
            ServiceError: When the template environment is unavailable.
            TemplateError: If the unit template is missing or invalid.
        """
        if not self.jinja_env:
            raise ServiceError(
                "Template environment not initialized",
                details="Reinstall wasm so that the packaged systemd templates are available.",
            )

        try:
            template_obj = self.jinja_env.get_template(f"{template}.service.j2")
            return template_obj.render(**context)
        except TemplateNotFound as exc:
            raise TemplateError(f"Template not found: {template}.service.j2") from exc
        except JinjaTemplateError as exc:
            raise TemplateError(f"Template rendering failed: {exc}") from exc

    def create_service(
        self,
        name: str,
        command: str = "",
        working_directory: str = "",
        user: str | None = None,
        group: str | None = None,
        environment: dict[str, str] | None = None,
        description: str | None = None,
        template: str = "app",
        limits: ResourceLimits | None = None,
        environment_file: str | None = None,
        **kwargs: Any,
    ) -> None:
        """
        Create a new systemd service.

        This is the mandatory step for every caller that installs a unit, so it
        is where the name and the environment are validated: the deployers and
        the web API used to reach the templates without passing through either
        check.

        Args:
            name: Service name.
            command: Command to execute (not required for docker-compose template).
            working_directory: Working directory for the service.
            user: User to run service as.
            group: Group to run service as.
            environment: Environment variables written inline. Only what is
                not secret: every local user can read them.
            description: Service description.
            template: Template name.
            limits: Memory, CPU and task limits, validated here. None for none.
            environment_file: Absolute path of a 0600 file the unit loads the
                rest of its environment from, or None for none. A missing file
                is not an error: the unit references it with ``-``.
            **kwargs: Extra context variables passed to the template.

        Raises:
            ServiceError: If the unit already exists, would eclipse a unit
                shipped by the distribution, or cannot be written.
            TemplateError: If the unit template is missing or invalid.
            ValidationError: If the name, the environment or a directive value
                is unsafe.
        """
        unit = self._get_service_name(name)
        env = validate_environment(environment or {})

        info = self.inspect_unit(unit)
        if info.exists:
            if info.managed:
                raise ServiceError(
                    f"Service already exists: {info.unit}",
                    details=f"Delete it first, or edit {info.path}.",
                )
            raise ServiceError(
                f"Refusing to create a unit that is not WASM's to create: {info.unit}",
                details=f"{info.reason}. Choose a different service name.",
            )

        ctx: dict[str, Any] = {
            "name": unit,
            "description": validate_unit_value(
                description or f"WASM managed service: {unit}", field="Description"
            ),
            "command": validate_unit_value(command, field="ExecStart"),
            "working_directory": validate_unit_value(working_directory, field="WorkingDirectory"),
            "user": validate_unit_value(user or self.config.service_user, field="User"),
            "group": validate_unit_value(group or self.config.service_group, field="Group"),
            "environment": env,
            "environment_file": self._validated_environment_file(environment_file),
            "resource_limits": (limits or ResourceLimits()).validated().directives(),
        }
        ctx.update(kwargs)

        unit_file = self._get_service_file(unit)
        content = self._render_unit(template, ctx)
        self._write_unit_atomically(unit_file, content)
        self.daemon_reload()

        try:
            self.store.create_service(
                Service(
                    name=unit,
                    unit_file=str(unit_file),
                    command=command,
                    working_directory=working_directory,
                    user=str(ctx["user"]),
                    group=str(ctx["group"]),
                    environment=env,
                    status="inactive",
                    enabled=False,
                )
            )
        except (WASMError, sqlite3.Error) as exc:
            self.logger.debug(f"Could not register service in store: {exc}")

        self.logger.debug(f"Created service: {unit}")

    @staticmethod
    def _validated_environment_file(path: str | None) -> str | None:
        """
        Check an ``EnvironmentFile=`` path before it is written into a unit.

        Args:
            path: The path, or None.

        Returns:
            The path unchanged, or None.

        Raises:
            ValidationError: When the path is relative, or carries a character
                that would end the directive.
        """
        if path is None:
            return None
        value = validate_unit_value(path, field="EnvironmentFile")
        if not os.path.isabs(value):
            raise ValidationError(
                f"EnvironmentFile must be an absolute path, got {value!r}",
                details="systemd refuses a relative EnvironmentFile= and would not start the unit.",
            )
        return value

    def create_from_unit(self, name: str, content: str) -> None:
        """
        Create a unit from a complete file the caller wrote by hand.

        This exists because the panel offers an advanced mode where an operator
        supplies the whole unit. That mode used to write the file directly,
        which meant it could put any content at any unit path as root while the
        ownership guard on this class looked on. Routing it here applies the
        same rules as every other write.

        Args:
            name: Service name.
            content: Complete unit file body.

        Raises:
            ServiceError: When a unit of that name already exists anywhere
                systemd looks, when the body lacks the WASM marker, or when the
                write fails.
            ValidationError: When the name is not a safe unit name.
        """
        unit = self._get_service_name(name)
        self._check_unit_body(unit, content)

        info = self.inspect_unit(unit)
        if info.exists:
            if info.managed:
                raise ServiceError(
                    f"Service already exists: {info.unit}",
                    details=f"Delete it first, or edit {info.path}.",
                )
            raise ServiceError(
                f"Refusing to create a unit that is not WASM's to create: {info.unit}",
                details=f"{info.reason}. Choose a different service name.",
            )

        self._write_unit_atomically(self._get_service_file(unit), content)
        self.daemon_reload()

    def install_unit(self, name: str, template: str, context: Mapping[str, Any]) -> Path:
        """
        Write one of WASM's own units under exactly the name given.

        :meth:`create_service` names an application's unit and drops the legacy
        ``wasm-`` prefix, and refuses a unit that already exists. WASM's own
        units (the console's ``wasm-web``) keep the prefix, because it is what
        marks them as WASM's, and are rewritten in place when their options
        change. The ownership rule is the same one every other operation
        applies: systemd must load the unit from the managed directory, it must
        not eclipse a unit the system ships, and a file already there must be
        WASM's.

        Args:
            name: Unit name, with or without the ``.service`` suffix. Kept as
                given, prefix included.
            template: Template name without the ``.service.j2`` suffix.
            context: Variables handed to the template. Values interpolated into
                a directive are the caller's to validate.

        Returns:
            The unit file that was written.

        Raises:
            ServiceError: When the unit is not WASM's to write, the rendered
                body lacks the marker, or the file cannot be written.
            TemplateError: If the template is missing or invalid.
            ValidationError: When the name is not a safe unit name.
        """
        unit = validate_service_name(str(name).removesuffix(".service"))
        path = self.SYSTEMD_DIR / f"{unit}.service"
        content = self._render_unit(template, context)
        self._check_unit_body(unit, content)

        reason = self._refusal(
            unit,
            path,
            fragment=self._fragment_path(f"{unit}.service"),
            shadowed=self._shadowing_file(unit),
            # A new file carries the marker checked above; an existing one has
            # to show it is WASM's before it is replaced.
            signal=lambda: not path.exists() or self._carries_wasm_signal(unit, path),
        )
        if reason:
            raise ServiceError(
                f"Refusing to write a unit WASM does not manage: {unit}",
                details=f"{reason}. Remove or rename that unit first.",
            )

        self._write_unit_atomically(path, content)
        self.daemon_reload()
        return path

    def _check_unit_body(self, unit: str, content: str) -> None:
        """
        Reject a unit body that WASM must not write.

        Args:
            unit: Unit name, for the error message.
            content: Candidate unit body.

        Raises:
            ServiceError: When the marker is missing or the body is not text.
        """
        if WASM_UNIT_MARKER not in content:
            raise ServiceError(
                f"Refusing to write a unit without the WASM marker: {unit}",
                details=(
                    f"Keep the '# {WASM_UNIT_MARKER}' comment in the file. Without it "
                    "WASM stops recognising the unit as its own and refuses to manage it."
                ),
            )
        if "\x00" in content:
            raise ServiceError(
                f"Refusing to write a unit containing a NUL byte: {unit}",
                details="A unit file is text; a NUL byte would truncate it.",
            )

    def update_config(self, name: str, content: str) -> str:
        """
        Replace the body of a unit WASM manages.

        Args:
            name: Service name.
            content: Complete replacement unit file.

        Returns:
            The previous unit body, so the caller can revert by passing it back
            to this method.

        Raises:
            ServiceError: When the unit is not WASM's, cannot be read, or the
                new body would drop the marker that identifies it as ours.
            ValidationError: When the name is not a safe unit name.
        """
        info = self._require_managed(name, operation="rewrite")

        if WASM_UNIT_MARKER not in content:
            raise ServiceError(
                f"Refusing to write a unit without the WASM marker: {info.unit}",
                details=(
                    f"Keep the '# {WASM_UNIT_MARKER}' comment in the file. Without it "
                    "WASM stops recognising the unit as its own and refuses to manage it."
                ),
            )

        if "\x00" in content:
            raise ServiceError(
                f"Refusing to write a unit containing a NUL byte: {info.unit}",
                details="A unit file is text; a NUL byte would truncate it.",
            )

        try:
            previous = info.path.read_text()
        except OSError as exc:
            raise ServiceError(
                f"Could not read the current unit file: {info.path}",
                details=str(exc),
            ) from exc

        self._write_unit_atomically(info.path, content)
        self.daemon_reload()
        return previous

    def set_resource_limits(self, name: str, limits: ResourceLimits) -> str:
        """
        Give a unit WASM manages exactly these limits.

        The chokepoint for limits: they are validated here, whoever asks, and
        written through :meth:`update_config`, which keeps the ownership rules
        and reloads systemd. The running process keeps the limits it started
        with until it is restarted.

        Args:
            name: Service name.
            limits: The limits the unit must have.

        Returns:
            The previous unit body, to put back with :meth:`update_config`.

        Raises:
            ValidationError: A limit is out of range.
            ServiceError: The unit is not WASM's, or cannot be read or written.
        """
        limits.validated()
        info = self._require_managed(name, operation="limit")
        try:
            body = info.path.read_text()
        except OSError as exc:
            raise ServiceError(
                f"Could not read the current unit file: {info.path}", details=str(exc)
            ) from exc
        return self.update_config(name, with_resource_limits(body, limits))

    def delete_service(self, name: str) -> None:
        """
        Delete a service.

        Args:
            name: Service name.

        Raises:
            ServiceError: If the unit is not managed by WASM, or if the unit
                file cannot be removed.
            ValidationError: When the name is not a safe unit name.
        """
        info = self._require_managed(name, operation="delete", missing_ok=True)

        if info.exists:
            self._exec(["systemctl", "stop", info.unit_file], timeout=_LIFECYCLE_TIMEOUT)
            self._exec(["systemctl", "disable", info.unit_file])

            try:
                self.fs.remove(info.path, missing_ok=True)
            except OSError as exc:
                raise ServiceError(
                    f"Failed to delete service: {info.unit}",
                    details=str(exc),
                ) from exc

            self.daemon_reload()

        try:
            self.store.delete_service(info.unit)
        except (WASMError, sqlite3.Error) as exc:
            self.logger.debug(f"Could not remove service from store: {exc}")

        self.logger.debug(f"Deleted service: {info.unit}")

    # Lifecycle ------------------------------------------------------------

    def _reset_start_limit(self, info: UnitOwnership) -> None:
        """
        Clear a unit's failed state and start-limit counter before a deliberate start.

        App units carry ``StartLimitBurst=``, so a crash loop ends in
        ``failed`` instead of restarting forever. systemd applies that limit to
        every start, manual ones included: after a release crash-looped in the
        health gate, the rollback's restart of the previous release was refused
        with "start request repeated too quickly". An operator's or WASM's own
        start is a decision, not a loop, so it is always tried. The result is
        ignored: on a unit that is not failed this does nothing.

        Args:
            info: The unit, already checked to be WASM's.
        """
        self._exec(["systemctl", "reset-failed", info.unit_file])

    def start(self, name: str) -> None:
        """
        Start a service.

        Args:
            name: Service name.

        Raises:
            ServiceError: If the unit is not WASM's, does not exist, or systemd
                refuses to start it.
            ValidationError: When the name is not a safe unit name.
        """
        info = self._require_managed(name, operation="start")
        self._reset_start_limit(info)
        result = self._exec(["systemctl", "start", info.unit_file], timeout=_LIFECYCLE_TIMEOUT)

        if not result.success:
            raise ServiceError(
                f"Failed to start service: {info.unit}",
                details=result.stderr,
            )

        self._update_stored_status(info.unit, "active")

    def stop(self, name: str) -> bool:
        """
        Stop a service.

        Args:
            name: Service name.

        Returns:
            True when the unit is stopped afterwards, including when there was
            nothing to stop. Teardown paths call this before knowing whether
            the unit was ever created.

        Raises:
            ServiceError: If the unit exists but is not WASM's.
            ValidationError: When the name is not a safe unit name.
        """
        info = self._require_managed(name, operation="stop", missing_ok=True)
        if not info.exists:
            self.logger.debug(f"Nothing to stop: {info.unit} does not exist")
            return True

        result = self._exec(["systemctl", "stop", info.unit_file], timeout=_LIFECYCLE_TIMEOUT)
        self._update_stored_status(info.unit, "inactive")
        return result.success

    def restart(self, name: str) -> None:
        """
        Restart a service.

        Args:
            name: Service name.

        Raises:
            ServiceError: If the unit is not WASM's, does not exist, or systemd
                refuses to restart it.
            ValidationError: When the name is not a safe unit name.
        """
        info = self._require_managed(name, operation="restart")
        self._reset_start_limit(info)
        result = self._exec(["systemctl", "restart", info.unit_file], timeout=_LIFECYCLE_TIMEOUT)

        if not result.success:
            raise ServiceError(
                f"Failed to restart service: {info.unit}",
                details=result.stderr,
            )

        self._update_stored_status(info.unit, "active")

    def enable(self, name: str) -> bool:
        """
        Enable a service to start on boot.

        Args:
            name: Service name.

        Returns:
            True if systemd accepted the change.

        Raises:
            ServiceError: If the unit is not WASM's or does not exist.
            ValidationError: When the name is not a safe unit name.
        """
        info = self._require_managed(name, operation="enable")
        result = self._exec(["systemctl", "enable", info.unit_file])

        self._set_stored_enabled(info.unit, True)
        return result.success

    def disable(self, name: str) -> bool:
        """
        Disable a service from starting on boot.

        Args:
            name: Service name.

        Returns:
            True when the unit no longer starts on boot, including when it does
            not exist.

        Raises:
            ServiceError: If the unit exists but is not WASM's.
            ValidationError: When the name is not a safe unit name.
        """
        info = self._require_managed(name, operation="disable", missing_ok=True)
        if not info.exists:
            self.logger.debug(f"Nothing to disable: {info.unit} does not exist")
            return True

        result = self._exec(["systemctl", "disable", info.unit_file])

        self._set_stored_enabled(info.unit, False)
        return result.success

    def _update_stored_status(self, service_name: str, status: str) -> None:
        """
        Record a status change in the store, tolerating a missing record.

        Args:
            service_name: Resolved unit name.
            status: New status value.
        """
        try:
            self.store.update_service_status(service_name, status)
        except (WASMError, sqlite3.Error) as exc:
            self.logger.debug(f"Could not update service status in store: {exc}")

    def _set_stored_enabled(self, service_name: str, enabled: bool) -> None:
        """
        Record the enabled flag in the store, tolerating a missing record.

        Args:
            service_name: Resolved unit name.
            enabled: Whether the unit starts on boot.
        """
        try:
            svc = self.store.get_service(service_name)
            if svc:
                svc.enabled = enabled
                self.store.update_service(svc)
        except (WASMError, sqlite3.Error) as exc:
            self.logger.debug(f"Could not update service in store: {exc}")

    # Logs -----------------------------------------------------------------

    @staticmethod
    def _line_count(lines: int) -> str:
        """
        Normalise the number of journal lines to ask for.

        Args:
            lines: Requested line count.

        Returns:
            A positive integer as a string, ready for argv.

        Raises:
            ServiceError: When the value is not a number.
        """
        try:
            return str(max(1, int(lines)))
        except (TypeError, ValueError) as exc:
            raise ServiceError(
                f"Invalid number of log lines: {lines!r}",
                details="Pass a positive integer.",
            ) from exc

    def logs(self, name: str, lines: int = 50) -> str:
        """
        Get service logs.

        Args:
            name: Service name.
            lines: Number of lines to return.

        Returns:
            Log output, or journalctl's error output when it failed.

        Raises:
            ServiceError: If the unit is not WASM's or does not exist.
            ValidationError: When the name is not a safe unit name.
        """
        info = self._require_managed(name, operation="read the logs of")

        result = self._exec(
            ["journalctl", "-u", info.unit_file, "-n", self._line_count(lines), "--no-pager"]
        )
        return result.stdout if result.success else result.stderr

    def follow_logs(
        self,
        name: str,
        on_line: Callable[[str], None],
        lines: int = 50,
        timeout: int = _FOLLOW_TIMEOUT,
    ) -> None:
        """
        Follow service logs, delivering each line as it appears.

        ``wasm service logs --follow`` used to call :mod:`subprocess` directly,
        which is the one execution path the runner cannot enforce a deadline,
        a dry run or an audit record on.

        Args:
            name: Service name.
            on_line: Called once per line, without the trailing newline.
            lines: Number of past lines to replay before following.
            timeout: Deadline in seconds for the whole follow.

        Raises:
            ServiceError: If the unit is not WASM's or does not exist.
            ValidationError: When the name is not a safe unit name.
        """
        info = self._require_managed(name, operation="read the logs of")

        self.runner.stream(
            ["journalctl", "-u", info.unit_file, "-n", self._line_count(lines), "-f"],
            on_line=on_line,
            timeout=timeout,
        )

    def get_service_config(self, name: str) -> str | None:
        """
        Get service configuration content.

        Args:
            name: Service name.

        Returns:
            Unit file content, or None when WASM manages no such unit.

        Raises:
            ServiceError: If the unit exists but is not WASM's.
            ValidationError: When the name is not a safe unit name.
        """
        info = self._require_managed(name, operation="read", missing_ok=True)
        if not info.exists:
            return None

        try:
            return info.path.read_text()
        except OSError as exc:
            self.logger.debug(f"Could not read unit file {info.path}: {exc}")
            return None

    def verify_unit(self, content: str) -> tuple[bool, str]:
        """
        Check a candidate unit file with systemd-analyze, without installing it.

        Used by the unit editor to catch a mistake before it ever reaches a
        unit WASM or systemd has to reload. The candidate never touches the
        managed directory: it is staged into a private scratch directory,
        the same containment ``WebServerBackend.validate_config`` uses for
        an nginx or apache snippet, and removed once the check is done,
        success or failure alike.

        Args:
            content: Candidate unit file content, verbatim.

        Returns:
            Whether it verified cleanly, and the checker's own output,
            verbatim - empty on a clean pass, since systemd-analyze says
            nothing when there is nothing to say.

        Raises:
            ServiceError: When the scratch directory or file cannot be
                staged.
        """
        staging = Path(tempfile.gettempdir()) / f"wasm-verify-{os.urandom(6).hex()}"
        candidate = staging / "wasm-verify.service"
        try:
            try:
                self.fs.make_dir(staging, mode=SECRET_DIR_MODE, parents=True, exist_ok=False)
                self.fs.write_text(candidate, content, mode=SECRET_MODE)
            except OSError as exc:
                raise ServiceError(
                    "Could not stage the unit file for verification", details=str(exc)
                ) from exc

            result = self._exec(
                ["systemd-analyze", "verify", str(candidate)], timeout=VERIFY_TIMEOUT
            )
        finally:
            if staging.exists():
                self.fs.remove_tree(staging)

        output = "\n".join(stream for stream in (result.stderr, result.stdout) if stream.strip())
        return result.success, output
