"""
Systemd service manager for WASM.

Every unit this project touches is either named ``wasm-<app>`` (the historical
scheme), registered in the store, or carries the ``Generated by WASM`` marker
written by the templates. Anything else on the box belongs to the distribution
and must never be listed, stopped or deleted from here.
"""

import re
import sqlite3
from pathlib import Path

from jinja2 import Environment, PackageLoader, TemplateNotFound
from jinja2 import TemplateError as JinjaTemplateError

from wasm.core.config import SYSTEMD_DIR
from wasm.core.exceptions import ServiceError, TemplateError, WASMError
from wasm.core.runner import DEFAULT_TIMEOUT, CommandResult, CommandRunner, get_runner
from wasm.core.store import Service, get_store
from wasm.core.utils import write_file
from wasm.managers.base_manager import BaseManager

#: Marker every generated unit file carries, used to recognise our own units
#: when the store has lost track of them.
WASM_UNIT_MARKER = "Generated by WASM"

#: Starting or restarting an app can take a while: systemd waits for the unit
#: to settle before it answers.
_LIFECYCLE_TIMEOUT = 120


class ServiceManager(BaseManager):
    """
    Manager for systemd services.

    Handles creating, starting, stopping, and managing systemd services.
    """

    SYSTEMD_DIR = SYSTEMD_DIR

    #: Prefix carried by every unit this project created before the name was
    #: shortened. New units drop it and are recognised through the store or the
    #: unit-file marker instead.
    SERVICE_PREFIX = "wasm-"
    LEGACY_PREFIX = SERVICE_PREFIX

    def __init__(self, verbose: bool = False, runner: CommandRunner | None = None):
        """
        Initialize service manager.

        Args:
            verbose: Enable verbose logging.
            runner: Command runner to execute systemd with. Defaults to the
                process-wide runner.
        """
        super().__init__(verbose=verbose)
        self.store = get_store()
        self._runner = runner

        try:
            # Unit files are not markup: autoescaping would corrupt ExecStart.
            self.jinja_env: Environment | None = Environment(
                loader=PackageLoader("wasm", "templates/systemd"),
                trim_blocks=True,
                lstrip_blocks=True,
                autoescape=False,  # noqa: S701
            )
        except (ImportError, ValueError, OSError) as exc:
            # A missing template package is not fatal: everything except
            # create_service keeps working.
            self.logger.debug(f"Systemd template environment unavailable: {exc}")
            self.jinja_env = None

    @property
    def runner(self) -> CommandRunner:
        """
        The command runner used for every systemd invocation.

        Returns:
            The injected runner, or the process-wide one.
        """
        return self._runner or get_runner()

    def _exec(
        self,
        argv: list[str],
        *,
        sudo: bool = False,
        timeout: int = DEFAULT_TIMEOUT,
    ) -> CommandResult:
        """
        Run a command through the shared runner.

        Args:
            argv: Program and arguments.
            sudo: Prefix the command with sudo.
            timeout: Deadline in seconds.

        Returns:
            The command outcome.
        """
        return self.runner.run(["sudo", *argv] if sudo else argv, timeout=timeout)

    def is_installed(self) -> bool:
        """Check if systemd is available."""
        return self.runner.exists("systemctl")

    def get_version(self) -> str | None:
        """Get systemd version."""
        result = self._exec(["systemctl", "--version"])
        if result.success:
            match = re.search(r"systemd (\d+)", result.stdout)
            if match:
                return match.group(1)
        return None

    def _get_service_name(self, name: str) -> str:
        """
        Get service name for new services (no prefix).

        Args:
            name: Base service name.

        Returns:
            Service name without prefix.
        """
        # Strip legacy prefix if present
        if name.startswith(self.LEGACY_PREFIX):
            return name[len(self.LEGACY_PREFIX) :]
        return name

    def _resolve_service_name(self, name: str) -> str:
        """
        Resolve actual service name, checking both new and legacy formats.

        For backwards compatibility, checks if legacy (wasm-*) service exists
        and returns that if found. Otherwise returns the new format.

        Args:
            name: Base service name.

        Returns:
            Actual service name (may have legacy prefix if exists).
        """
        base_name = self._get_service_name(name)

        # Check if legacy service exists
        legacy_name = f"{self.LEGACY_PREFIX}{base_name}"
        legacy_file = self.SYSTEMD_DIR / f"{legacy_name}.service"
        if legacy_file.exists():
            return legacy_name

        # Check if new format exists
        new_file = self.SYSTEMD_DIR / f"{base_name}.service"
        if new_file.exists():
            return base_name

        # Neither exists, return new format for creation
        return base_name

    def _get_service_file(self, name: str) -> Path:
        """
        Get service file path for new services.

        Args:
            name: Service name.

        Returns:
            Path to service file.
        """
        service_name = self._get_service_name(name)
        if not service_name.endswith(".service"):
            service_name = f"{service_name}.service"
        return self.SYSTEMD_DIR / service_name

    def _resolve_service_file(self, name: str) -> Path:
        """
        Resolve service file path, checking both new and legacy formats.

        Args:
            name: Service name.

        Returns:
            Path to existing service file (or new format if none exists).
        """
        service_name = self._resolve_service_name(name)
        if not service_name.endswith(".service"):
            service_name = f"{service_name}.service"
        return self.SYSTEMD_DIR / service_name

    def _stored_service_names(self) -> set[str]:
        """
        Names of the units the store knows this project created.

        Returns:
            Unit names without the ``.service`` suffix. Empty when the store
            cannot be read, which only makes the filter stricter.
        """
        try:
            return {service.name.removesuffix(".service") for service in self.store.list_services()}
        except (WASMError, sqlite3.Error) as exc:
            self.logger.debug(f"Could not read services from store: {exc}")
            return set()

    def is_managed(self, name: str) -> bool:
        """
        Report whether a unit belongs to WASM.

        Three independent signals, because any one of them can be missing on a
        server that has been upgraded or repaired by hand.

        Args:
            name: Unit name, with or without the ``.service`` suffix.

        Returns:
            True when the unit was created by this project.
        """
        unit = name.removesuffix(".service")

        if unit.startswith(self.SERVICE_PREFIX):
            return True

        if unit in self._stored_service_names():
            return True

        unit_file = self.SYSTEMD_DIR / f"{unit}.service"
        try:
            return WASM_UNIT_MARKER in unit_file.read_text()
        except OSError:
            return False

    def daemon_reload(self) -> bool:
        """
        Reload systemd daemon.

        Returns:
            True if successful.
        """
        return self._exec(["systemctl", "daemon-reload"], sudo=True).success

    def service_exists(self, name: str) -> bool:
        """
        Check if a service exists (new or legacy format).

        Args:
            name: Service name.

        Returns:
            True if service exists.
        """
        service_file = self._resolve_service_file(name)
        return service_file.exists()

    def list_services(self, all_services: bool = False) -> list[dict]:
        """
        List WASM-managed services.

        The query is scoped to the units this project owns. Asking systemd for
        ``*`` and filtering afterwards used to return ssh, cron and dbus, which
        then showed up as deletable in ``wasm service list``.

        Args:
            all_services: List every unit on the system, including units WASM
                does not manage. Opt-in, for diagnostics only.

        Returns:
            List of service information dictionaries.
        """
        patterns = (
            ["*"]
            if all_services
            else [f"{self.SERVICE_PREFIX}*", *sorted(self._stored_service_names())]
        )

        result = self._exec(
            [
                "systemctl",
                "list-units",
                "--type=service",
                "--all",
                "--no-pager",
                "--plain",
                *patterns,
            ]
        )

        services: list[dict] = []
        if not result.success:
            return services

        for line in result.stdout.strip().split("\n"):
            if not line or line.startswith("UNIT"):
                continue

            parts = line.split()
            if len(parts) < 4:
                continue

            unit_name = parts[0]
            if not unit_name.endswith(".service"):
                continue

            name = unit_name.removesuffix(".service")
            if not all_services and not self.is_managed(name):
                continue

            services.append(
                {
                    "name": name,
                    "load": parts[1],
                    "active": parts[2],
                    "sub": parts[3],
                }
            )

        return services

    def get_status(self, name: str) -> dict:
        """
        Get service status.

        Args:
            name: Service name.

        Returns:
            Dictionary with status information.
        """
        service_name = self._resolve_service_name(name)

        # Check if active
        result = self._exec(["systemctl", "is-active", service_name])
        is_active = result.stdout.strip() == "active"

        # Check if enabled
        result = self._exec(["systemctl", "is-enabled", service_name])
        is_enabled = result.stdout.strip() == "enabled"

        # Get detailed status
        result = self._exec(["systemctl", "show", service_name, "--no-pager"])
        details = {}
        if result.success:
            for line in result.stdout.split("\n"):
                if "=" in line:
                    key, value = line.split("=", 1)
                    details[key] = value

        return {
            "name": service_name,
            "exists": self.service_exists(name),
            "active": is_active,
            "enabled": is_enabled,
            "pid": details.get("MainPID", ""),
            "memory": details.get("MemoryCurrent", ""),
            "uptime": details.get("ActiveEnterTimestamp", ""),
        }

    def create_service(
        self,
        name: str,
        command: str = "",
        working_directory: str = "",
        user: str | None = None,
        group: str | None = None,
        environment: dict[str, str] | None = None,
        description: str | None = None,
        template: str = "app",
        **kwargs,
    ) -> bool:
        """
        Create a new systemd service.

        Args:
            name: Service name.
            command: Command to execute (not required for docker-compose template).
            working_directory: Working directory for the service.
            user: User to run service as.
            group: Group to run service as.
            environment: Environment variables.
            description: Service description.
            template: Template name.
            **kwargs: Extra context variables passed to the template.

        Returns:
            True if service was created successfully.

        Raises:
            ServiceError: If creation fails.
            TemplateError: If the unit template is missing or invalid.
        """
        service_name = self._get_service_name(name)

        if self.service_exists(name):
            raise ServiceError(f"Service already exists: {service_name}")

        if not self.jinja_env:
            raise ServiceError(
                "Template environment not initialized",
                details="Reinstall wasm so that the packaged systemd templates are available.",
            )

        # Prepare context
        ctx = {
            "name": service_name,
            "description": description or f"WASM managed service: {name}",
            "command": command,
            "working_directory": working_directory,
            "user": user or self.config.service_user,
            "group": group or self.config.service_group,
            "environment": environment or {},
        }
        ctx.update(kwargs)

        # Render template
        try:
            template_obj = self.jinja_env.get_template(f"{template}.service.j2")
            service_content = template_obj.render(**ctx)
        except TemplateNotFound as exc:
            raise TemplateError(f"Template not found: {template}.service.j2") from exc
        except JinjaTemplateError as exc:
            raise TemplateError(f"Template rendering failed: {exc}") from exc

        # Write service file
        service_file = self._get_service_file(name)
        if not write_file(service_file, service_content, sudo=True):
            raise ServiceError(f"Failed to write service file: {service_file}")

        # Reload daemon
        self.daemon_reload()

        # Register in store
        try:
            svc = Service(
                name=service_name,
                unit_file=str(service_file),
                command=command,
                working_directory=working_directory,
                user=ctx["user"],
                group=ctx["group"],
                environment=environment,
                status="inactive",
                enabled=False,
            )
            self.store.create_service(svc)
        except (WASMError, sqlite3.Error) as e:
            self.logger.debug(f"Could not register service in store: {e}")

        self.logger.debug(f"Created service: {service_name}")
        return True

    def delete_service(self, name: str) -> bool:
        """
        Delete a service.

        Args:
            name: Service name.

        Returns:
            True if service was deleted.

        Raises:
            ServiceError: If the unit is not managed by WASM, or if the unit
                file cannot be removed.
        """
        service_name = self._resolve_service_name(name)
        service_file = self._resolve_service_file(name)

        # An existing unit that WASM did not write belongs to the system. This
        # is what stopped `wasm service delete ssh` from removing sshd.
        if service_file.exists() and not self.is_managed(service_name):
            raise ServiceError(
                f"Refusing to delete a unit WASM does not manage: {service_name}",
                details=(
                    f"{service_file} was not generated by WASM. "
                    "Remove it with systemctl if that is really what you want."
                ),
            )

        # Stop service if running
        self.stop(name)

        # Disable service
        self.disable(name)

        # Remove service file
        if service_file.exists():
            if not self._exec(["rm", "-f", str(service_file)], sudo=True).success:
                raise ServiceError(f"Failed to delete service: {service_name}")

        # Reload daemon
        self.daemon_reload()

        # Remove from store
        try:
            self.store.delete_service(service_name)
        except (WASMError, sqlite3.Error) as e:
            self.logger.debug(f"Could not remove service from store: {e}")

        self.logger.debug(f"Deleted service: {service_name}")
        return True

    def start(self, name: str) -> bool:
        """
        Start a service.

        Args:
            name: Service name.

        Returns:
            True if service started successfully.

        Raises:
            ServiceError: If systemd refuses to start the unit.
        """
        service_name = self._resolve_service_name(name)
        result = self._exec(
            ["systemctl", "start", service_name], sudo=True, timeout=_LIFECYCLE_TIMEOUT
        )

        if not result.success:
            raise ServiceError(
                f"Failed to start service: {service_name}",
                details=result.stderr,
            )

        self._update_stored_status(service_name, "active")
        return True

    def stop(self, name: str) -> bool:
        """
        Stop a service.

        Args:
            name: Service name.

        Returns:
            True if service stopped successfully.
        """
        service_name = self._resolve_service_name(name)
        result = self._exec(
            ["systemctl", "stop", service_name], sudo=True, timeout=_LIFECYCLE_TIMEOUT
        )

        self._update_stored_status(service_name, "inactive")
        return result.success

    def restart(self, name: str) -> bool:
        """
        Restart a service.

        Args:
            name: Service name.

        Returns:
            True if service restarted successfully.

        Raises:
            ServiceError: If systemd refuses to restart the unit.
        """
        service_name = self._resolve_service_name(name)
        result = self._exec(
            ["systemctl", "restart", service_name], sudo=True, timeout=_LIFECYCLE_TIMEOUT
        )

        if not result.success:
            raise ServiceError(
                f"Failed to restart service: {service_name}",
                details=result.stderr,
            )

        self._update_stored_status(service_name, "active")
        return True

    def _update_stored_status(self, service_name: str, status: str) -> None:
        """
        Record a status change in the store, tolerating a missing record.

        Args:
            service_name: Resolved unit name.
            status: New status value.
        """
        try:
            self.store.update_service_status(service_name, status)
        except (WASMError, sqlite3.Error) as e:
            self.logger.debug(f"Could not update service status in store: {e}")

    def _set_stored_enabled(self, service_name: str, enabled: bool) -> None:
        """
        Record the enabled flag in the store, tolerating a missing record.

        Args:
            service_name: Resolved unit name.
            enabled: Whether the unit starts on boot.
        """
        try:
            svc = self.store.get_service(service_name)
            if svc:
                svc.enabled = enabled
                self.store.update_service(svc)
        except (WASMError, sqlite3.Error) as e:
            self.logger.debug(f"Could not update service in store: {e}")

    def enable(self, name: str) -> bool:
        """
        Enable a service to start on boot.

        Args:
            name: Service name.

        Returns:
            True if service was enabled.
        """
        service_name = self._resolve_service_name(name)
        result = self._exec(["systemctl", "enable", service_name], sudo=True)

        self._set_stored_enabled(service_name, True)
        return result.success

    def disable(self, name: str) -> bool:
        """
        Disable a service from starting on boot.

        Args:
            name: Service name.

        Returns:
            True if service was disabled.
        """
        service_name = self._resolve_service_name(name)
        result = self._exec(["systemctl", "disable", service_name], sudo=True)

        self._set_stored_enabled(service_name, False)
        return result.success

    def logs(
        self,
        name: str,
        lines: int = 50,
        follow: bool = False,
    ) -> str:
        """
        Get service logs.

        Args:
            name: Service name.
            lines: Number of lines to return.
            follow: Follow log output (not supported in this method).

        Returns:
            Log output.
        """
        service_name = self._resolve_service_name(name)

        result = self._exec(["journalctl", "-u", service_name, "-n", str(lines), "--no-pager"])

        return result.stdout if result.success else result.stderr

    def get_service_config(self, name: str) -> str | None:
        """
        Get service configuration content.

        Args:
            name: Service name.

        Returns:
            Service file content or None.
        """
        service_file = self._resolve_service_file(name)
        try:
            return service_file.read_text()
        except OSError as exc:
            self.logger.debug(f"Could not read unit file {service_file}: {exc}")
            return None
