"""
Systemd service manager for WASM.

This module is the only door to systemd, and WASM runs as root, so the question
it has to answer before every single operation is *who owns this unit*. Getting
that wrong is not a cosmetic bug: ``wasm service delete ssh`` used to stop and
disable sshd, because the ownership guard only ran when a file existed under
``/etc/systemd/system`` and distribution units live in ``/usr/lib/systemd/system``.

Definition of a WASM-managed unit
---------------------------------
A unit belongs to WASM when **all three** hold:

1. **systemd loads it from the directory WASM manages.** The authority is
   ``systemctl show -p FragmentPath``, not a guess based on paths: it is one
   call and it reports where the unit actually comes from, including when a
   name in ``/etc`` is an alias for a file shipped by the distribution.
2. **It does not shadow a unit shipped with the system.** A file in our
   directory that eclipses ``/usr/lib/systemd/system/nginx.service`` is a
   takeover of the distribution's unit, not one of ours, and is refused even
   though it sits in the right directory.
3. **It carries a WASM signal**: the ``wasm-`` prefix (the historical naming
   scheme), a record in the store, or the ``Generated by WASM`` marker written
   by the templates. Three signals because any one of them can be missing on a
   server that has been upgraded or repaired by hand.

Every operation that reads or changes unit state goes through
:meth:`ServiceManager.inspect_unit`, so the guard cannot be forgotten in one
code path the way it was before.

Why ``Environment=`` and not ``EnvironmentFile=``
------------------------------------------------
``EnvironmentFile=`` at mode 0600 would keep secrets out of ``systemctl show``
output, which is the one real advantage it has, and it was evaluated here.
It is not what this manager does:

- The file is parsed shell-like, with its own quoting rules. CLAUDE.md records
  that quoted values in ``.env`` files are a recurring source of breakage; an
  ``EnvironmentFile`` moves that same class of failure into the unit's boot
  path, where it fails at start time instead of at write time.
- It turns one unit file into two pieces of state that every create, update,
  delete, backup and restore path would have to keep in sync. A secret left
  behind by a delete is worse than a secret visible to root in
  ``systemctl show``, which is a root-only view of a root-owned machine anyway.
- The injection risk it is sometimes credited with removing is already closed
  at the boundary by :mod:`wasm.validators.environment` plus escaping at render
  time, and that validation would still be required for an environment file.

The decision is therefore: keep ``Environment=`` in the unit, and make the
validation in :meth:`ServiceManager.create_service` mandatory rather than
optional, since this manager is the single step every caller must pass through.
"""

from __future__ import annotations

import re
import sqlite3
from collections.abc import Callable, Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from jinja2 import Environment, PackageLoader, TemplateNotFound
from jinja2 import TemplateError as JinjaTemplateError

from wasm.core.config import SYSTEMD_DIR
from wasm.core.exceptions import ServiceError, TemplateError, WASMError
from wasm.core.fs import FileSystem
from wasm.core.runner import DEFAULT_TIMEOUT, CommandResult, CommandRunner
from wasm.core.store import Service, get_store
from wasm.managers.base_manager import BaseManager
from wasm.validators.environment import validate_environment, validate_unit_value
from wasm.validators.names import validate_service_name

#: Marker every generated unit file carries, used to recognise our own units
#: when the store has lost track of them.
WASM_UNIT_MARKER = "Generated by WASM"

#: Starting or restarting an app can take a while: systemd waits for the unit
#: to settle before it answers.
_LIFECYCLE_TIMEOUT = 120

#: ``journalctl -f`` runs until the caller stops reading. The deadline exists
#: because the runner requires one, not because an hour of logs is a limit
#: anybody should hit; callers that need longer pass their own.
_FOLLOW_TIMEOUT = 3600

#: Unit files are not secret - systemd reads them as root and users need to be
#: able to inspect them - but nothing outside root may rewrite one.
UNIT_FILE_MODE = 0o644


@dataclass(frozen=True)
class UnitOwnership:
    """
    What WASM knows about one systemd unit.

    Attributes:
        unit: Validated unit name without the ``.service`` suffix.
        path: Where WASM would write this unit inside its own directory.
        fragment_path: The file systemd reports loading the unit from, when
            systemd could be asked.
        exists: True when a unit file for this name exists anywhere systemd
            looks, or systemd already knows the unit.
        managed: True when the unit satisfies every ownership rule.
        reason: Why the unit is not managed. Empty when it is.
    """

    unit: str
    path: Path
    fragment_path: Path | None
    exists: bool
    managed: bool
    reason: str = ""

    @property
    def unit_file(self) -> str:
        """The full unit name, as systemctl expects it."""
        return f"{self.unit}.service"


class ServiceManager(BaseManager):
    """
    Manager for systemd services.

    Handles creating, starting, stopping, and managing systemd services. Every
    public method refuses to act on a unit WASM does not own; see the module
    docstring for what ownership means.
    """

    SYSTEMD_DIR = SYSTEMD_DIR

    #: Every directory systemd loads units from, most specific first. Ownership
    #: is decided against all of them: looking only at ``/etc/systemd/system``
    #: is what let ``delete ssh`` through, because sshd lives in ``/usr/lib``.
    UNIT_SEARCH_DIRS: tuple[Path, ...] = (
        SYSTEMD_DIR,
        Path("/run/systemd/system"),
        Path("/run/systemd/transient"),
        Path("/etc/systemd/system.control"),
        Path("/usr/local/lib/systemd/system"),
        Path("/usr/lib/systemd/system"),
        Path("/lib/systemd/system"),
    )

    #: Prefix carried by every unit this project created before the name was
    #: shortened. New units drop it and are recognised through the store or the
    #: unit-file marker instead.
    SERVICE_PREFIX = "wasm-"
    LEGACY_PREFIX = SERVICE_PREFIX

    def __init__(
        self,
        verbose: bool = False,
        runner: CommandRunner | None = None,
        fs: FileSystem | None = None,
    ):
        """
        Initialize service manager.

        Args:
            verbose: Enable verbose logging.
            runner: Command runner to execute systemd with. Defaults to the
                process-wide runner.
            fs: Filesystem to write unit files through. Defaults to the
                process-wide one, which is what makes ``--dry-run`` refuse to
                install or delete a unit.
        """
        super().__init__(verbose=verbose, runner=runner, fs=fs)
        self.store = get_store()

        try:
            # Unit files are not markup: autoescaping would corrupt ExecStart.
            self.jinja_env: Environment | None = Environment(
                loader=PackageLoader("wasm", "templates/systemd"),
                trim_blocks=True,
                lstrip_blocks=True,
                autoescape=False,  # noqa: S701
            )
        except (ImportError, ValueError, OSError) as exc:
            # A missing template package is not fatal: everything except
            # create_service keeps working.
            self.logger.debug(f"Systemd template environment unavailable: {exc}")
            self.jinja_env = None

    def _exec(self, argv: list[str], *, timeout: int = DEFAULT_TIMEOUT) -> CommandResult:
        """
        Run a command through the shared runner.

        WASM requires root, so nothing here is prefixed with sudo: a manager
        that shells out to sudo hides which identity the change was made under
        and breaks on hosts where sudo is not installed.

        Args:
            argv: Program and arguments.
            timeout: Deadline in seconds.

        Returns:
            The command outcome.
        """
        return self.runner.run(argv, timeout=timeout)

    def is_installed(self) -> bool:
        """
        Check if systemd is available.

        Returns:
            True when systemctl can be executed.
        """
        return self.runner.exists("systemctl")

    def get_version(self) -> str | None:
        """
        Get systemd version.

        Returns:
            The major version as a string, or None when it cannot be read.
        """
        result = self._exec(["systemctl", "--version"])
        if result.success:
            match = re.search(r"systemd (\d+)", result.stdout)
            if match:
                return match.group(1)
        return None

    # Naming ---------------------------------------------------------------

    def _get_service_name(self, name: str) -> str:
        """
        Get the validated service name for new services (no prefix).

        Args:
            name: Base service name, with or without the ``.service`` suffix.

        Returns:
            Service name without prefix or suffix.

        Raises:
            ValidationError: When the name is not a safe unit name.
        """
        candidate = validate_service_name(str(name).removesuffix(".service"))
        return candidate.removeprefix(self.LEGACY_PREFIX) or candidate

    def _resolve_service_name(self, name: str) -> str:
        """
        Resolve actual service name, checking both new and legacy formats.

        For backwards compatibility, checks if a legacy (``wasm-*``) unit exists
        and returns that if found. Otherwise returns the new format.

        Args:
            name: Base service name.

        Returns:
            Actual service name (may have legacy prefix if it exists).

        Raises:
            ValidationError: When the name is not a safe unit name.
        """
        given = validate_service_name(str(name).removesuffix(".service"))

        if given.startswith(self.LEGACY_PREFIX):
            # A caller that spells the prefix means that unit. Only fall back to
            # the unprefixed form when it is the one actually installed,
            # otherwise the prefix - a WASM ownership signal - is thrown away.
            stripped = given.removeprefix(self.LEGACY_PREFIX) or given
            if (self.SYSTEMD_DIR / f"{given}.service").exists():
                return given
            if (self.SYSTEMD_DIR / f"{stripped}.service").exists():
                return stripped
            return given

        legacy_name = f"{self.LEGACY_PREFIX}{given}"
        if (self.SYSTEMD_DIR / f"{legacy_name}.service").exists():
            return legacy_name

        return given

    def _get_service_file(self, name: str) -> Path:
        """
        Get the unit file path a new service would be written to.

        Args:
            name: Service name.

        Returns:
            Path to the unit file inside the managed directory.

        Raises:
            ValidationError: When the name is not a safe unit name.
        """
        return self.SYSTEMD_DIR / f"{self._get_service_name(name)}.service"

    def _resolve_service_file(self, name: str) -> Path:
        """
        Resolve unit file path, checking both new and legacy formats.

        Args:
            name: Service name.

        Returns:
            Path to the existing unit file, or the new-format path when none
            exists.

        Raises:
            ValidationError: When the name is not a safe unit name.
        """
        return self.SYSTEMD_DIR / f"{self._resolve_service_name(name)}.service"

    # Ownership ------------------------------------------------------------

    def _stored_service_names(self) -> set[str]:
        """
        Names of the units the store knows this project created.

        Returns:
            Unit names without the ``.service`` suffix. Empty when the store
            cannot be read, which only makes the filter stricter.
        """
        try:
            return {service.name.removesuffix(".service") for service in self.store.list_services()}
        except (WASMError, sqlite3.Error) as exc:
            self.logger.debug(f"Could not read services from store: {exc}")
            return set()

    def _is_managed_dir(self, directory: Path) -> bool:
        """
        Report whether a directory is the one WASM writes units into.

        Args:
            directory: Candidate unit directory.

        Returns:
            True when it is the managed directory, comparing resolved paths so
            a symlinked ``/lib`` does not read as a second location.
        """
        if directory == self.SYSTEMD_DIR:
            return True
        try:
            return directory.resolve() == Path(self.SYSTEMD_DIR).resolve()
        except OSError:
            return False

    def _foreign_unit_dirs(self) -> list[Path]:
        """
        The unit directories that belong to the system, not to WASM.

        Returns:
            Every configured search directory except the managed one.
        """
        return [d for d in self.UNIT_SEARCH_DIRS if not self._is_managed_dir(d)]

    def _fragment_path(self, unit_file: str) -> Path | None:
        """
        Ask systemd where it loads a unit from.

        Args:
            unit_file: Full unit name, including the ``.service`` suffix.

        Returns:
            The path systemd reports, or None when systemd does not know the
            unit or cannot be reached.
        """
        result = self._exec(["systemctl", "show", "-p", "FragmentPath", unit_file])
        if not result.success:
            return None

        for line in result.stdout.splitlines():
            key, separator, value = line.partition("=")
            if separator and key.strip() == "FragmentPath":
                fragment = value.strip()
                return Path(fragment) if fragment else None
        return None

    def _carries_wasm_signal(self, unit: str, path: Path) -> bool:
        """
        Report whether a unit shows any sign of having been created by WASM.

        Args:
            unit: Unit name without the ``.service`` suffix.
            path: The unit file inside the managed directory.

        Returns:
            True when the prefix, the store or the file marker identifies it.
        """
        if unit.startswith(self.SERVICE_PREFIX):
            return True
        if unit in self._stored_service_names():
            return True
        try:
            return WASM_UNIT_MARKER in path.read_text()
        except OSError:
            return False

    def inspect_unit(self, name: str) -> UnitOwnership:
        """
        Decide whether a unit belongs to WASM, and why.

        Args:
            name: Unit name, with or without the ``.service`` suffix.

        Returns:
            The ownership verdict, including the reason when it is negative.

        Raises:
            ValidationError: When the name is not a safe unit name.
        """
        unit = self._resolve_service_name(name)
        path = self.SYSTEMD_DIR / f"{unit}.service"
        fragment = self._fragment_path(f"{unit}.service")

        shadowed = next(
            (
                d / f"{unit}.service"
                for d in self._foreign_unit_dirs()
                if (d / f"{unit}.service").exists()
            ),
            None,
        )
        exists = path.exists() or shadowed is not None or fragment is not None

        def verdict(managed: bool, reason: str = "") -> UnitOwnership:
            return UnitOwnership(
                unit=unit,
                path=path,
                fragment_path=fragment,
                exists=exists,
                managed=managed,
                reason=reason,
            )

        if fragment is not None and not self._is_managed_dir(fragment.parent):
            return verdict(False, f"systemd loads it from {fragment}, outside {self.SYSTEMD_DIR}")

        if shadowed is not None:
            return verdict(
                False,
                f"a unit with the same name is shipped by the system at {shadowed}; "
                "a file in the managed directory would eclipse it",
            )

        # Ownership is deliberately independent of existence: a unit systemd has
        # loaded but whose file this process cannot see is still ours when
        # nothing points at another owner. Callers ask about existence through
        # ``exists``, which is what decides whether an operation has a target.
        if not self._carries_wasm_signal(unit, path):
            return verdict(
                False,
                f"{path} was not generated by WASM"
                if path.exists()
                else f"nothing identifies {unit} as a unit WASM created",
            )

        return verdict(True)

    def is_managed(self, name: str) -> bool:
        """
        Report whether a unit belongs to WASM.

        Args:
            name: Unit name, with or without the ``.service`` suffix.

        Returns:
            True when the unit was created by this project and still lives
            where this project puts its units. An unusable name is not managed
            rather than an error, so listings can call this on anything.
        """
        try:
            return self.inspect_unit(name).managed
        except WASMError as exc:
            self.logger.debug(f"Not a WASM unit name: {name!r}: {exc}")
            return False

    def _require_managed(
        self, name: str, *, operation: str, missing_ok: bool = False
    ) -> UnitOwnership:
        """
        Resolve a unit and refuse to operate on it unless WASM owns it.

        Args:
            name: Unit name, with or without the ``.service`` suffix.
            operation: Verb used in the error message.
            missing_ok: Return the verdict instead of raising when the unit does
                not exist anywhere. Used by the idempotent operations (stop,
                disable, delete, status), so teardown does not depend on knowing
                whether a unit was ever created.

        Returns:
            The ownership verdict. It is only returned with ``exists`` False
            when ``missing_ok`` is set.

        Raises:
            ServiceError: When the unit is not WASM's, or does not exist and
                ``missing_ok`` is False.
            ValidationError: When the name is not a safe unit name.
        """
        info = self.inspect_unit(name)

        # Existence is checked first: a name nobody has installed cannot belong
        # to anyone, and the caller decides whether that is an error.
        if not info.exists:
            if missing_ok:
                return info
            raise ServiceError(
                f"Unknown service: {info.unit}",
                details=(
                    f"There is no unit file at {info.path}. "
                    "Run 'wasm service list' to see the units WASM manages."
                ),
            )

        if info.managed:
            return info

        raise ServiceError(
            f"Refusing to {operation} a unit WASM does not manage: {info.unit}",
            details=(
                f"{info.reason}. Use systemctl directly if that is really what you want to do."
            ),
        )

    # State ----------------------------------------------------------------

    def daemon_reload(self) -> bool:
        """
        Reload systemd daemon.

        Returns:
            True if successful.
        """
        result = self._exec(["systemctl", "daemon-reload"])
        if not result.success:
            self.logger.debug(f"daemon-reload failed: {result.stderr}")
        return result.success

    def service_exists(self, name: str) -> bool:
        """
        Check if a unit file exists in the managed directory.

        Args:
            name: Service name.

        Returns:
            True if the unit file exists, in either the new or legacy format.

        Raises:
            ValidationError: When the name is not a safe unit name.
        """
        return self._resolve_service_file(name).exists()

    def list_services(self, all_services: bool = False) -> list[dict]:
        """
        List WASM-managed services.

        The query is scoped to the units this project owns. Asking systemd for
        ``*`` and filtering afterwards used to return ssh, cron and dbus, which
        then showed up as deletable in ``wasm service list``.

        Args:
            all_services: List every unit on the system, including units WASM
                does not manage. Opt-in, for diagnostics only.

        Returns:
            List of service information dictionaries.
        """
        patterns = (
            ["*"]
            if all_services
            else [f"{self.SERVICE_PREFIX}*", *sorted(self._stored_service_names())]
        )

        result = self._exec(
            [
                "systemctl",
                "list-units",
                "--type=service",
                "--all",
                "--no-pager",
                "--plain",
                *patterns,
            ]
        )

        services: list[dict] = []
        if not result.success:
            return services

        for line in result.stdout.strip().split("\n"):
            if not line or line.startswith("UNIT"):
                continue

            parts = line.split()
            if len(parts) < 4:
                continue

            unit_name = parts[0]
            if not unit_name.endswith(".service"):
                continue

            name = unit_name.removesuffix(".service")
            if not all_services and not self.is_managed(name):
                continue

            services.append(
                {
                    "name": name,
                    "load": parts[1],
                    "active": parts[2],
                    "sub": parts[3],
                }
            )

        return services

    def get_status(self, name: str) -> dict:
        """
        Get service status.

        Args:
            name: Service name.

        Returns:
            Dictionary with status information. A unit that does not exist is
            reported as absent rather than refused, because callers use this to
            decide whether they still have to create it.

        Raises:
            ServiceError: When the unit exists but WASM does not manage it.
            ValidationError: When the name is not a safe unit name.
        """
        info = self._require_managed(name, operation="inspect", missing_ok=True)

        # A unit this process cannot see a file for is still queried: the three
        # probes below only read, systemd is the authority on what is running,
        # and a status call that lies about a live service is how a broken
        # deployment gets reported as healthy. ``exists`` reports our own view.
        is_active = (
            self._exec(["systemctl", "is-active", info.unit_file]).stdout.strip() == "active"
        )
        is_enabled = (
            self._exec(["systemctl", "is-enabled", info.unit_file]).stdout.strip() == "enabled"
        )

        result = self._exec(["systemctl", "show", info.unit_file, "--no-pager"])
        details: dict[str, str] = {}
        if result.success:
            for line in result.stdout.split("\n"):
                key, separator, value = line.partition("=")
                if separator:
                    details[key] = value

        return {
            "name": info.unit,
            "exists": info.exists,
            "active": is_active,
            "enabled": is_enabled,
            "pid": details.get("MainPID", ""),
            "memory": details.get("MemoryCurrent", ""),
            "uptime": details.get("ActiveEnterTimestamp", ""),
        }

    # Creation -------------------------------------------------------------

    def _write_unit_atomically(self, path: Path, content: str) -> None:
        """
        Write a unit file so that no reader ever sees a partial one.

        This used to open its own ``mkstemp``, fsync it and ``os.replace`` it
        into position. :meth:`~wasm.core.fs.FileSystem.write_text` already does
        exactly that - sibling temporary, fsync, atomic rename, mode applied at
        creation - so the copy is gone: two implementations of an atomic write
        means one of them eventually stops being atomic, and only one of them
        can be turned off by ``--dry-run``.

        Args:
            path: Final unit file path.
            content: Complete unit file body.

        Raises:
            ServiceError: When the file cannot be written or renamed.
        """
        try:
            self.fs.write_text(path, content, mode=UNIT_FILE_MODE)
        except OSError as exc:
            raise ServiceError(
                f"Failed to write unit file: {path}",
                details=(
                    f"{exc}. The previous unit file, if any, is untouched. "
                    f"Check that {path.parent} exists and is writable by root."
                ),
            ) from exc

    def _render_unit(self, template: str, context: Mapping[str, Any]) -> str:
        """
        Render a unit file from a packaged template.

        Args:
            template: Template name without the ``.service.j2`` suffix.
            context: Variables handed to the template.

        Returns:
            The rendered unit file.

        Raises:
            ServiceError: When the template environment is unavailable.
            TemplateError: If the unit template is missing or invalid.
        """
        if not self.jinja_env:
            raise ServiceError(
                "Template environment not initialized",
                details="Reinstall wasm so that the packaged systemd templates are available.",
            )

        try:
            template_obj = self.jinja_env.get_template(f"{template}.service.j2")
            return template_obj.render(**context)
        except TemplateNotFound as exc:
            raise TemplateError(f"Template not found: {template}.service.j2") from exc
        except JinjaTemplateError as exc:
            raise TemplateError(f"Template rendering failed: {exc}") from exc

    def create_service(
        self,
        name: str,
        command: str = "",
        working_directory: str = "",
        user: str | None = None,
        group: str | None = None,
        environment: dict[str, str] | None = None,
        description: str | None = None,
        template: str = "app",
        **kwargs: Any,
    ) -> None:
        """
        Create a new systemd service.

        This is the mandatory step for every caller that installs a unit, so it
        is where the name and the environment are validated: the deployers and
        the web API used to reach the templates without passing through either
        check.

        Args:
            name: Service name.
            command: Command to execute (not required for docker-compose template).
            working_directory: Working directory for the service.
            user: User to run service as.
            group: Group to run service as.
            environment: Environment variables.
            description: Service description.
            template: Template name.
            **kwargs: Extra context variables passed to the template.

        Raises:
            ServiceError: If the unit already exists, would eclipse a unit
                shipped by the distribution, or cannot be written.
            TemplateError: If the unit template is missing or invalid.
            ValidationError: If the name, the environment or a directive value
                is unsafe.
        """
        unit = self._get_service_name(name)
        env = validate_environment(environment or {})

        info = self.inspect_unit(unit)
        if info.exists:
            if info.managed:
                raise ServiceError(
                    f"Service already exists: {info.unit}",
                    details=f"Delete it first, or edit {info.path}.",
                )
            raise ServiceError(
                f"Refusing to create a unit that is not WASM's to create: {info.unit}",
                details=f"{info.reason}. Choose a different service name.",
            )

        ctx: dict[str, Any] = {
            "name": unit,
            "description": validate_unit_value(
                description or f"WASM managed service: {unit}", field="Description"
            ),
            "command": validate_unit_value(command, field="ExecStart"),
            "working_directory": validate_unit_value(working_directory, field="WorkingDirectory"),
            "user": validate_unit_value(user or self.config.service_user, field="User"),
            "group": validate_unit_value(group or self.config.service_group, field="Group"),
            "environment": env,
        }
        ctx.update(kwargs)

        unit_file = self._get_service_file(unit)
        content = self._render_unit(template, ctx)
        self._write_unit_atomically(unit_file, content)
        self.daemon_reload()

        try:
            self.store.create_service(
                Service(
                    name=unit,
                    unit_file=str(unit_file),
                    command=command,
                    working_directory=working_directory,
                    user=str(ctx["user"]),
                    group=str(ctx["group"]),
                    environment=env,
                    status="inactive",
                    enabled=False,
                )
            )
        except (WASMError, sqlite3.Error) as exc:
            self.logger.debug(f"Could not register service in store: {exc}")

        self.logger.debug(f"Created service: {unit}")

    def create_from_unit(self, name: str, content: str) -> None:
        """
        Create a unit from a complete file the caller wrote by hand.

        This exists because the panel offers an advanced mode where an operator
        supplies the whole unit. That mode used to write the file directly,
        which meant it could put any content at any unit path as root while the
        ownership guard on this class looked on. Routing it here applies the
        same rules as every other write.

        Args:
            name: Service name.
            content: Complete unit file body.

        Raises:
            ServiceError: When a unit of that name already exists anywhere
                systemd looks, when the body lacks the WASM marker, or when the
                write fails.
            ValidationError: When the name is not a safe unit name.
        """
        unit = self._get_service_name(name)
        self._check_unit_body(unit, content)

        info = self.inspect_unit(unit)
        if info.exists:
            if info.managed:
                raise ServiceError(
                    f"Service already exists: {info.unit}",
                    details=f"Delete it first, or edit {info.path}.",
                )
            raise ServiceError(
                f"Refusing to create a unit that is not WASM's to create: {info.unit}",
                details=f"{info.reason}. Choose a different service name.",
            )

        self._write_unit_atomically(self._get_service_file(unit), content)
        self.daemon_reload()

    def _check_unit_body(self, unit: str, content: str) -> None:
        """
        Reject a unit body that WASM must not write.

        Args:
            unit: Unit name, for the error message.
            content: Candidate unit body.

        Raises:
            ServiceError: When the marker is missing or the body is not text.
        """
        if WASM_UNIT_MARKER not in content:
            raise ServiceError(
                f"Refusing to write a unit without the WASM marker: {unit}",
                details=(
                    f"Keep the '# {WASM_UNIT_MARKER}' comment in the file. Without it "
                    "WASM stops recognising the unit as its own and refuses to manage it."
                ),
            )
        if "\x00" in content:
            raise ServiceError(
                f"Refusing to write a unit containing a NUL byte: {unit}",
                details="A unit file is text; a NUL byte would truncate it.",
            )

    def update_config(self, name: str, content: str) -> str:
        """
        Replace the body of a unit WASM manages.

        Args:
            name: Service name.
            content: Complete replacement unit file.

        Returns:
            The previous unit body, so the caller can revert by passing it back
            to this method.

        Raises:
            ServiceError: When the unit is not WASM's, cannot be read, or the
                new body would drop the marker that identifies it as ours.
            ValidationError: When the name is not a safe unit name.
        """
        info = self._require_managed(name, operation="rewrite")

        if WASM_UNIT_MARKER not in content:
            raise ServiceError(
                f"Refusing to write a unit without the WASM marker: {info.unit}",
                details=(
                    f"Keep the '# {WASM_UNIT_MARKER}' comment in the file. Without it "
                    "WASM stops recognising the unit as its own and refuses to manage it."
                ),
            )

        if "\x00" in content:
            raise ServiceError(
                f"Refusing to write a unit containing a NUL byte: {info.unit}",
                details="A unit file is text; a NUL byte would truncate it.",
            )

        try:
            previous = info.path.read_text()
        except OSError as exc:
            raise ServiceError(
                f"Could not read the current unit file: {info.path}",
                details=str(exc),
            ) from exc

        self._write_unit_atomically(info.path, content)
        self.daemon_reload()
        return previous

    def delete_service(self, name: str) -> None:
        """
        Delete a service.

        Args:
            name: Service name.

        Raises:
            ServiceError: If the unit is not managed by WASM, or if the unit
                file cannot be removed.
            ValidationError: When the name is not a safe unit name.
        """
        info = self._require_managed(name, operation="delete", missing_ok=True)

        if info.exists:
            self._exec(["systemctl", "stop", info.unit_file], timeout=_LIFECYCLE_TIMEOUT)
            self._exec(["systemctl", "disable", info.unit_file])

            try:
                self.fs.remove(info.path, missing_ok=True)
            except OSError as exc:
                raise ServiceError(
                    f"Failed to delete service: {info.unit}",
                    details=str(exc),
                ) from exc

            self.daemon_reload()

        try:
            self.store.delete_service(info.unit)
        except (WASMError, sqlite3.Error) as exc:
            self.logger.debug(f"Could not remove service from store: {exc}")

        self.logger.debug(f"Deleted service: {info.unit}")

    # Lifecycle ------------------------------------------------------------

    def start(self, name: str) -> None:
        """
        Start a service.

        Args:
            name: Service name.

        Raises:
            ServiceError: If the unit is not WASM's, does not exist, or systemd
                refuses to start it.
            ValidationError: When the name is not a safe unit name.
        """
        info = self._require_managed(name, operation="start")
        result = self._exec(["systemctl", "start", info.unit_file], timeout=_LIFECYCLE_TIMEOUT)

        if not result.success:
            raise ServiceError(
                f"Failed to start service: {info.unit}",
                details=result.stderr,
            )

        self._update_stored_status(info.unit, "active")

    def stop(self, name: str) -> bool:
        """
        Stop a service.

        Args:
            name: Service name.

        Returns:
            True when the unit is stopped afterwards, including when there was
            nothing to stop. Teardown paths call this before knowing whether
            the unit was ever created.

        Raises:
            ServiceError: If the unit exists but is not WASM's.
            ValidationError: When the name is not a safe unit name.
        """
        info = self._require_managed(name, operation="stop", missing_ok=True)
        if not info.exists:
            self.logger.debug(f"Nothing to stop: {info.unit} does not exist")
            return True

        result = self._exec(["systemctl", "stop", info.unit_file], timeout=_LIFECYCLE_TIMEOUT)
        self._update_stored_status(info.unit, "inactive")
        return result.success

    def restart(self, name: str) -> None:
        """
        Restart a service.

        Args:
            name: Service name.

        Raises:
            ServiceError: If the unit is not WASM's, does not exist, or systemd
                refuses to restart it.
            ValidationError: When the name is not a safe unit name.
        """
        info = self._require_managed(name, operation="restart")
        result = self._exec(["systemctl", "restart", info.unit_file], timeout=_LIFECYCLE_TIMEOUT)

        if not result.success:
            raise ServiceError(
                f"Failed to restart service: {info.unit}",
                details=result.stderr,
            )

        self._update_stored_status(info.unit, "active")

    def enable(self, name: str) -> bool:
        """
        Enable a service to start on boot.

        Args:
            name: Service name.

        Returns:
            True if systemd accepted the change.

        Raises:
            ServiceError: If the unit is not WASM's or does not exist.
            ValidationError: When the name is not a safe unit name.
        """
        info = self._require_managed(name, operation="enable")
        result = self._exec(["systemctl", "enable", info.unit_file])

        self._set_stored_enabled(info.unit, True)
        return result.success

    def disable(self, name: str) -> bool:
        """
        Disable a service from starting on boot.

        Args:
            name: Service name.

        Returns:
            True when the unit no longer starts on boot, including when it does
            not exist.

        Raises:
            ServiceError: If the unit exists but is not WASM's.
            ValidationError: When the name is not a safe unit name.
        """
        info = self._require_managed(name, operation="disable", missing_ok=True)
        if not info.exists:
            self.logger.debug(f"Nothing to disable: {info.unit} does not exist")
            return True

        result = self._exec(["systemctl", "disable", info.unit_file])

        self._set_stored_enabled(info.unit, False)
        return result.success

    def _update_stored_status(self, service_name: str, status: str) -> None:
        """
        Record a status change in the store, tolerating a missing record.

        Args:
            service_name: Resolved unit name.
            status: New status value.
        """
        try:
            self.store.update_service_status(service_name, status)
        except (WASMError, sqlite3.Error) as exc:
            self.logger.debug(f"Could not update service status in store: {exc}")

    def _set_stored_enabled(self, service_name: str, enabled: bool) -> None:
        """
        Record the enabled flag in the store, tolerating a missing record.

        Args:
            service_name: Resolved unit name.
            enabled: Whether the unit starts on boot.
        """
        try:
            svc = self.store.get_service(service_name)
            if svc:
                svc.enabled = enabled
                self.store.update_service(svc)
        except (WASMError, sqlite3.Error) as exc:
            self.logger.debug(f"Could not update service in store: {exc}")

    # Logs -----------------------------------------------------------------

    @staticmethod
    def _line_count(lines: int) -> str:
        """
        Normalise the number of journal lines to ask for.

        Args:
            lines: Requested line count.

        Returns:
            A positive integer as a string, ready for argv.

        Raises:
            ServiceError: When the value is not a number.
        """
        try:
            return str(max(1, int(lines)))
        except (TypeError, ValueError) as exc:
            raise ServiceError(
                f"Invalid number of log lines: {lines!r}",
                details="Pass a positive integer.",
            ) from exc

    def logs(self, name: str, lines: int = 50) -> str:
        """
        Get service logs.

        Args:
            name: Service name.
            lines: Number of lines to return.

        Returns:
            Log output, or journalctl's error output when it failed.

        Raises:
            ServiceError: If the unit is not WASM's or does not exist.
            ValidationError: When the name is not a safe unit name.
        """
        info = self._require_managed(name, operation="read the logs of")

        result = self._exec(
            ["journalctl", "-u", info.unit_file, "-n", self._line_count(lines), "--no-pager"]
        )
        return result.stdout if result.success else result.stderr

    def follow_logs(
        self,
        name: str,
        on_line: Callable[[str], None],
        lines: int = 50,
        timeout: int = _FOLLOW_TIMEOUT,
    ) -> None:
        """
        Follow service logs, delivering each line as it appears.

        ``wasm service logs --follow`` used to call :mod:`subprocess` directly,
        which is the one execution path the runner cannot enforce a deadline,
        a dry run or an audit record on.

        Args:
            name: Service name.
            on_line: Called once per line, without the trailing newline.
            lines: Number of past lines to replay before following.
            timeout: Deadline in seconds for the whole follow.

        Raises:
            ServiceError: If the unit is not WASM's or does not exist.
            ValidationError: When the name is not a safe unit name.
        """
        info = self._require_managed(name, operation="read the logs of")

        self.runner.stream(
            ["journalctl", "-u", info.unit_file, "-n", self._line_count(lines), "-f"],
            on_line=on_line,
            timeout=timeout,
        )

    def get_service_config(self, name: str) -> str | None:
        """
        Get service configuration content.

        Args:
            name: Service name.

        Returns:
            Unit file content, or None when WASM manages no such unit.

        Raises:
            ServiceError: If the unit exists but is not WASM's.
            ValidationError: When the name is not a safe unit name.
        """
        info = self._require_managed(name, operation="read", missing_ok=True)
        if not info.exists:
            return None

        try:
            return info.path.read_text()
        except OSError as exc:
            self.logger.debug(f"Could not read unit file {info.path}: {exc}")
            return None
